- federatedml/util/data_io.py
- federatedml/util/test/data_io_test.py
1. Adding svmlight sparse data input format in data_io.py
2. Adding uniitest for data_io, test file is data_io_test.py
> add sparse inputformat to data_io module with unittest

- arch/networking/proxy/src/main/java/com/webank/ai/fate/networking/proxy/infra/impl/PacketQueuePipe.java
Fixes  ISSUE#55
Changes:
1.add a line of code "if (isDrained()) return result;" between line 66 and line 67 of PacketQueuePipe.java(in arch/networking/proxy/src/main/java/com/webank/ai/fate/networking/proxy/infra/impl/)
> Feature 0.2 one second latency

- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/TransferJobScheduler.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/processor/SendProcessor.java
Fixes  ISSUE#207
Changes:
1.  there is a single loop thread in the class arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/TransferJobScheduler.java,   if the pressure is high ,  the single thread can not get thread from threadpool ,so it will throw exception ,then this thread will exit。so there is no thread to handle request 
2.arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/processor/SendProcessor.java
there  are  producer  and  consumer in this class，  but the order of  initialization  is  wrong ，
the  consumer  should  before  producer，because  the consumer sometimes will  initialize failed  under high pressure,  the producor will block  in that case，so  the thread in the threadpool will …
> fix federation crash bug

- fate_flow/db/db_models.py
- fate_flow/manager/tracking.py
- fate_flow/settings.py
1. delete flow sort tracking metric
2. metric key use pickle to store
Fixes  ISSUE #323 
Changes:
1. Use pickle to serializate metric key
2. Keep the original order when storing metrics, and restore order when reading
> Improve the fate-flow metric storage

- federatedml/secureprotol/affine.py
- federatedml/secureprotol/test/affine_test.py
Changes:
1. Unit test for affine cipher is added.
2. The precision for affine cipher encoder is adjustable now.
3. Now the addition for AffineCipherText only supports the same object and integer zero, and the multiplication only supports integer multipliers. These operators already satisfy the usage in SecureBoosting, while may need further extensions when implemented in other situations.
> affine unit test added

- arch/api/cluster/federation.py
Fixes  ISSUE#440
Changes:
1. there are too many debug in federations,
so remove some debug logs in api/cluster/federation.py
> remove some debug logs

- fate_flow/apps/tracking_app.py
Fixes  ISSUE #451 
Changes:
1. Download output data using a comma as a separator.
> fate_flow: download output data using a comma as a separator

- fate_flow/README.md
Changes:
1. The description of HTTP_PORT is "listen port for the grpc server of FATE-Flow" and changed to "listen port for the http server of FATE-Flow"
> Fix the description of HTTP_PORT

- federatedml/secureprotol/__init__.py
- federatedml/tree/hetero_secureboosting_tree_guest.py
- federatedml/util/consts.py
Changes:
1. add AFFINE/ITERATIVEAFFINE CONST in consts.py
2. add IterativeAffine support in tree/hetero_secureboosting_tree_guest.py
3. add Affine/IterativeAffine in secureprotol/init.py
Signed-off-by: sookieqinsookieqin@tencent.com
> add support for IterativeAffine in sbt 

- federatedml/secureprotol/iterative_affine.py
Changes:
Iterative Affine Cipher now correctly supports homomorphic subtraction.
Signed-off-by: clarkieliu clarkieliu@tencent.com
> iterative-affine subtraction debugged

- cluster-deploy/README.md
Fixes Bug:
After installing mysql, when you want to access mysql to empower all IP access, you will get Error by bellow statement, because the character '-' before 'S' should be Half-Angular, not Full-Angular.
--------------
$/data/projects/common/mysql/mysql-8.0.13/bin/mysql -ufate_dev -p –S /data/projects/common/mysql/mysql-8.0.13/mysql.sock
--------------
Changes:
1:  Modified a SQL statement (that empowering all IP access the mysql) in the Deployment Guide.
'–S' --> '-S'
> Fixbug：Modified a SQL statement (that empowering all IP access the mysql) in the Deployment Guide.

- fate_flow/driver/task_executor.py
描述：算法模块名结尾不能是p/y结尾，否则调用时会出现ModuleNotFoundError
Description: Customized module name ended with letter p or y, will raise ModuleNotFoundError when used 
原因：
在FATE1.0 /fate/python/fate_flow/driver/task_executor.py 模块96行有如下语句用于拼接模块路径
run_class_package = '.'.join(run_class_paths[:-2]) + '.' + run_class_paths[-2].rstrip('.py')
当模块名末尾含有p/y的时候，会被rstrip函数递归去掉出现在末尾的给定字符，导致无法找到模块
Cause:
Following code is used to concatenate module path in /fate/python/fate_flow/driver/task_executor.py line 96:
run_class_package = '.'.join(run_class_paths[:-2]) + '.' + run_class_paths[-2].rstrip('.py')
Letter p/y in the end of module name will be replaced recursively, leading to a  ModuleNotFoundError
举例：
例如当模块名叫做testonly.py, 会报ModuleNotFoundError: No module named 'federatedml.feature.testonl'错误
Example:
A module …
> Bug: Module name ended with letter p or y, will raise ModuleNotFoundError

- README.md
Signed-off-by: Layne Peng <playne@vmware.com>
Changes:
1. Since we have announce KubeFATE as one option to install FATE, I added this part of introduction in FATE installation section.
> Add KubeFATE as one option to install FATE in README file.

- federatedml/test/run_test.sh
Changes:
1. Add failed status in federatedml/test/run/test.sh for using ci-testing
2. Use Coverage to generate coverage report for code coverage statistics
> modify run_test by using coverage to run and exit state

- examples/federatedml-1.x-examples/hetero_linear_regression/README.md
- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_train_sparse_job_conf.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/README.md
- examples/federatedml-1.x-examples/hetero_poisson_regression/hetero_poisson_testsuite.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/test_hetero_poisson_train_sparse_job_conf.json
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
Fixes  ISSUE #1047
Changes:
1. Fix auto clean issue in LinR & Poisson Host by disabling auto clean for partial prediction transfer variable. 
2. Add example configuration file with sparse-data input for Hetero Poisson Regression.
3. Edit example doc to include sparse examples.
> Develop 1.3 sparse poisson

- federatedml/local_baseline/local_baseline.py
Fixes local baseline multi-class model output
Changes:
1. Change model output format of multi-class data (now same as LR one-vs-rest)
> fix local baseline model output

- arch/api/impl/based_1x/federation_cluster.py
- arch/api/impl/based_1x/federation_standalone.py
- arch/api/impl/based_2x/federation.py
- arch/api/session.py
- federatedml/nn/homo_nn/enter_point.py
Changes:
1. add check whether remote or get `None` obj
2.add check whether partition is provided when calling parallelize
3.fix homo nn parallelize bug
> Feature 1.4 check none federation

- examples/federatedml-1.x-examples/hetero_secureboost/test_secureboost_train_with_early_stopping_conf.json
Changes:
1. change num_trees from 100 in 5 in hetero_secureboost early stop examples
2.
3.
> modify num_tree in early stop examples

- federatedml/transfer_variable/base_transfer_variable.py
Changes:
1. deepcopy may create a new cleaner in the variable, overwriting the magic functions __deepcopy__ and __copy__ to avoid this from happening
> never copy or deepcopy to create new variable instance

- federatedml/conf/default_runtime_conf/data_split_param.json
- federatedml/param/data_split_param.py
Fixes default param value of Data Split
Changes:
1. only use default data set sizes if all size params are null
> Feature 1.5 data split fix

- federatedml/tree/__init__.py
- federatedml/tree/hetero/hetero_decision_tree_host.py
- federatedml/tree/hetero/hetero_secureboosting_tree_host.py
- federatedml/tree/tree_core/fast_feature_histogram.py
Reduce running time of histogram calculation when iterative affine is used as encryptor. Test OK under default setting (both use_missing and zero_as_missing are false), but weird behavior appear when zero_as_missing  are true, which is to be fixed.
> Reduce running time of histogram

- doc/dsl_conf_v2_setting_guide.rst
- doc/job_config_guide_zh.md
- python/fate_arch/federation/rabbitmq/_federation.py
- python/fate_arch/federation/rabbitmq/_mq_channel.py
- python/fate_arch/federation/rabbitmq/_rabbit_manager.py
- python/fate_flow/entity/types.py
Extend rabbitmq manager to support more runtime config.
A user can specify arguments for rabbitmq in runtime config of the job in this way:
```
{
...
"job_parameters" : {
"rabbitmq_run" : {
"queue": {...},
"upstream": {...},
"connection": {...},
"max_message_size": {...}
}
}
}
```
The parameters are described as follows:
- queue: parameters for queue creation
- upstream: parameters for setting federated upstream
- connection: parameters to config client-broker connections
- max_message_size: specify the limitation of message size to send
> Update rabbit manager

- python/federatedml/statistic/union/union.py
Changes:
1. Union module outputs empty table when all input are empty
2.
3.
> edit union output for emtpy table

- python/federatedml/statistic/union/union.py
Changes:
1. modify union keep_duplicate logic:key will always change (append dataset as suffix)
2.
3.
> edit union to append dataset as suffix when keep_duplicate is true

- python/fate_arch/common/file_utils.py
- python/fate_client/flow_sdk/utils.py
- python/fate_flow/service.sh
-------
Changes:
1. FATE could infer fate base directory from environment variable `FATE_DEPLOY_BASE`
Reason:
make it possible to deploy `FATE` to different directory other than `source code directory` with symlink and keep source code directory clean
1. copy bin and conf directory to deploy base directory
2. add soft symlink to `source` directories and files: examples, python and fate.env 
deploy directory structure:
``` sh
Permissions Size User Date Modified Name
drwxr-xr-x     - sage  6 Feb 19:53  bin
drwxr-xr-x     - sage  6 Feb 19:53  conf
lrwxr-xr-x    25 sage  6 Feb 19:56  examples -> /Users/sage/FATE/examples
lrwxr-xr-x    25 sage  6 Feb 19:57  fate.env -> /Users/sage/FATE/fate.env
lrwxr-xr-x    23 sage  6 Feb 19:52  python -> …
```
> add environment variable `FATE_DEPLOY_BASE`

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/param/boosting_param.py
Change the default value to 1.0 in subsample_feature_rate's annotation for the coherence value in code.
> Fix misleading annotation of subsample_feature_rate

- docker-build/docker/modules/python-nn/Dockerfile
The tensorflow version of python-nn Dockerfile is inconsistent with requirements.txt, causing docker build to report an error.
> fix: docker build of python-nn

- docker-build/docker/modules/eggroll/Dockerfile
`egg_pair_bootstrap.sh` use `strace` to record system call. 
But eggroll image haven't install the command yet.
https://github.com/WeBankFinTech/eggroll/blob/3f13c7aba12af3cec1002735e915040174dd1867/bin/roll_pair/egg_pair_bootstrap.sh#L185
> Update eggroll dockerfile: install strace

- examples/dsl/v2/homo_secureboost/README.md
`test_secureboost_cross_validation_dsl.json` is a dsl config file, but in cross validation multi-class example, it was `test_secureboost_cross_validation_binary_conf.json`
Changes:
1.
dsl config file in Multi-Class, Cross Validation
> Update README.md about dsl config files

- python/fate_flow/pipelined_model/pipelined_model.py
- python/fate_flow/tests/model_tests/define_meta.yaml
- python/fate_flow/tests/model_tests/pipelined_model_test.py
- python/requirements.txt
1. do not write meta file when define_index has not been changed
2. only write meta file once when define_index is changed
3. add lock before writing files
> bugfix: modify component meta file only when necessary

- python/fate_flow/apps/model_app.py
- python/fate_flow/doc/fate_flow_http_api.rst
- python/fate_flow/examples/homo_deploy_model.json
- python/fate_flow/pipelined_model/homo_model_deployer/__init__.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/__init__.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/_dummy_base_handler.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/base.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/model_storage/__init__.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/model_storage/base.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/model_storage/minio.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/pytorch.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/sklearn.py
- python/fate_flow/pipelined_model/homo_model_deployer/kfserving/tensorflow.py
- python/fate_flow/pipelined_model/homo_model_deployer/model_deploy.py
- python/fate_flow/pipelined_model/publish_model.py
- python/federatedml/protobuf/homo_model_convert/homo_model_convert.py
- python/requirements.txt
- python/setup.py
Changes:
1. Add a "model/homo/deploy" rest api in fate_flow.
2. Implement a deployer of type KFServing, using a separate MinIO service as model storage.
After the change, users can create a KFServing InferenceService with this newly added API.
> Feature 1.7 deploy homo model: fate_flow changes

- .gitignore
- python/fate_flow/db/db_models.py
- python/fate_flow/pipelined_model/migrate_model.py
- python/fate_flow/pipelined_model/mysql_model_storage.py
- python/fate_flow/pipelined_model/pipelined_model.py
- python/fate_flow/pipelined_model/redis_model_storage.py
- python/fate_flow/settings.py
- python/fate_flow/tests/model_tests/pipelined_model_test.py
1. import `__main__ ` is not a good practice
2. `str.find` returns `-1` if substr is not found
3. fix typo `varify` -> `verify`
4. change `PipelinedModel.archive_model_base_path` and `PipelinedModel.archive_model_file_path` to property
5. return itself when `deepcopy` `PipelinedModel`
6. check model local cache exists and raise user friendly error message
7. add hash check in unpack model archive
8. close file as soon as possible after file opened
> 1.5.2: bugfix

- conf/service_conf.yaml
- docker-build/build_cluster_docker.sh
- docker-build/docker/base/Dockerfile
- docker-build/docker/modules/python-nn/Dockerfile
- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_mq_channel.py
- python/fate_arch/federation/pulsar/_pulsar_manager.py
- python/requirements.txt
1. Update docker build
2. Support using specified pulsar cluster and tenant
- add 'cluster' and 'tenant' to pulsar field of fateflow's config
- it is necessary to unify tenant name between different parties
3. Optimize the unsubscribtion mechanism
- move set ttl to namespaces' creation
- unsubscribe once job was finished
4. Update Pulsar Usage
- enable subscription-replicate feature
- enable retention to keep topic alive without subscription
- improve the check alive in connection
5. Improve the cleanup process of Pulsar namespace
- remove all subscription
- remove all retention policy
- remove all remote cluster
fastavro is required, which can be referred to https://pulsar.apache.org/docs/fr/client-libraries-python/#optional-dependencies
> Improve the Implement of Pulsar Federation Engine

- python/fate_flow/fate_flow_server.py
Changes:
1. Pass related loggers when setting up the instances so any exceptions during the while-loop would be logged instead of being raised and causing the thread to exit.
> Fix: catch and log exceptions in Detector and DAGScheduler thread

- python/federatedml/model_selection/data_split/data_split.py
Changes:
1. Change filter function to join function in data_split component.
By changing filter to join function, data_split component running time can be extremely optimized. For example, when dealing with a dataset with 3,000,000 elements, the cost decrease from 20,000 seconds to almost 200 seconds in my environment.
> perf(data_split): change filter function to join

- .github/workflows/pypi.yml
Changes:
1. Add github action to release package to PyPI
1. use branch named pypi/<version>/develop to trigger package release to pypitest for test
2. use branch named pypi/<version>/release to trigger package release to pypi for product
Please double check before release a package since re-upload to PyPI with same package version is not allowed!
> 👷 Add github action for PyPI release

- python/federatedml/framework/weights.py
Signed-off-by: gxcuit gxcuit@163.com
Fixes  ISSUE #3475
Changes:
1. Add `__rmul__` and `__radd__` to support reflected (swapped) operands.
> add `__rmul__` and `__radd__` in weights

- python/fate_arch/storage/localfs/_table.py
Changes:
1. all files startswith `.` or `_` are ignore from hdfs reading
fix #3595
> ignore hidden files from hdfs file reading

- python/fate_arch/computing/eggroll/_csession.py
Changes:
1. enable in memory computing output option for eggroll engine according to pull request https://github.com/WeBankFinTech/eggroll/pull/568
this fix issue #3749
> enable in memory output for eggroll computing engine

- bin/common.sh
Signed-off-by: gxcuit <gxcuit@163.com>
Fixes  ISSUE #3526 
Changes:
1. add `shopt -s expand_aliases` in bin/common.sh
When deploying FATE in ubuntu using the compiled installer, it will incur a `fate_sed_cmd: command not found error. It is because 
> Aliases are not expanded when the shell is not interactive, unless the expand_aliases shell option is set using shopt
Please kindly refer to #3526 and [https://stackoverflow.com/questions/24054154/how-do-create-an-alias-in-shell-scripts](stackoverflow)
> Fix #3526, fix  standalone deployment when using the compiled installer

- python/federatedml/util/data_transform.py
Fix null value convert error when set exclusive_data_type for specify columns in DataTransform component.
When the output format of data_transform is dense, and configured exclusive data type for columns , data_transform component will occur convert value error if column value is null(default data type is float). 
if exclusive_data_type configured, the missing_impute value check is not worked.
Signed-off-by: Atisan <ling.java@gmail.com>
Changes:
1. federatedml/util/data_transform.py
> Fix value convert error exception

- python/federatedml/framework/hetero/sync/gradient_sync.py
@jat001 @dylan-fan @zhihuiwan 
修改文件：
python/federatedml/framework/hetero/sync/gradient_sync.py
修改内容：
@abc.abstractclassmethod已废弃停用，更新为@abc.abstractmethod
> @abc.abstractclassmethod已废弃停用，更新为@abc.abstractmethod

- build/docker-build/docker/base/Dockerfile
- build/docker-build/docker/modules/eggroll/Dockerfile
Signed-off-by: Chen Jing <jingch@vmware.com>
Fixes  #3854
1. The pyspark module is a pretty large one, no need to be installed on the base image stage, because eggroll archetecture do not need this module at all. This can save about 210MB for the compressed size of eggroll and python images.
2. There is no compiling requirement for the eggroll image, so no need to install the java-1.8.0-openjdk module.
eggroll: 858 MB -> 635 MB
python: 814 MB -> 606 MB
Verified that we can upload data and train a module successfully in 2 modes:
1. eggroll mode
2. spark+rabbitmq mode
> Reduce the necessary size of the base and eggroll images

- python/fate_test/fate_test/scripts/data_cli.py
import torchvision is quite slow, which
slowdown other subcommand in fate_test.
move torchvision import to specificated
function and lazy import when needed.
> refactor: lazy import torchvision

- python/requirements.txt
1. use pulsar-client == 2.10.0 for macos since 2.10.1 for macos not published
2. remove markdown since 3.3.5 is yanked
> chore: platform specific syntax for pulsar-client

- doc/tutorial/pipeline/pipeline_tutorial_upload.ipynb
The notebook is missing `os` package import. "Run all cells" would fail due to this.
Signed-off-by: orionHong orionxhr@outlook.com
Changes:
1. Just added `import os` to the notebook.
> Fix missing "import os" for upload tutorial

- python/requirements.txt
Signed-off-by: Chen Jing <jingch@vmware.com>
The purpose for this pip package is for package the python virtual environment in fateflow.
Reference: https://github.com/FederatedAI/FATE-Flow/pull/352
> add venv-pack into requirements for dependence distribution purpose

- .travis.yml
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-exchange_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/common/hadoop_spark_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/common/hadoop_spark_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.zh.md
- deploy/cluster-deploy/upgrade/1_4_0-1_5_1/fate_upgrade_zh.md
- deploy/cluster-deploy/upgrade/1_4_3-1_5_1/fate_upgrade_zh.md
- deploy/cluster-deploy/upgrade/1_4_4-1_5_1/fate_upgrade_zh.md
- deploy/cluster-deploy/upgrade/1_5_0-1_5_1/resource/fate_upgrade_zh.md
- deploy/cluster-deploy/upgrade/1_5_0-1_5_1/resource/upgrade.sh
- deploy/cluster-deploy/upgrade/eggroll_2_0_x-2_2_1/upgrade_helper_guide_zh.md
- python/federatedml/test/README.md
On Centos, `sh` is linked to `bash`. On Ubuntu, `sh` is linked to `dash`.
`dash` is not compatible with `bash`. See #4494.
> use bash instead of sh

- python/fate/components/components/hetero_lr.py
- python/fate/components/entrypoint/component.py
- python/fate/components/params/__init__.py
- python/fate/components/params/_cipher.py
- python/fate/components/params/_fields.py
- python/fate/components/params/_learning_rate.py
- python/fate/components/params/_optimizer.py
- python/fate/components/params/_penalty.py
-------
enhance params
Changes:
1. add constrained params by pydantic
2. add build-in params type such as learning_rate, penality, optimizer
3. add jsonschema generation
> (beta) enhance params

- python/fate_arch/computing/spark/_table.py
implemented exactly_sample function for spark will failed when there are partitions empty(ie: partition sums close or greater than num data)
this pull request fix #4721
> fix exactly_sample for spark (#4721)

- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
在训练过程中，指定参与分箱的列(bin_names)， 并且设置不同的转换类型（如箱号、woe）等参数（transform_param.transform_cols 和transform_param.transform_type)， 训练过程结束后，数据能够按预期的进行数据转换或者不处理，但是在离线预测任务中，由于缺失对应的参数，导致预测结果的数据转换后与训练过程的转换逻辑不一致
Signed-off-by: jsuper <ling.java@gmail.com>
如何重现：
1、在纵向特征分箱任务中，指定部分列参与计算，并且设置不同的变量转换方式。
2、训练完成后，使用该训练任务的模型进行离线预测，组件执行报错或者数据未按预期进行转换。
Changes:
1. 加载模型时，加载对应参数
> 修复特征分箱组件在预测任务中行为不一致的问题

- doc/tutorial/fate_llm/GPT2-example.ipynb
- doc/tutorial/fate_llm/GPT2-multi-task.ipynb
> update doc of guidelines

- python/fate/arch/dataframe/ops/_cmp.py
Changes:
1. dataframe fix: cmp between tensor and np.ndarray/pd.Series
> dataframe fix: fix cmp between tensor and ndarray/pd.Series

- examples/pipeline/test_linr_sid_cv.py
- examples/pipeline/test_lr_sid.py
- examples/pipeline/test_lr_sid_cv.py
- examples/pipeline/test_single_linr.py
- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_encoder.py
- python/fate/arch/dataframe/ops/_quantile.py
- python/fate/arch/dataframe/utils/_dataloader.py
- python/fate/components/components/coordinated_linr.py
- python/fate/components/components/coordinated_lr.py
- python/fate/components/core/component_desc/_parameter.py
- python/fate/components/core/params/__init__.py
- python/fate/components/core/params/_cv_param.py
- python/fate/ml/glm/hetero/coordinated_linr/guest.py
- python/fate/ml/glm/hetero/coordinated_lr/guest.py
- python/fate/ml/utils/_model_param.py
- python/fate/ml/utils/_optimizer.py
Fixes  ISSUE #4659
Changes:
1. add cv to Coordinated LR & LinR
2. fix optimizer
3.
> Dev 2.0.0 beta debugging

- python/fate/arch/context/_context.py
- python/fate/arch/context/_federation.py
> serde support ctx

- python/fate/arch/dataframe/_frame_reader.py
- python/fate/arch/dataframe/conf/default_config.py
- python/fate/arch/dataframe/manager/data_manager.py
- python/fate/arch/dataframe/ops/_dimension_scaling.py
- python/fate/arch/dataframe/ops/_indexer.py
- python/fate/arch/dataframe/ops/_where.py
- python/fate/arch/dataframe/utils/_sample.py
Changes:
1. add block_row_size to manager single block size
2. fix where op, _sample_util bug
3. fix retrieval row api
> Feature 2.0.0 beta dataframe refact

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_indexer.py
Changes:
1. optimize dataframe interface for psi
2. fix zero item error when psi result is zero
> dataframe: optimizer indexer for psi

- python/fate/arch/dataframe/conf/default_config.py
- python/fate/arch/dataframe/ops/_compress_block.py
- python/fate/arch/dataframe/ops/_histogram.py
Changes:
1. optmizer block compress: compress when multiple block exists
> dataframe: update block compress logic

- python/fate/arch/dataframe/manager/schema_manager.py
Signed-off-by:  mgqa34 mgq3374541@163.com
Changes:
1. fix bug: df[cols] will be in old orders before fixed, df[["x1", x0"]] = df[["x0", "x1"]]
> dataframe: fix getitem attr order

- python/fate/arch/histogram/_histogram_sbt.py
> add support for cumsum flag for histogram

- doc/tutorial/pipeline/pipeline_tutorial_match_id.ipynb
import os is missing in pipeline_tutorial_match_id.ipynb code block
Signed-off-by: brandonJY@users.noreply.github.com
> add import os in pipeline_tutorial_match_id.ipynb

- python/fate/ml/nn/hetero/hetero_nn.py
- python/fate/ml/nn/model_zoo/agg_layer/agg_layer.py
- python/fate/ml/nn/model_zoo/hetero_nn_model.py
- python/fate/ml/nn/test/test_fedpass_lenet.py
- python/fate/ml/nn/trainer/trainer_base.py
> Dev 2.0.0 rc nn update

- python/fate/arch/computing/backends/standalone/_csession.py
- python/fate/arch/computing/backends/standalone/_standalone.py
> refactor standalone: simplify requirements

- python/fate/arch/dataframe/ops/_indexer.py
…is empty
Changes:
1. dataframe: fix transform_flatten_data_to_dataframe when flatten_data is empty
> DataFrame Bug Fix When PSI Result Equals to 0

- python/fate/components/core/component_desc/artifacts/data/_dataframe.py
- chore: remove metadata in dataframe write since it may be large
- chore: remove metadata in dataframe read since it may be large too
> chore 2.0.0 rc remove dataframe write log

- RELEASE.md
- doc/2.0/fate/performance.md
Changes:
1. Update Performance  documents
> Feature 2.0.0 rc update doc

- README.md
- README_zh.md
- doc/2.0/fate/components/linear_regression.md
- doc/2.0/fate/components/logistic_regression.md
- doc/2.0/fate/quick_start.md
> doc update
