- examples/intersect/conf/guest_runtime_conf.json
- examples/intersect/conf/host_runtime_conf.json
- federatedml/param/param.py
- federatedml/secureprotol/encode.py
- federatedml/secureprotol/test/encode_test.py
- federatedml/statistic/intersect/__init__.py
- federatedml/statistic/intersect/intersect.py
- federatedml/statistic/intersect/intersect_guest.py
- federatedml/statistic/intersect/intersect_host.py
- federatedml/transfer_variable_conf/transfer_conf.json
- federatedml/util/transfer_variable.py
Fixes  ISSUE#8
Changes:
1.add Encode class
2.RSA intersection will send encrypted intersection results
3.RAW intersection's role can be configured
4.RAW intersection configure if encode for each role
> intersection upgrade for 0.2v

- examples/intersect/conf/guest_runtime_conf.json
- examples/intersect/conf/host_runtime_conf.json
- federatedml/evaluation/evaluation.py
- federatedml/evaluation/test/evaluation_test.py
- federatedml/param/param.py
- federatedml/util/consts.py
Fixes  ISSUE#29
Changes:
add regression evaluation methods， include:
1.mean_absolute_error
2.mean_squared_error
3.mean_squared_log_error
4.median_absolute_error
5.r2_score
6.root_mean_squard_error
7.fix some format project of evaluation
> add regression evaluation and fix some format

- examples/hetero_logistic_regression/conf/arbiter_runtime_conf.json
- examples/hetero_logistic_regression/conf/guest_runtime_conf.json
- examples/hetero_logistic_regression/conf/host_runtime_conf.json
- federatedml/param/param.py
- federatedml/statistic/intersect/__init__.py
- federatedml/statistic/intersect/intersect.py
- federatedml/statistic/intersect/intersect_guest.py
- federatedml/statistic/intersect/intersect_host.py
- workflow/workflow.py
Fixes  ISSUE#14
Changes:
add raw intersection before hetero train, predict and cross_validation
@tanmc123 please check if this change of workflow has some unexpections of HOMO
@mgqa34 please check if this change of HETERO satifies the HETERO of tree
@yankang18 you can focus on this change
> add intersect before train, predict and cross_validation

- examples/toy_example/secure_add_guest.py
- examples/toy_example/secure_add_host.py
- federatedml/transfer_variable_conf/transfer_conf.json
- federatedml/util/__init__.py
- federatedml/util/transfer_variable.py
Fixes  ISSUE#35 Toy Example
Changes:
1. Add toy example for quickstart case and testcase of the successful deployment
> add toy example for quick start

- examples/toy_example/secure_add_guest.py
- examples/toy_example/secure_add_guest_workflow.py
- examples/toy_example/secure_add_host.py
- examples/toy_example/secure_add_host_workflow.py
Fixes  ISSUE#35
Changes:
add secure add workflow program to simulate the full process of fate modeling
> add secure add workflow program to call secure add instance

- examples/hetero_ftl/run_guest.py
- examples/hetero_ftl/run_host.py
- examples/hetero_ftl/save_UCI_Credit_card_data_util.py
- federatedml/ftl/encrypted_ftl.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_arbiter.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
Changes:
1. Add description for handlers that perform feature transformation/extraction on raw input of logistic regression model.
> Add desription for dnn-based lr handlers

- arch/api/standalone/eggroll.py
Fixes  ISSUE#57
Changes:
1. cleanup API for standalone mode.
> 1. Cleanup api for standalone mode.

- examples/hetero_logistic_regression/run_logistic_regression.sh
- examples/hetero_logistic_regression/run_logistic_regression_cluster.sh
Fixes  hetero-lr run cluster example.
just modify two shell
run_logistic_regression_cluster.sh
run_logistic_regression.sh
> fix hetero-lr run cluster shell.

- examples/hetero_secureboosting_tree/conf/load_file.json
- federatedml/toy_example/secure_add_guest.py
- federatedml/toy_example/secure_add_host.py
- federatedml/tree/hetero_decision_tree_guest.py
- federatedml/util/data_io.py
Fixes bugs of secure-boost examples and secureboot, toy_example
> Feature 0.2 fix secureboost bugs

- examples/hetero_feature_binning/conf/guest_runtime_conf.json
- examples/hetero_feature_binning/conf/host_runtime_conf.json
- examples/hetero_feature_binning/conf/load_file.json
- examples/hetero_feature_binning/load_file_functions.py
- examples/hetero_feature_binning/run_feature_binning_clustering.sh
- examples/hetero_feature_binning/run_feature_binning_standalone.sh
- examples/hetero_feature_selection/conf/guest_runtime_conf.json
- examples/hetero_feature_selection/conf/host_runtime_conf.json
- examples/hetero_feature_selection/conf/load_file.json
- examples/hetero_feature_selection/load_file_functions.py
- examples/hetero_feature_selection/run_feature_selection.py
- examples/hetero_feature_selection/run_feature_selection_clustering.sh
- examples/hetero_feature_selection/run_feature_selection_standalone.sh
- examples/hetero_feature_selection/show_data.sh
- examples/hetero_feature_selection/show_model.sh
- examples/hetero_feature_selection/show_result.py
Changes:
1. Change feature binning script
2.
3.
> Feature 0.2 feature selection

- workflow/status_tracer_decorator.py
Fixes  ISSUE#85
Changes:
disabled clean up api in status_tracer_decorator
> fix bugs of status tracer

- arch/core/src/main/java/com/webank/ai/fate/core/factory/GrpcChannelFactory.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/action/SendConsumeAction.java
- arch/eggroll/roll/src/main/java/com/webank/ai/fate/eggroll/roll/service/async/storage/IterateProcessor.java
- arch/networking/proxy/src/main/java/com/webank/ai/fate/networking/proxy/factory/GrpcStubFactory.java
1. Fixed a bug where iterate may return duplicate value.
2. Optimized federation module to send data by intervals.
> feature-0.2-arch to develop

- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/model_selection/mini_batch.py
- federatedml/optim/gradient/test/gradient_method_test.py
- federatedml/statistic/intersect/README.md
- workflow/conf/default_runtime_conf.json
Changes:
1. fix bugs in run test
2. When batch size set larger than size of data, change the batch size to data size
3.
> Feature 0.2 fix bugs 4 15

- RELEASE.md
- examples/task_manager_examples/README.md
Changes:
1. add FATE v0.2 Release
2. Delete task manager example readme "Request Offline Feature"
> Feature 0.2 release doc

- federatedml/feature/README.md
- federatedml/util/README.md
Changes:
1. Add Imputer README
2. Add DataIO README
> Add README of imputer and dataio

- arch/task_manager/job_manager.py
- arch/task_manager/task_manager_server.py
Reverts WeBankFinTech/FATE#115
> Revert "fix task manager can not stop job bug"

- examples/task_manager_examples/test_hetero_lr_workflow.json
- examples/task_manager_examples/test_intersect_workflow.json
update intersect and hetero-lr configure for taskmanager
> update intersect and hetero-lr configure

- arch/proto/feature-binning-meta.proto
- arch/proto/feature-binning-param.proto
- arch/proto/feature-selection-meta.proto
- arch/proto/feature-selection-param.proto
- federatedml/feature/hetero_feature_binning/base_feature_binning.py
Changes:
1. fix feature binning bugs
2. Add protos file back
3.
> Feature 0.2 fit bug 4 22

- arch/task_manager/apps/workflow.py
- arch/task_manager/example_conf/test_hetero_lr_workflow.json
- arch/task_manager/job_manager.py
- arch/task_manager/task_manager_server.py
1. fill runtime conf in own party
2. fix task which not be started by tm post status hang
> fill runtime conf in own party

- requirements.txt
> Feature 0.2 serving

- arch/api/utils/upload.py
- arch/task_manager/example_conf/test_hetero_lr_workflow.json
- arch/task_manager/example_conf/test_intersect_workflow.json
- examples/load_file/load_file.py
- federatedml/feature/imputer.py
- federatedml/feature/scaler.py
- federatedml/feature/test/imputer_test.py
- federatedml/feature/test/min_max_scaler_test.py
- federatedml/feature/test/standard_scaler_test.py
- federatedml/param/param.py
- federatedml/statistic/intersect/intersect_host.py
- workflow/workflow.py
Changes:
1. fix load_file max partition limit 
2. fix imputer, outlier predict bug
3. fix some bugs.
> Feature 0.2 fix bug 5 14

- requirements.txt
> update some security version

- federatedml/secureprotol/fate_paillier.py
- federatedml/secureprotol/fixedpoint.py
- federatedml/secureprotol/test/fate_paillier_test.py
- federatedml/secureprotol/test/fixedpoin_test.py
and fixed some overflow bugs
Fixes  ISSUE#151
Changes:
1. Support add, sub, mul, div ,gt, lt ,eq, etc on fixed-point data
2. Fixed some overflow bugs in fixed-point data
> add operator on fixedpoint

- arch/build_py_proto.sh
- examples/hetero_logistic_regression/conf/arbiter_runtime_conf.json
- examples/hetero_logistic_regression/conf/guest_runtime_conf.json
- examples/hetero_logistic_regression/conf/host_runtime_conf.json
- federatedml/evaluation/evaluation.py
- federatedml/feature/imputer.py
- federatedml/feature/min_max_scaler.py
- federatedml/feature/scaler.py
- federatedml/feature/standard_scaler.py
- federatedml/logistic_regression/base_logistic_regression.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_arbiter.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/one_vs_rest/one_vs_rest.py
- federatedml/optim/federated_aggregator/hetero_federated_aggregator.py
- federatedml/optim/gradient/logistic_gradient.py
- federatedml/param/param.py
- federatedml/secureprotol/__init__.py
- federatedml/secureprotol/encrypt_mode.py
- federatedml/util/fate_operator.py
- workflow/workflow.py
Fixes ISSUE #136， #126
Changes:
1.add one_vs_rest module
2.hetero-lr support different calculation mode
3.add some doc and fix bugs
> add one_vs_rest

- federatedml/one_vs_rest/one_vs_rest.py
Changes:
1.fix one_vs_rest save_model namespace
> fix one_vs_rest save_model namespace

- federatedml/one_vs_rest/one_vs_rest.py
Fixes  ISSUE #170 
Changes:
1.fix label type not match bug
> fix one_vs_rest predict label type not match input_data type bug

- federatedml/feature/feature_selection.py
- federatedml/util/param_checker.py
Fixes  ISSUE #177 
Changes:
1. feature_selection: rename "mata" to "meta"
2. param_checker:  recovery some object overried in previous pull request
> fix bug of param-check and feature-selection

- fate-serving/serving-server/pom.xml
Fix dependency package configuration bugs that cause fate-serving deployment failures on some machine
> Feature 0.3 serving

- arch/api/cluster/eggroll.py
- arch/eggroll/roll/src/main/java/com/webank/ai/fate/eggroll/roll/service/async/callback/PutAllProcessorListenableFutureCallback.java
- arch/pom.xml
1. Rolled back map API change.
2. Minor enhancements.
> Feature 0.3 arch

- federatedml/feature/one_hot_encoder.py
Changes:
1. fix a onehot bug:  detect onehot max column overflow
> fix one-hot bugs

- README.md
- build_standalone_docker.sh
- cluster-deploy/README.md
- cluster-deploy/scripts/auto-deploy.sh
- cluster-deploy/scripts/auto-packaging.sh
- cluster-deploy/scripts/configurations.sh
- cluster-deploy/scripts/fate-base/install_redis.sh
- requirements.txt
Changes:
1.update docker single node deploy guide
2.update deploy scripts
3.update requirements.txt,delete three packages that no need.
> Feature 0.3 deploy

- contrib/paillier/Makefile
- contrib/paillier/paillier.cu
- contrib/paillier/test.cu
CHANGE
1 add contrib folder & pailler CGBN test code
> paillier CGBN

- arch/processor/processor.py
1. Fixed a bug when computing with little data.
> 1. Fixed a bug when little data not creating empty db.

- README.md
- cluster-deploy/README.md
Changes:
1.Update software description.
> Update software description

- RELEASE.md
Changes:
1. add fate v0.3 content to release.md
2.
3.
> add release v0.3

- RELEASE.md
> add eggroll updates to release.md

- fate-serving/README.md
> update fate-serving readme

- federatedml/feature/README.md
- federatedml/logistic_regression/README.md
- federatedml/one_vs_rest/README.md
- federatedml/tree/README.md
- federatedml/util/README.md
Fixes  ISSUE #248 
Changes:
1. add one_vs_rest readme
2. add one-hot readme
3. update lr readme
4. update tree readme
5. add dataio readme
> Feature 0.3 algorithm readme

- eggroll/core/pom.xml
> update jackson 2.9.9

- RELEASE.md
- cluster-deploy/README.md
- cluster-deploy/scripts/auto-deploy.sh
- cluster-deploy/scripts/auto-packaging.sh
- cluster-deploy/scripts/configurations.sh
- cluster-deploy/scripts/modify_json.py
> update deploy doc

- eggroll/core/pom.xml
Reverts WeBankFinTech/FATE#292
> Revert "Develop"

- arch/api/utils/log_utils.py
- arch/core/pom.xml
ISSUE#315
Changes:
1. divide the logs into levels files.
> Feature 1.0 logutils

- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/TransferJobScheduler.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/action/DtableRecvConsumeAction.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/processor/RecvProcessor.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/transfer/communication/processor/SendProcessor.java
- arch/driver/federation/src/main/java/com/webank/ai/fate/driver/federation/utils/ThreadPoolTaskExecutorUtil.java
Fixes  ISSUE#318
Changes:
1.add retry operation when using thread pool  in  the federation model
> add retry to thread pool

- federatedml/evaluation/evaluation.py
Fixes  ISSUE #321 
Changes:
1.fix evaluation regression checker bug
> Feature 1.0 evaluation fix bugs

- docker/standalone/Dockerfile
Fixes  ISSUE#327
Changes:
1. ubuntu don't support libmpfr4. So need an update to libmpfr6
> update standalone dockerfile

- arch/api/model_manager/manager.py
- arch/api/proto/pipeline_pb2.py
- arch/proto/pipeline.proto
- fate_flow/apps/job_apps.py
- fate_flow/driver/job_controller.py
- fate_flow/manager/model_manager.py
- fate_flow/manager/pipeline_manager.py
- fate_flow/manager/tracking.py
- fate_flow/service.sh
- fate_flow/utils/grpc_utils.py
Fixes  ISSUE #329 
Changes:
1. fix task status sync error on cluster mode
2. fix save data table on cluster mode
> fate_flow: fix some bug on cluster mode

- arch/core/src/main/java/com/webank/ai/fate/core/utils/Configuration.java
- arch/core/src/main/java/com/webank/ai/fate/core/utils/ObjectTransform.java
- fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
Fixes  ISSUE#325
Changes:
Fate-core adds support for utf8 encoding of JSON files
Fate-serving modifies the logic when the remote end returns to non-zero
Fate-core adds logs when errors occur
> fate-serving/fate-core improvement 

- doc/api/eggroll_api.md
- doc/api/federation_api.md
Fixes  ISSUE #334 
Changes:
1. add api-doc of eggroll and federation
> update arch api doct

- arch/core/src/main/resources/jdbc.properties
- arch/eggroll/meta-service/src/main/resources/jdbc.properties
- cluster-deploy/doc/configuration.md
- cluster-deploy/example-dir-tree/meta-service/conf/jdbc.properties
- eggroll/core/src/main/resources/jdbc.properties
- eggroll/framework/meta-service/src/main/resources/jdbc.properties
Changes:
For security, IP info ect needs to be removed
fixes  ISSUE#340
Changes:
1.jdbc.properties
2.configuration.md
> EggRoll  sensitive information remove#340

- federatedml/secureprotol/affine.py
- federatedml/secureprotol/affine_encoder.py
- federatedml/secureprotol/encrypt.py
Fixes  ISSUE#353
Changes:
1. Affine cipher method added
2. A simple and intuitive encoding method compatible with affine cipher added
> affine cipher encryption method added

- federatedml/secureprotol/affine.py
- federatedml/secureprotol/affine_encoder.py
Changes:
1. use SystemRandom()
2. use fate_gmpy2
3. header added
> Contributor affine cipher

- examples/hetero_ftl/run_arbiter.py
- examples/hetero_ftl/run_guest.py
- examples/hetero_ftl/run_host.py
- federatedml/ftl/hetero_ftl/hetero_ftl_host.py
- federatedml/param/predict_param.py
- federatedml/param/workflow_param.py
- workflow/hetero_ftl_workflow/hetero_workflow.py
- workflow/workflow.py
Changes: Make FTL compatible with FATE 1.0
1. Update legacy workflow to enable FTL to be compatible with FATE 1.0
2. Add necessary param py files
> fix ftl compatibility

- fate_flow/db/db_models.py
- fate_flow/entity/runtime_config.py
- fate_flow/manager/tracking.py
Fixes  ISSUE #407 
Changes:
1. fix too many SQL variables error on sqlite
> fate_flow: fix too many SQL variables error on sqlite

- fate_flow/driver/job_controller.py
- fate_flow/manager/tracking.py
Fixes  
Changes:
1. modify submit job model info format
> fate_flow: modify submit job model info format

- fate-serving/fate-serving-core/pom.xml
- fate-serving/federatedml/pom.xml
- fate-serving/pom.xml
- fate-serving/serving-server/pom.xml
> Develop 1.0 merge

- examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_cv_job_conf.json
- examples/min_test_task/run_task.py
- federatedml/feature/quantile_summaries.py
- federatedml/optim/convergence.py
- federatedml/param/encrypt_param.py
Fixes  ISSUE# 412
Changes:
1. Fix bugs in binning 
2. Fix bugs in min-test-task
> Feature 1.0 algorithm fix 20190812

- examples/min_test_task/README.md
- examples/min_test_task/run_task.py
Fixes  ISSUE# 373
Changes:
1. Fix min-test-task bug
2. Add min-task README doc
> Add min-test-task README

- examples/toy_example/run_toy_example.py
- examples/toy_example/toy_example_conf.json
Fixes  ISSUE #433 
Changes:
1. add running script for toy example
> add toy example running script

- contrib/fate_script/README.md
Fixes  ISSUE
Changes:
1.remove some info of FATE Script README.md
> fixed issue #434

- fateboard/src/main/java/com/webank/ai/fate/board/log/LogFileService.java
> add standalone params

- RELEASE.md
Fixes  ISSUE#456
Changes:
update 1.0 features in release.md
> update 1.0 release readme

- fate-serving/fate-serving-core/src/main/java/com/webank/ai/fate/serving/core/utils/ProtobufUtils.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/BaseModel.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/DataIO.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/FeatureSelection.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/HeteroLR.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Scale.java
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/Scaler.java
- fate_flow/apps/tracking_app.py
- fate_flow/fate_flow_client.py
- fate_flow/manager/model_manager.py
- requirements.txt
Fixes  ISSUE #454 
Changes:
1. fix bug that read model error which has default values only on online inference
> Feature 1.0 flow

- standalone-deploy/Manual/README.md
Changes:  change  standalone readme
> change readme

- federatedml/README.md
> update federatedml readme

- examples/federatedml-1.0-examples/README.md
> Feature 1.0 algorithm fix

- fate-configuration-en-0.5.md
> merge from master

- standalone-deploy/README.md
Changes:
1.Feature 1.0 change deploy readme
> Feature 1.0 change deploy readme

- RELEASE.md
> update standalone deploy doc

- cluster-deploy/README.md
- standalone-deploy/README.md
2.update standalone readme. #489 
Changes:
1.update cluster readme.
2.update stabdalone readme.
> 1.update cluster readme.

- arch/core/src/main/java/com/webank/ai/fate/core/utils/RuntimeUtils.java
Fixes ISSUE#275 
Changes: add a more reliable function to get server ip host
> optimize the way to get local ip address

- doc/upload_data_guide.md
Fixes  ISSUE#505
Changes:
1. Example config in upload data guide is out of date
> Update upload_data_guide doc

- federatedml/evaluation/evaluation.py
- federatedml/feature/binning/base_binning.py
- federatedml/feature/quantile_summaries.py
- federatedml/feature/test/quantile_binning_test.py
- federatedml/model_base.py
Fixes  ISSUE #514 #510 #517
Changes:
1. Fix bugs for feature binning to take abnormal values into consideration
2. Fix bugs for train and eval
3. fix evaluation data type bug
> Feature 1.0.1 fix union bugs

- arch/api/utils/upload.py
- arch/api/utils/version_control.py
- cluster-deploy/example-dir-tree/serving-server/conf/serving-server.properties
- fate-serving/federatedml/src/main/java/com/webank/ai/fate/serving/federatedml/model/BaseModel.java
- fate-serving/serving-server/src/main/resources/serving-server.properties
Fixes  ISSUE #525 
Changes:
1. Support dataset versioning
2. Serving get serviceRoleName from configuration
> Feature 1.0.1 support dataset in version

- cluster-deploy/example-dir-tree/fateboard/conf/application.properties
- cluster-deploy/scripts/auto-deploy.sh
- fateboard/README.md
- fateboard/pom.xml
- fateboard/src/main/java/com/webank/ai/fate/board/controller/JobDetailController.java
- fateboard/src/main/java/com/webank/ai/fate/board/controller/JobManagerController.java
- fateboard/src/main/java/com/webank/ai/fate/board/utils/HttpClientPool.java
- fateboard/src/main/resources/application.properties
- standalone-deploy/README.md
- standalone-deploy/build_standalone_docker.sh
- standalone-deploy/docker/docker-compose-build.yml
- standalone-deploy/docker/fateboard/docker-entrypoint.sh
- standalone-deploy/docker/mysql/Dockerfile
- standalone-deploy/docker/mysql/init_database.sql
- standalone-deploy/docker/python/Dockerfile
Changes:
1. update fateboard node, support the sqlite database.
2.update deploy for the stanalone version
> Develop 1.0.2 sqlitdeploy

- RELEASE.md
> add 1.0.1 release

- federatedml/model_base.py
- federatedml/model_selection/KFold.py
Fixes  ISSUE #540 #514 
Changes:
1. Fix KFold bug
2. Fix train and eval bug
3.
> Fix KFold and model_base bugs

- federatedml/feature/fate_element_type.py
> update fate_element_type to support NoneType cmp

- fate-serving/serving-server/src/main/java/com/webank/ai/fate/serving/manger/InferenceManager.java
Signed-off-by: kaideng <forgive_dengkai@163.com>
Fixes  ISSUE#557
Changes:
1. copy the feature data,to avoid this exception
> fix feature bug

- README.md
> merge master to release 1.0.1

- fateboard/src/main/java/com/webank/ai/fate/board/log/LogFileService.java
- fateboard/src/main/java/com/webank/ai/fate/board/services/LogSshLoadService.java
Signed-off-by: happycooper.xu <g6xuyiming@163.com>
Changes:
1.update LogFileService.java and LogSshLoadService.java .
> fix bug of logs

- federatedml/evaluation/evaluation.py
Fixes  ISSUE #571
Changes:
1. fix a bug for evaluation with some dsl
> fix evaluation bug for some dsl

- README.md
- fateboard/README.md
> merge master to develop

- federatedml/README.md
- federatedml/feature/README.md
- federatedml/tree/README.md
Changes:
1. Edit README and add link to specific algorithm readme
> Editing README and add link to specific algorithm readme

- RELEASE.md
> add 1.0.2 release note

- RELEASE.md
> update 1.0.2 release note

- cluster-deploy/README.md
Changes:
1.Add a link to the Chinese guide.
> Add a link to the Chinese guide

- docker-build/README.md
> Add reference to KubeFate

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-V1.0 部署指南.md
Fixes  ISSUE#xxx #602 
Changes:
1.Fix bugs and improve instructions.
> Feature 1.0.2 deploy

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-V1.0 部署指南.md
- docker-build/README.md
> update cluster deploy doc 

- doc/api/eggroll_api.md
Fixes  ISSUE #626 
Changes:
1. Fix import error in eggroll api doc
> fix eggroll init error

- arch/api/utils/upload.py
- fate_flow/utils/upload.py
- federatedml/param/intersect_param.py
- federatedml/statistic/intersect/intersect.py
- federatedml/statistic/intersect/intersect_guest.py
- federatedml/statistic/intersect/intersect_host.py
- federatedml/statistic/intersect/intersect_model.py
- federatedml/statistic/intersect/rsa_cache/cache_utils.py
- federatedml/statistic/intersect/rsa_cache/db_models.py
- federatedml/statistic/intersect/rsa_cache/redis_adaptor.py
- federatedml/transfer_variable/definition/raw_intersect.json
- federatedml/transfer_variable/definition/rsa_intersect.json
- federatedml/transfer_variable/definition/transfer_conf.json
- federatedml/transfer_variable/transfer_class/raw_intersect_transfer_variable.py
- federatedml/transfer_variable/transfer_class/rsa_intersect_transfer_variable.py
- federatedml/util/consts.py
Fixes  ISSUE #587 #503 
Changes:
1.rsa and raw intersection support multi-host
2.rsa intersection support cache to speed up
> 1.add multi-host for raw intersect and rsa intersect

- cluster-deploy/README.md
> Fix markdown syntax problem

- federatedml/evaluation/evaluation.py
- federatedml/statistic/intersect/intersect.py
- federatedml/statistic/intersect/intersect_model.py
Fixes  ISSUE #571 
Changes:
1. fix bug, when a task has both train data and eval data, the evaluation will abandon one of them.
2. raw intersection add save_as guest id operation
> Feature 1.0.1 raw intersect reform

- federatedml/util/validation_strategy.py
Fixes  ISSUE #646 
Changes:
1. fix bugs of use same flowid when both validation and train data need validate during training process
> fix bugs both validation and train data need validate during training process

- fate_flow/apps/schedule_app.py
- fate_flow/driver/job_detector.py
- fate_flow/driver/task_scheduler.py
- fate_flow/manager/tracking.py
- fate_flow/utils/authentication_utils.py
> Fix flow bug

- fate_flow/driver/dsl_parser.py
- federatedml/tree/hetero_secureboosting_tree_guest.py
Fixes  ISSUE #663 
Changes:
1.
2.
3.
> fix bugs of secureboost when predict standalone

- federatedml/nn/homo_nn/enter_point.py
> fix issue#670

- examples/federatedml-1.0-examples/quick_run.py
- federatedml/evaluation/evaluation.py
- federatedml/feature/hetero_feature_selection/base_feature_selection.py
- federatedml/linear_model/logistic_regression/base_logistic_regression.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- federatedml/one_vs_rest/one_vs_rest.py
- federatedml/optim/gradient/hetero_linear_model_gradient.py
- federatedml/param/evaluation_param.py
- federatedml/protobuf/generated/feature_selection_param_pb2.py
- federatedml/protobuf/generated/lr_model_param_pb2.py
- federatedml/protobuf/proto/feature-selection-param.proto
- federatedml/protobuf/proto/lr-model-param.proto
- federatedml/util/fate_operator.py
Fixes  ISSUE #666
Changes:
1. Fix homo-lr evaluation
> Feature 1.1 integration second round

- federatedml/nn/homo_nn/enter_point.py
> fix ISSUE#672

- arch/api/table/eggroll_util.py
adjust eggroll_util to use new api in eggroll
> adjust eggroll_util

- docker-build/README.md
- docker-build/README_zh.md
1. Added Chinese document "README_zh.md"
2. Refined the "Packaging images" section
> Added Chinese user guide

- arch/api/utils/log_utils.py
- fate_flow/apps/data_access_app.py
- fate_flow/apps/tracking_app.py
- fate_flow/driver/task_executor.py
- fate_flow/utils/authentication_utils.py
- fate_flow/utils/download.py
- fate_flow/utils/upload.py
fix bugs #689 :
1.The task status of each party after the authentication failure is different；
2.Scheduling error logs cannot be output separately；
3.No error log under component log；
4.Work_mode is always 0 when upload/download；
> fix fate flow bugs

- fate_flow/driver/dsl_parser.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
Changes:
1. Fix hetero_lr save model bug
> fix hetero_lr host get_param bugs

- examples/federatedml-1.0-examples/hetero_linear_regression/test_hetero_linr_cv_job_conf.json
- examples/federatedml-1.0-examples/hetero_linear_regression/test_hetero_linr_train_job_conf.json
- examples/federatedml-1.0-examples/homo_logistic_regression/test_homolr_train_job_conf.json
- federatedml/optim/gradient/hetero_linr_gradient_and_loss.py
- federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
- federatedml/param/cross_validation_param.py
- federatedml/param/evaluation_param.py
- federatedml/param/feature_binning_param.py
- federatedml/param/feature_selection_param.py
- federatedml/param/linear_regression_param.py
- federatedml/param/logistic_regression_param.py
- federatedml/param/onehot_encoder_param.py
- federatedml/param/poisson_regression_param.py
- federatedml/param/sample_param.py
- federatedml/param/scale_param.py
Fixes param check error from linear & Poisson Regression
> Feature 1.1 new third round

- arch/api/table/eggroll_util.py
> fix spark mode

- arch/api/table/pyspark/table_impl.py
> fix bug in spark

- federatedml/README.md
> fix readme

- cluster-deploy/scripts/packaging.sh
- fate_flow/driver/task_scheduler.py
> job skip clean up

- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_train_job_conf.json
Signed-off-by: Yu Wu <yolandawu131@gmail.com>
Changes:
1. add three-party linR train example
> edit linR examples

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-V1.1allinone部署指南(build).md
- cluster-deploy/doc/Fate-V1.1cluster部署指南(build).md
Fixes  ISSUE#xxx #725 
Changes:
1.update deploy guide
> update deploy guide

- cluster-deploy/scripts/allinone_cluster_configurations.sh
- cluster-deploy/scripts/deploy/eggroll/egg/configurations.sh
- cluster-deploy/scripts/deploy/eggroll/egg/deploy.sh
- cluster-deploy/scripts/deploy/fate_base/mysql/configurations.sh
- cluster-deploy/scripts/deploy/fate_base/mysql/deploy.sh
- cluster-deploy/scripts/deploy_cluster_allinone.sh
- cluster-deploy/scripts/deploy_cluster_multinode.sh
- cluster-deploy/scripts/packaging.sh
Fixes  ISSUE #740 
Changes:
1. Fix bugs that grant mysql permission to ip repeatedly
2. Modify processor start port num
3.
> Feature 1.1 deploy

- .sat.toml
- README.md
Changes:
1. add .sat.toml  and modify readme.md for pinpoint-satellite
> Feature codescanner

- arch/api/session.py
- arch/api/table/eggroll/session_impl.py
- arch/api/table/eggroll/table_impl.py
- arch/api/table/pyspark/session_impl.py
- arch/api/table/pyspark/table_impl.py
- arch/api/table/session.py
> support db switch

- arch/api/table/pyspark/session_impl.py
> fix bug, don't pickle dable!

- arch/api/table/eggroll_util.py
- arch/api/table/pyspark/rdd_func.py
> fix issue #769

- .gitmodules
- federatedml/tree/hetero_secureboosting_tree_guest.py
> fix bugs of secureboost' early_stop

- federatedml/statistic/union/README.md
- federatedml/statistic/union/union.py
Fixes  ISSUE:
Missing table schema in output data
Changes:
1. Edit Union README
> Feature 1.1.1 union

- cluster-deploy/scripts/default_configurations.sh
- cluster-deploy/scripts/deploy/eggroll/egg/configurations.sh
- cluster-deploy/scripts/deploy/eggroll/egg/deploy.sh
- cluster-deploy/scripts/deploy/eggroll/meta-service/configurations.sh
- cluster-deploy/scripts/deploy/eggroll/meta-service/deploy.sh
- cluster-deploy/scripts/deploy/eggroll/roll/configurations.sh
- cluster-deploy/scripts/deploy/eggroll/roll/deploy.sh
- cluster-deploy/scripts/deploy/fate_flow/configurations.sh
- cluster-deploy/scripts/deploy/fateboard/configurations.sh
- cluster-deploy/scripts/deploy/fateboard/deploy.sh
- cluster-deploy/scripts/deploy/federation/configurations.sh
- cluster-deploy/scripts/deploy/federation/deploy.sh
- cluster-deploy/scripts/deploy/proxy/configurations.sh
- cluster-deploy/scripts/deploy/proxy/deploy.sh
- cluster-deploy/scripts/deploy_cluster_allinone.sh
- cluster-deploy/scripts/deploy_cluster_multinode.sh
- cluster-deploy/scripts/packaging.sh
Changes:
1.Modify the version information to distinguish the version of the compressed package and the module jar package.
2.The version variable represents the version number of the compressed package.
3.The module version variable represents the jar package version number of the module.
> Feature 1.1 deploy ubuntu

- docker-build/.env
- docker-build/build_cluster_docker.sh
- docker-build/docker/modules/python/Dockerfile
1. Package exmaples dir to the python image
2. Replace the hard-code version of the package with the variable
> Package examples to the python image

- standalone-deploy/build_standalone_docker.sh
Changes:
1.Verify judgment information
2.Verify judgment information
3.Verify judgment information
> modify error information

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone部署指南(build).md
- cluster-deploy/doc/Fate-allinone部署指南(install).md
- cluster-deploy/doc/Fate-cluster部署指南(build).md
- cluster-deploy/doc/Fate-cluster部署指南(install).md
- cluster-deploy/doc/Fate-exchange部署指南.md
- cluster-deploy/doc/configuration.md
- cluster-deploy/doc/thirdparty_spark/Hadoop+Spark集群部署指南.md
Fixes  ISSUE#xxx #810 
Changes:
1.update deploy guide
> Feature 1.1.1 deploy doc

- README.md
- docker-build/README.md
Signed-off-by: Haining Henry Zhang <haininghenryzh@vmware.com>
Update document of building Docker images.
> update docker build document

- fate_flow/examples/inference_request.py
> delete phone num and device_id

- test_example/cluster-task.json
- test_example/run_test.py
- test_example/standalone-task.json
- test_example/submit.py
Changes:
1.add submit.py for auto_submit 
2.add example template of standalone and cluster tasks
3.add run_test.py for testing all examples existed
> add test_example folder

- federatedml/util/data_io.py
Fixes  ISSUE #836 
Changes:
1. fix dataio reading tag inputformat bugs
> fix dataio reading tag inputformat bugs

- cluster-deploy/scripts/deploy/eggroll/services.sh
Changes:
1.modify eggroll services.sh
2.
3.
> Deploy 1.2

- federatedml/secureprotol/README.md
Fixes  [ISSUE#847](https://github.com/FederatedAI/FATE/issues/847)
> fix code errors

- federatedml/linear_model/linear_regression/base_linear_regression.py
- federatedml/linear_model/logistic_regression/base_logistic_regression.py
- federatedml/linear_model/poisson_regression/base_poisson_regression.py
- federatedml/optim/gradient/hetero_linear_model_gradient.py
- federatedml/optim/gradient/hetero_linr_gradient_and_loss.py
- federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
- federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
- federatedml/util/data_io.py
- federatedml/util/fate_operator.py
Changes:
Code change to support sparse data input for hetero logistic regression/linear regression/poisson regression
> Code change to support sparse data input for hetero linear model

- research/federated_object_detection_benchmark/README.md
- research/federated_object_detection_benchmark/model/model_wrapper.py
Changes:
1. Add the link to the paper.
2. Add Citation content.
3. Change use to 2010 metric for calculating mAP.
> link to paper

- cluster-deploy/doc/configuration.md
> modify doc

- federatedml/feature/one_hot_encoder.py
Changes:
1. Fix a onehot bug, create empty result for need_run is false case.
> Fix onehot bug

- federatedml/secureprotol/spdz/beaver_triples/he.py
- federatedml/secureprotol/spdz/communicator/federation.py
> Feature 1.2 ss old

- cluster-deploy/scripts/deploy/services.sh
- fate_flow/service.sh
Changes:
1.modify fateflow service.sh
2.
3.
> modify services.sh

- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-cluster_deployment_guide_install_zh.md
- cluster-deploy/scripts/default_configurations.sh
- fate_flow/service.sh
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Changes:
1.modify doc
2.modify version
3.
> Deploy 1.2.0

- .gitmodules
Changes:
1. update fateboard's branch in .gitmodule
2.
3.
> update fate-version module's branch

- fate_flow/service.sh
Signed-off-by: root <paulbao@webank.com>
Changes:
1.modify service.sh
2.
3.
> modify service.sh

- docker-build/.env
- docker-build/README.md
- docker-build/README_zh.md
- docker-build/build_cluster_docker.sh
- docker-build/docker/base/Dockerfile
- docker-build/docker/modules/egg/Dockerfile
- docker-build/docker/modules/fateboard/Dockerfile
- docker-build/docker/modules/federation/Dockerfile
- docker-build/docker/modules/meta-service/Dockerfile
- docker-build/docker/modules/proxy/Dockerfile
- docker-build/docker/modules/python/Dockerfile
- docker-build/docker/modules/roll/Dockerfile
Support building images of FATE v1.2.0
Changes:
1. Update documents
2. Correct the usage of `version`
3. Remove hard-coded values
> Docker build update for FATE v1.2.0 (#901)

- standalone-deploy/build_standalone_docker.sh
Signed-off-by: root <paulbao@webank.com>
Changes:
1.modify version information
2.
3.
> modify version information

- fate_flow/doc/fate_flow_cli.md
> modify CLI

- .gitmodules
- examples/federatedml-1.x-examples/hetero_feature_binning/hetero_binning_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_binning/multi_hosts_binning_job_conf.json
- examples/federatedml-1.x-examples/hetero_feature_selection/hetero_feature_selection_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_selection/test_hetero_feature_selection_multi_host_job_conf.json
- examples/federatedml-1.x-examples/hetero_linear_regression/hetero_linr_testsuite.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_multi_host_job_conf.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_dsl.json
- examples/federatedml-1.x-examples/hetero_secureboost/hetero_secureboost_testsuite.json
- examples/federatedml-1.x-examples/homo_logistic_regression/homo_lr_testsuite.json
- examples/federatedml-1.x-examples/homo_logistic_regression/test_multi_host_job_conf.json
- examples/federatedml-1.x-examples/homo_nn/testsuite.json
- examples/federatedml-1.x-examples/intersect/intersect_testsuite.json
Fixes  ISSUE #922 
Changes:
1. correct testsuites
> 1.2 patch.0 example test

- federatedml/statistic/intersect/README.md
Signed-off-by: zazd <zhenght5@gmail.com>
Fixes  ISSUE #932 
Changes:
update intersection readme
> update intersection readme

- federatedml/secureprotol/README.md
> add reference

- arch/api/table/eggroll/table_impl.py
- arch/api/table/pyspark/table_impl.py
> adjust reduce

- federatedml/transfer_variable/base_transfer_variable.py
Changes:
1. enable n to 1 get, such as Arbiter get object from guest and host
> enable n to 1 get

- arch/api/table/eggroll/table_impl.py
- arch/api/table/pyspark/table_impl.py
- arch/api/table/table.py
> add mapPartitions2

- federatedml/nn/hetero_nn/hetero_nn_guest.py
- federatedml/nn/hetero_nn/hetero_nn_host.py
- federatedml/secureprotol/encrypt_mode.py
- federatedml/secureprotol/test/encrypt_mode_test.py
- federatedml/tree/feature_histogram.py
- federatedml/tree/hetero_decision_tree_guest.py
- federatedml/tree/hetero_decision_tree_host.py
- federatedml/tree/hetero_secureboosting_tree_guest.py
- federatedml/tree/splitter.py
> Merge secureboost api opt into develop-1.3

- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Changes:
1. update wrong link to example folder
> update wrong link to example folder

- arch/api/table/eggroll/table_impl.py
> fix reduce

- docker-build/build_cluster_docker.sh
Fixes  ISSUE# Fix to allow run build_cluster_docker.sh on MacOS
Changes:
1. minor changes to build_cluster_docker.sh
> fix to run this script on MacOS

- examples/toy_example/run_toy_example.py
- federatedml/tree/test/feature_histogram_test.py
Changes:
1. Merge master branch into develop 1.3
> Develop 1.3 merge master

- standalone-deploy/build_standalone_docker.sh
- standalone-deploy/docker/docker-compose-build.yml
Fixes  ISSUE # Currently running standalone need a root access. By changing the path, non-root can run the standalone  
Changes:
1. change path from /var/lib/fate/log to ./fate/log
2. change path from /var/lib/fate/data to ./fate/data
> change path so that do not need root access to create directories

- docker-build/build_cluster_docker.sh
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- federatedml/optim/gradient/hetero_linear_model_gradient.py
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Changes:
1. Fix glm model host param order's error
> Feature 1.3 fix glm error

- examples/federatedml-1.x-examples/hetero_logistic_regression/hetero_lr_testsuite.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_sparse_train_job_conf.json
- federatedml/linear_model/logistic_regression/README.md
- federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
Changes:
1. Add sparse example in hetero-lr
2. Fix a gradient error caused by adding log
> Add Sparse example

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-cluster_deployment_guide_install_zh.md
- cluster-deploy/scripts/default_configurations.sh
- standalone-deploy/README.md
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Fixes  ISSUE#xxx #978 
Changes:
1.1.Modify the deployment script version number
> 1.Modify the deployment script version number

- federatedml/feature/binning/quantile_binning.py
- federatedml/feature/binning/quantile_summaries.py
- federatedml/feature/one_hot_encoder.py
- federatedml/linear_model/logistic_regression/base_logistic_regression.py
- federatedml/optim/gradient/hetero_linear_model_gradient.py
- federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
- federatedml/param/encrypt_param.py
- federatedml/param/onehot_encoder_param.py
- federatedml/util/fate_operator.py
Fixes  ISSUE#992 #991
Changes:
1. Add abnormal detection for sparse gradient of hetero linear model
2. Re-write hetero linear sparse gradient part
3. Add onehot param detection
4. Fix 32M problem in quantile binning
> Add abnormal detection in sparse gradient of linear model, Fix 32M problem in quantile binning

- arch/api/utils/splitable.py
> lowdown split size to 15M

- federatedml/tree/feature_histogram.py
- federatedml/tree/hetero_decision_tree_guest.py
- federatedml/tree/hetero_decision_tree_host.py
- federatedml/tree/splitter.py
- federatedml/tree/test/feature_histogram_test.py
- federatedml/util/consts.py
Fixes  ISSUE #1009 
Changes:
1. feature histogram of host will be dtable instead of list
2. accelerate host split info preparing by feature dimension
> fix bugs of secureboost 32m by adjust feature histogram format of host

- examples/federatedml-1.x-examples/hetero_feature_binning/binning_transform_woe_job_conf.json
- examples/federatedml-1.x-examples/hetero_feature_binning/hetero_binning_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_binning/test_hetero_binning_add_onehot_job_dsl.json
Fixes  ISSUE #1014
Changes:
1. Change a hetero-binning example case. Woe case should not concate onehot component.
> Change hetero-feature-binning&onehot case

- examples/federatedrec-examples/hetero_fm/hetero_fm_testsuite.json
- examples/federatedrec-examples/hetero_fm/test_predict_conf.json
- examples/federatedrec-examples/hetero_svd/hetero_svd_testsuite.json
- examples/federatedrec-examples/hetero_svd/test_predict_conf.json
Signed-off-by: peiyong86 <peiyong86@gmail.com>
Fixes  ISSUE #1019 
Changes:
1. Add prediction module to FM/SVD's testsuit.
> add predict to testsuit of fm and svd

- examples/federatedrec-examples/homo_fm/homo_fm_testsuite.json
- examples/federatedrec-examples/homo_fm/upload_data_guest.json
- examples/federatedrec-examples/homo_fm/upload_data_host.json
Changes:
1. testsuite with predict
2. upload logic
> changed testsuite and upload

- examples/federatedrec-examples/hetero_gmf/hetero_gmf_testsuite.json
Changes:
1. fix error of gmf testsuite
> Develop 1.3 fedrec fix

- federatedml/feature/one_hot_encoder.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- federatedml/util/component_properties.py
Changes:
1. Onehot detect null input
2. homo-lr add final iteration
3. component properties add eval data
> Develop 1.3 Fix-errors

- examples/federatedrec-examples/homo_fm/README.md
Fixes  ISSUE #1029
Changes:
1. changed typo in Readme
> changed typo

- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras_multi_label.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras_temperate.json
Changes:
1. Add LinR sparse-data training configuration file.
2. Add sparse-data training task to LinR test suite
3. Add failed status in federatedml/test/run/test.sh for using ci-testing
4. Use Coverage to generate coverage report for code coverage statistics.
> Add LinR sparse example and modify federatedml' run_test script

- fate_flow/apps/schedule_app.py
- fate_flow/utils/grpc_utils.py
- fate_flow/utils/node_check_utils.py
Signed-off-by: wzh <15779896112@163.com>
Fixes  ISSUE #1039
> modify node check

- cluster-deploy/scripts/deploy/federatedml/deploy.sh
- standalone-deploy/build_standalone_docker.sh
Signed-off-by: cooper <g6xuyiming@163.com>
Fixes  ISSUE #1041
Changes:
1.Update standalone and cluster deploy scripts to support federatedrec component.
> update deploy scripts

- examples/federatedrec-examples/hetero_gmf/hetero_gmf_testsuite.json
Changes:
1. fix the wrong evaluation data in gmf testsuite
> change the evaluation data in testsuite of gmf

- federatedml/model_selection/k_fold.py
Fixes  ISSUE #1046 
Changes:
1. Kfold fail to set cv_iter nums for arbiter in GLM which cause loss callback error
> Fix GLM loss callback

- examples/federatedml-1.x-examples/multi_model_pipeline/test_multi_pipeline_conf.json
- federatedml/param/sample_param.py
Fixes  ISSUE #1050 
Changes:
1. Add stratified sample checker
2. Add stratified sample config example
> add stratified-sample param check and using examples

- fate_flow/README_zh.md
- federatedml/README_zh.md
Fixes  ISSUE #1053
Changes:
1. Add Chinese version README for federatedml and fate-flow
> Add Chinese version doc for fate_flow README and federatedml README

- docker-build/.env
- docker-build/README.md
- docker-build/README_zh.md
- docker-build/build_cluster_docker.sh
- docker-build/docker/modules/egg/Dockerfile
- docker-build/docker/modules/python/Dockerfile
Signed-off-by: Lu Peng <penglu@hydsoft.com>
Changes:
1. Build docker image shell
2. Fate_flow Dockerfile and Egg Dockerfile
3. Readme
> Build docker images for FATE 1.3

- federatedml/nn/homo_nn/enter_point.py
> fix loss callback

- .gitmodules
Changes:
1. update gitmodule of fateboard and eggroll
> update gitmodule of fate-v1.3.0

- fate_flow/README_zh.md
Signed-off-by: wzh <15779896112@163.com>
Fixes  ISSUE #1069
modify Chinese version REAME doc for fate-flow
> modify readme_zh.md

- requirements.txt
Changes:
1. upgrade bleach==1.5.0 to 3.1.1
2.
3.
> upgrade bleach version

- RELEASE.md
Changes:
1. update release doc of fate-v1.3
> update release doc of fate-1.3

- examples/federatedml-1.x-examples/hetero_logistic_regression/hetero_lr_testsuite.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_sqn_job_conf.json
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- federatedml/optim/gradient/hetero_linear_model_gradient.py
Changes:
1. Fix sqn missed error
> Fix sqn missed error

- federatedml/evaluation/evaluation.py
- federatedml/param/boosting_tree_param.py
- federatedml/transfer_variable/definition/validation_strategy.json
- federatedml/tree/boosting_tree.py
- federatedml/tree/hetero_secureboosting_tree_guest.py
- federatedml/tree/hetero_secureboosting_tree_host.py
- federatedml/util/validation_strategy.py
> Feature 1.4 early stop

- examples/federatedml-1.x-examples/hetero_nn/README.md
- examples/federatedml-1.x-examples/hetero_nn/hetero_nn_testsuite.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_dsl_with_early_stop.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras_with_early_stop.json
- federatedml/nn/hetero_nn/hetero_nn_base.py
- federatedml/nn/hetero_nn/hetero_nn_guest.py
- federatedml/nn/hetero_nn/hetero_nn_host.py
- federatedml/param/hetero_nn_param.py
Fixes  ISSUE #1097 
Changes:
1. Add Early Stop Strategy in HeteroNN
2. Add early stop examples
> add early stop in hetero nn

- examples/federatedml-1.x-examples/hetero_linear_regression/README.md
- examples/federatedml-1.x-examples/hetero_linear_regression/hetero_linr_testsuite.json
- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_validate_job_conf.json
- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_validate_job_dsl.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_validate_job_conf.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/README.md
- examples/federatedml-1.x-examples/hetero_poisson_regression/hetero_poisson_testsuite.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/test_hetero_poisson_validate_job_conf.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/test_hetero_poisson_validate_job_dsl.json
- federatedml/linear_model/base_linear_model_arbiter.py
- federatedml/linear_model/linear_model_base.py
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- federatedml/param/linear_regression_param.py
- federatedml/param/logistic_regression_param.py
- federatedml/param/poisson_regression_param.py
Add early stop support & examples to Hetero LR, LinR, and Poisson Module (issue #1106)
Changes:
1. modify validation strategy initialization & usage in fit process 
2. add "early_stopping_rounds" to linear model params 
3. add validate examples
> Develop 1.4 early stop lm

- federatedml/evaluation/evaluation.py
- federatedml/tree/hetero_secureboosting_tree_guest.py
- federatedml/tree/hetero_secureboosting_tree_host.py
- federatedml/util/validation_strategy.py
> fix early stop

- federatedrec/general_mf/README.md
Signed-off-by: tonyliu <liucongwust@gmail.com>
Changes:
1. fix readme of gmf
> fix readme of gmf model

- federatedml/statistic/union/union.py
Fixes known issues of Union module 
Changes:
1. Allow single data table input 
2. Allow empty data table input
> Fix Union Module

- federatedml/linear_model/poisson_regression/base_poisson_regression.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
Fix object attribute and function call in table operations. 
Changes:
1. modify attributes
2. modify function calls in lambda expressions
> Fix self nonserializable

- federatedml/util/component_properties.py
> rm log with args

- examples/federatedml-1.x-examples/hetero_stepwise/README.md
- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_linr_conf.json
- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_lr_conf.json
- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_lr_dsl.json
Edit stepwise examples
Changes:
1. add README doc 
2. edit dsl setting
> update stepwise examples

- federatedml/local_baseline/local_baseline.py
> fix single model output

- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_linr_conf.json
- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_lr_conf.json
- examples/federatedml-1.x-examples/hetero_stepwise/test_hetero_stepwise_poisson_conf.json
> edit examples

- examples/federatedml-1.x-examples/hetero_feature_binning/hetero_binning_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_binning/test_hetero_binning_big_bin_job_conf.json
- examples/federatedml-1.x-examples/hetero_feature_selection/hetero_feature_selection_testsuite.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/hetero_lr_testsuite.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_cv_job_dsl.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_train_job_dsl.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_hetero_lr_validate_job_dsl.json
- examples/federatedml-1.x-examples/hetero_logistic_regression/test_lr_with_feature_engineering_dsl.json
- examples/federatedml-1.x-examples/homo_logistic_regression/homo_lr_testsuite.json
- examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json
- examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_train_job_dsl.json
- federatedml/feature/binning/optimal_binning/optimal_binning.py
- federatedml/model_selection/k_fold.py
- federatedml/model_selection/start_cross_validation.py
Changes:
1. remove data ouput for evaluation components
2.
3.
> rm evaluation components in cv jobs

- federatedml/feature/binning/optimal_binning/bucket_info.py
- federatedml/feature/binning/optimal_binning/heap.py
- federatedml/feature/binning/optimal_binning/optimal_binning.py
- federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- federatedml/linear_model/linear_model_base.py
- federatedml/linear_model/logistic_regression/base_logistic_regression.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- federatedml/param/feature_binning_param.py
- federatedml/param/logistic_regression_param.py
- federatedml/protobuf/proto/lr-model-param.proto
Fixes  ISSUE #1157 
Changes:
1. Fix some errors in optimal binning
2. Remove some useless log
3. Fix homo-lr aggregation logic
> Feature 1.4 optimal binning fix

- arch/api/utils/splitable.py
> fix issue #1184

- arch/transfer_variables/auth_conf/federatedml/intersection_func.json
- examples/federatedml-1.x-examples/intersect/README.md
- examples/federatedml-1.x-examples/intersect/test_intersect_job_dsl.json
- examples/federatedml-1.x-examples/intersect/test_intersect_without_dataio_job_conf.json
- examples/federatedml-1.x-examples/intersect/test_intersect_without_dataio_job_dsl.json
- federatedml/evaluation/evaluation.py
- federatedml/feature/feature_scale/base_scale.py
- federatedml/feature/feature_scale/min_max_scale.py
- federatedml/feature/feature_scale/standard_scale.py
- federatedml/feature/feature_scale/test/min_max_scale_test.py
- federatedml/feature/feature_scale/test/standard_scale_test.py
- federatedml/param/intersect_param.py
- federatedml/param/scale_param.py
- federatedml/statistic/intersect/intersect_model.py
- federatedml/transfer_variable/transfer_class/intersection_func_transfer_variable.py
- federatedml/util/consts.py
Changes:
1.update scale param
2.add intersection info share
> Develop 1.4 intersection example

- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_keras_with_early_stop.json
- federatedml/nn/hetero_nn/backend/hetero_nn_model.py
- federatedml/nn/hetero_nn/hetero_nn_base.py
- federatedml/nn/hetero_nn/hetero_nn_guest.py
- federatedml/protobuf/generated/hetero_nn_model_param_pb2.py
- federatedml/protobuf/proto/hetero-nn-model-param.proto
Changes:
1. use metrics to describe training process evaluation
2. add use_first_metric_only to judge early stopping strategy
3. modify examples of hetero nn' early stop
> adjust early stop of hetero_nn

- federatedml/feature/feature_selection/iv_value_select_filter.py
Changes:
1. Remove useless log
2.
3.
> delete useless log

- federatedml/tree/homo/homo_secureboosting_client.py
- federatedml/util/validation_strategy.py
Changes:
1. add early stopping checking
> add homo checking

- arch/api/federation.py
- federatedml/statistic/correlation/hetero_pearson.py
- federatedml/transfer_variable/base_transfer_variable.py
> fix issue #1198

- federatedml/param/hetero_nn_param.py
Changes:
1. fix nn param loss
2.
3.
> fix hetero_nn loss

- examples/federatedml-1.x-examples/hetero_linear_regression/hetero_linr_testsuite.json
- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_validate_job_dsl.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/hetero_poisson_testsuite.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/test_hetero_poisson_validate_job_dsl.json
- federatedml/param/linear_regression_param.py
- federatedml/param/poisson_regression_param.py
Add validate data DataIO to linr/poisson validate examples
> edit validate example

- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- federatedml/local_baseline/local_baseline.py
- federatedml/nn/hetero_nn/hetero_nn_guest.py
- federatedml/nn/homo_nn/enter_point.py
- federatedml/one_vs_rest/one_vs_rest.py
- federatedml/tree/hetero/hetero_decision_tree_guest.py
- federatedml/tree/hetero/hetero_secureboosting_tree_guest.py
- federatedml/util/io_check.py
Changes:
1. add row number check for data predict
> Feature 1.4 io check

- federatedml/local_baseline/test/local_baseline_test.py
Changes:
1. Add local baseline unit test
> add local baseline test

- arch/api/table/pyspark/table_impl.py
> fix issue #1169

- CONTRIBUTING.md
Changes:
1. Add email address into Contributing
2.
3.
> Add email address in contributing

- federatedml/statistic/test/hetero_pearson_test.py
> add test for pearson

- federatedml/nn/backend/pytorch/__init__.py
- federatedml/nn/backend/pytorch/nn_model.py
> fix torch backend

- examples/federatedml-1.x-examples/intersect/test_intersect_without_dataio_job_conf.json
- federatedml/statistic/intersect/test/intersection_guest_test.py
- federatedml/statistic/intersect/test/intersection_host_test.py
Signed-off-by: zazd <zhenght5@gmail.com>
Changes:
1.add intersection testunit
> add intersection test

- federatedml/secureprotol/test/encrypt_mode_test.py
- federatedml/test/run_test.sh
> fix run test error

- federatedml/tree/homo/homo_secureboosting_arbiter.py
> fix duplicate tag

- arch/api/federation.py
- federatedml/statistic/correlation/hetero_pearson.py
- federatedml/transfer_variable/base_transfer_variable.py
> fix Issue 1198

- federatedml/feature/binning/optimal_binning/optimal_binning.py
- federatedml/feature/binning/quantile_binning.py
- federatedml/feature/hetero_feature_binning/base_feature_binning.py
> fix model_base

- federatedml/tree/homo/homo_decision_tree_arbiter.py
> fix max split nodes

- examples/federatedml-1.x-examples/hetero_feature_selection/hetero_feature_selection_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_selection/test_hetero_feature_eval_selection_job_conf.json
> Feature 1.4 fix binning

- examples/federatedml-1.x-examples/hetero_secureboost/hetero_secureboost_testsuite.json
- examples/federatedml-1.x-examples/hetero_secureboost/test_secureboost_train_with_early_stopping_conf.json
- federatedml/evaluation/evaluation.py
- federatedml/param/boosting_tree_param.py
> Fix get metric

- federatedml/evaluation/evaluation.py
> fix-get-metric

- .gitmodules
- examples/federatedml-1.x-examples/hetero_nn/README.md
- federatedml/nn/hetero_nn/README.md
- federatedml/nn/hetero_nn/hetero_nn_guest.py
- federatedml/param/hetero_nn_param.py
> Feature 1.4 fix nn readme

- federatedml/model_selection/stepwise/hetero_stepwise.py
- federatedml/model_selection/stepwise/test/stepwise_test.py
Fixes  ISSUE #1247
Changes:
1. add feature pseudonyms with party id to callback info
2. fix stepwise test case
> Fix stepwise feature party id info on Board

- examples/federatedml-1.x-examples/homo_secureboost/test_secureboost_cross_validation_dsl.json
- federatedml/model_selection/k_fold.py
- federatedml/param/boosting_tree_param.py
- federatedml/param/evaluation_param.py
- federatedml/tree/hetero/hetero_secureboosting_tree_guest.py
- federatedml/util/validation_strategy.py
> Feature 1.4 earlystop fix and update

- federatedml/param/hetero_nn_param.py
> add hetero nn param description

- examples/federatedml-1.x-examples/hetero_feature_binning/hetero_binning_testsuite.json
- examples/federatedml-1.x-examples/hetero_feature_binning/test_asymmetric_job_conf.json
- federatedml/feature/binning/base_binning.py
- federatedml/feature/binning/optimal_binning/optimal_binning.py
- federatedml/feature/binning/quantile_binning.py
- federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- federatedml/feature/hetero_feature_binning/hetero_binning_host.py
- federatedml/statistic/data_overview.py
Fixes  ISSUE #1236 
Changes:
1. 
2.
3.
> Feature 1.4 add asymmetric

- federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- federatedml/feature/hetero_feature_binning/hetero_binning_host.py
> add binning

- federatedml/feature/binning/test/base_binning_test.py
- federatedml/feature/binning/test/bucket_binning_test.py
- federatedml/feature/binning/test/quantile_binning_test.py
- federatedml/feature/test/quantile_test.py
- federatedml/optim/gradient/test/hetero_lr_gradient_test.py
> fix test partitions

- arch/api/impl/based_2x/federation.py
add remote status detection, kill task if any exception catch
> Feature 1.4 remote exception handle

- federatedml/feature/feature_scale/test/min_max_scale_test.py
- federatedml/statistic/intersect/test/intersection_guest_test.py
- federatedml/statistic/intersect/test/intersection_host_test.py
Signed-off-by: zazd <zhenght5@gmail.com>
Changes:
1. test unit
> undate test case

- federatedml/statistic/test/hetero_pearson_test.py
> fix pearson test

- examples/federatedml-1.x-examples/hetero_feature_selection/hetero_feature_selection_testsuite.json
- federatedml/feature/feature_selection/variance_coe_filter.py
- federatedml/model_selection/k_fold.py
- federatedml/util/abnormal_detection.py
> Fix cv logic

- federatedrec/general_mf/hetero_gmf/hetero_gmf_base.py
- federatedrec/general_mf/hetero_gmf/hetero_gmf_client.py
- federatedrec/matrix_factorization/hetero_matrixfactor/hetero_mf_base.py
- federatedrec/matrix_factorization/hetero_matrixfactor/hetero_mf_client.py
- federatedrec/optim/gradient/homo_fm_gradient.py
- federatedrec/svd/hetero_svd/hetero_svd_base.py
- federatedrec/svd/hetero_svd/hetero_svd_client.py
- federatedrec/svdpp/hetero_svdpp/hetero_svdpp_base.py
- federatedrec/svdpp/hetero_svdpp/hetero_svdpp_client.py
> edit federatedrec

- README.md
- arch/api/base/table.py
- federatedml/README.rst
- federatedml/secureprotol/README.rst
- federatedrec/README.md
- federatedrec/factorization_machine/README.md
> Feature 1.4 rst docs

- examples/min_test_task/run_task.py
> change time-out setting for min-test

- federatedml/local_baseline/test/__init__.py
- federatedml/model_selection/stepwise/__init__.py
- federatedml/model_selection/stepwise/test/__init__.py
- federatedml/param/linear_regression_param.py
- federatedml/param/logistic_regression_param.py
- federatedml/param/poisson_regression_param.py
Changes:
1. Add __init__.py to some package directories
2. Edit metrics param in glm param
> Feature 1.4 fix init

- federatedml/param/boosting_tree_param.py
- federatedml/param/hetero_nn_param.py
- federatedml/param/linear_regression_param.py
- federatedml/param/logistic_regression_param.py
- federatedml/param/poisson_regression_param.py
Signed-off-by: Chen <cwjghglbdcj@gmail.com>
Changes:
1.
2.
3.
> add early stopping related parameter check

- RELEASE.md
Changes:
1. update release of fate-1.4.0
2.
3.
> update release of feate-1.4.0

- federatedml/feature/test/quantile_test.py
> Feature 1.4 edit unittest

- fate_flow/fate_flow_server.py
- fate_flow/settings.py
- fate_flow/utils/job_utils.py
> fix match cmd line bug

- fate_flow/fate_flow_server.py
- fate_flow/utils/session_utils.py
> improve session util

- arch/api/impl/based_2x/build.py
- arch/api/impl/based_2x/session.py
- arch/api/impl/based_spark/based_2x/build.py
- arch/api/session.py
1. add options for session init
> add options for session init

- fate_flow/apps/schedule_app.py
- fate_flow/driver/task_executor.py
- fate_flow/driver/task_scheduler.py
- fate_flow/examples/test_hetero_lr_job_conf.json
- fate_flow/utils/session_utils.py
> support job processors_per_node parameters

- cluster-deploy/build.sh
> modify build output dirname

- arch/api/impl/based_2x/federation.py
> Issue 1.4 obj remote clean temorary workaround

- federatedml/transfer_variable/base_transfer_variable.py
Changes:
1. fix transfer_variable singleton
> Bugfix 1.4 fix transfer variable

- cluster-deploy/build.md
> add build guide

- cluster-deploy/build.md
> fix build guid

- .gitmodules
- cluster-deploy/build.sh
- standalone-deploy/README.md
> Feature 1.4.0 deploy

- arch/api/base/table.py
- cluster-deploy/build.md
- fate_flow/driver/task_executor.py
- fate_flow/examples/test_hetero_lr_job_conf.json
- fate_flow/examples/test_predict_conf.json
- fate_flow/manager/tracking_manager.py
- fate_flow/settings.py
- fate_flow/utils/job_utils.py
> Support save as task input data table

- fate_flow/driver/task_executor.py
- fate_flow/manager/tracking_manager.py
> add task_id namespace clean up

- examples/min_test_task/config/test_hetero_lr_train_job_dsl.json
- examples/min_test_task/config/test_intersect_job_dsl.json
- examples/min_test_task/config/test_predict_conf.json
- examples/min_test_task/config/upload.json
- examples/min_test_task/run_task.py
> edit min test

- .gitmodules
> upgrade eggroll to build9

- federatedml/nn/hetero_nn/hetero_nn_host.py
- federatedml/tree/hetero/hetero_secureboosting_tree_host.py
- federatedml/tree/homo/homo_secureboosting_client.py
- federatedml/util/validation_strategy.py
> Feature 1.4 best iter

- examples/federatedml-1.x-examples/experiment/__init__.py
- examples/federatedml-1.x-examples/experiment/config/__init__.py
- examples/federatedml-1.x-examples/experiment/config/download.json
- examples/federatedml-1.x-examples/experiment/config/test_hetero_lr_train_job_conf.json
- examples/federatedml-1.x-examples/experiment/config/test_hetero_lr_train_job_conf_with_localbaseline.json
- examples/federatedml-1.x-examples/experiment/config/test_hetero_lr_train_job_dsl.json
- examples/federatedml-1.x-examples/experiment/config/test_hetero_lr_train_job_dsl_with_localbaseline.json
- examples/federatedml-1.x-examples/experiment/config/test_predict_conf.json
- examples/federatedml-1.x-examples/experiment/config/upload.json
- examples/federatedml-1.x-examples/experiment/generate_mock_data.py
- examples/federatedml-1.x-examples/experiment/run.sh
- examples/federatedml-1.x-examples/experiment/run_task.py
- examples/min_test_task/config/upload.json
> add experiment test

- .gitmodules
- federatedml/secureprotol/affine.py
- federatedml/secureprotol/iterative_affine.py
Changes:
1. fix bug of very low propability(1e-10)  of dead loop in iterativeAffine
2.
3.
> update affine encryption's code to avoid dead loop in low probability

- arch/transfer_variables/auth_conf/federatedml/hetero_secure_boosting_tree_transfer_variable.json
- federatedml/transfer_variable/transfer_class/hetero_secure_boost_transfer_variable.py
- federatedml/tree/hetero/hetero_decision_tree_guest.py
- federatedml/tree/hetero/hetero_secureboosting_tree_guest.py
- federatedml/tree/hetero/hetero_secureboosting_tree_host.py
- federatedml/tree/tree_core/predict_cache.py
Fixes  ISSUE #1348 
Changes:
1. add predict data cache to speed up hetero_secureboost predicting process
2.
3.
> add predict cached to hetero sbt

- examples/federatedml-1.x-examples/README.rst
- examples/federatedml-1.x-examples/experiment/generate_mock_data.py
- examples/federatedml-1.x-examples/experiment/run_task.py
> Feature 1.4 add partition note

- .gitmodules
- .travis.yml
> update travis & gitmodule

- doc/readthedoc/requirements.txt
Changes:
1. remove duplicate requirements in doc/eadthedoc
> remove duplicate requirements

- .gitmodules
- RELEASE.md
> Feature 1.4 travis ci update

- fate_flow/README.md
- fate_flow/README_zh.md
- fate_flow/doc/fate_flow_rest_api.md
Signed-off-by: wzh <15779896112@163.com>
Changes:
1.
2.
3.
> update fate flow doc

- fate_flow/README.rst
- fate_flow/README_zh.rst
- fate_flow/doc/fate_flow_cli.rst
- fate_flow/doc/fate_flow_rest_api.rst
- index.rst
Changes:
1. add rst format doc for fate_Flow
> add rst docs for fate_flow

- examples/federatedml-1.x-examples/README.rst
> Develop 1.4 edit doc

- arch/api/impl/based_2x/federation.py
> add auth check

- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
Fixes  ISSUE #xxx #1339 
Changes:
1.allinone doc update
2.exchange doc update
> Feature 1.4.0 deploy doc

- federatedml/util/data_io.py
Fixes  ISSUE #1381 
Changes:
1. feature shape and header consistency
2. allow no label in predict task
3.
> Feature 1.4.1 dataio enhance

- federatedml/secure_information_retrieval/__init__.py
- federatedml/secure_information_retrieval/base_secure_information_retrieval.py
- federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
- federatedml/secure_information_retrieval/secure_information_retrieval_host.py
1. Add the Secure Information Retrieval module.
> secure-info-retrieval module added

- federatedml/evaluation/evaluation.py
> fix evaluation multi accuracy metric

- federatedml/evaluation/evaluation.py
> fix ks bug

- examples/federatedml-1.x-examples/local_baseline/test_local_baseline_homo_job_conf.json
- federatedml/local_baseline/local_baseline.py
Changes:
1. Fix local baseline binary predict
> fix local baseline binary predict

- federatedml/evaluation/evaluation.py
- federatedml/evaluation/metric_interface.py
- federatedml/evaluation/metrics/classification_metric.py
fix bugs:
1. psi callback, nan problem
2. pr, auc log bug
3. precision prettifying value reset
4. confusion mat/F1 score threshold adjust
> Feature 1.4.1 evaluation update

- federatedml/feature/feature_scale/min_max_scale.py
- federatedml/feature/feature_scale/standard_scale.py
- federatedml/statistic/intersect/intersect.py
- federatedml/statistic/intersect/intersect_model.py
Fixes  ISSUE  #1420
Changes:
1.fix intersection bug if host do not get sync results
2.fix scale bugs while scale after one-hot
> Develop 1.4.1 intersect fix bug

- federatedml/evaluation/metrics/classification_metric.py
> add sample count examination in ks

- federatedml/evaluation/evaluation.py
> fix roc curve

- cluster-deploy/build.sh
- fate_flow/README.md
- fate_flow/README.rst
- fate_flow/README_zh.md
- fate_flow/README_zh.rst
- fate_flow/apps/job_app.py
- fate_flow/db/db_models.py
- fate_flow/doc/fate_flow_rest_api.md
- fate_flow/doc/fate_flow_rest_api.rst
- fate_flow/driver/dag_scheduler.py
- fate_flow/driver/job_controller.py
- fate_flow/driver/task_scheduler.py
- fate_flow/fate_flow_client.py
- fate_flow/fate_flow_server.py
- fate_flow/manager/queue_manager.py
- fate_flow/manager/tracking_manager.py
- fate_flow/utils/api_utils.py
- fate_flow/utils/job_utils.py
- fate_flow/utils/upload.py
Fixes  ISSUE #1417
Changes:
1. fix fate flow  bugs
> Feature 1.4.1 fate flow

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
Fixes  ISSUE #xxx #1369 
Changes:
1.update deploy doc
> 1、1.4.0 deploy doc update

- federatedml/evaluation/metric_interface.py
> np to int type

- federatedml/model_base.py
- federatedml/util/component_properties.py
> Edit model-base to support multiple input data

- CONTRIBUTING.md
- README.md
- README_zh.md
- doc/develop_guide_zh.rst
Fixes  ISSUE 
There is a commit that format markdown to reStructuredText, but miss some URLs, so I'm trying to fix it.
BTW, wget -c  maybe better than wget
Changes:
1. fix markdown to reStructuredText
2. auto-format blank
> fix bad url

- federatedml/evaluation/metrics/classification_metric.py
> update np nan examination

- fate_flow/manager/tracking_manager.py
Signed-off-by: zengjice <jicezeng@gmail.com>
Changes:
1.
2.
3.
> fix save_job_info update fields

- federatedml/feature/feature_scale/min_max_scale.py
- federatedml/feature/feature_scale/standard_scale.py
Changes:
1. fix scale precision
2. std scale transform for not float input data
> Develop 1.4.1 scale precision

- federatedml/evaluation/evaluation.py
Changes:
1. Fix evaluation show result
2.
3.
> edit method for evaluation obtain data

- arch/api/impl/based_2x/federation.py
Changes:
1. remove remote callback log
> remove remote callback log

- federatedml/feature/feature_scale/test/min_max_scale_test.py
> Develop 1.4.1 scale unittest

- federatedml/evaluation/metric_interface.py
pr quantile precision val adjust
> pr quantile precision val adjust

- .travis.yml
- federatedml/test/run_test.sh
Changes:
1. edit travis
2. add flow api test to code coverage
> Feature 1.4.1 edit travis version

- .gitmodules
- RELEASE.md
- federatedml/nn/hetero_nn/README.rst
Changes:
1. update version of fateboard in gitmodule
2. fix hetero-nn readme format
3. update fate-1.4.1 content of  release note
> Feature 1.4.1 update doc

- CONTRIBUTING.md
- README.md
- README_zh.md
- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
- doc/develop_guide.rst
- doc/develop_guide_zh.rst
- examples/federatedml-1.x-examples/README.rst
> Merge master's doc update into develop

- examples/federatedml-1.x-examples/hetero_pearson/testsuite.json
- federatedml/param/pearson_param.py
- federatedml/secureprotol/spdz/spdz.py
- federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
- federatedml/secureprotol/spdz/utils/random_utils.py
- federatedml/statistic/correlation/hetero_pearson.py
Changes:
1. add non-federated support
2. add mix rand support
> enhance pearson

- CONTRIBUTING.md
- README.md
- README_zh.md
- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
- doc/develop_guide.rst
- doc/develop_guide_zh.rst
- examples/federatedml-1.x-examples/README.rst
> Merge master'update into feature-1.5-pipeline

- examples/test/run_test.py
> no deps task first

- federatedml/tree/hetero/hetero_decision_tree_guest.py
Changes:
1. fix node dispatch bug when leaf in max depth 
2.
3.
> fix node dispatch bug when leaf in max depth

- federatedml/test/run_test.sh
Changes:
1. remove flow_unittest from codecov
2.
3.
> remove flow_test from codecov

- federatedml/statistic/correlation/hetero_pearson.py
Changes:
1. export model only if `need_run` is True
> export model only if `need_run` is True

- cluster-deploy/README.md
- cluster-deploy/README.rst
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
> Edit min-test part in deploy doc

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
Fixes  ISSUE #xxx #1456 
Changes:
1.update package version
2.add checklist
3.
> Feature 1.4.1 deploy doc

- cluster-deploy/README.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
Fixes  ISSUE #xxx #1492 
Changes:
1.update package version
2.
3.
> 1、update package version

- docker-build/README_zh.md
Changes:
1. remove  ‘’。‘’  from the link
> edit kubefate link

- docker-build/.env
- docker-build/build_cluster_docker.sh
> Support 1.4.1 docker build

- arch/api/impl/based_spark/based_hdfs/federation.py
- arch/api/impl/based_spark/based_hdfs/rabbit_manager.py
- arch/api/impl/based_spark/util.py
- fate_flow/driver/job_controller.py
Changes:
fix  bugs on randomstring
> Feature fateonspark baseon1.4.0 dy

- arch/api/impl/based_spark/based_hdfs/table.py
- fate_flow/utils/job_utils.py
> fix bug in from_dtable in RDDTable and change default value in job_utils

- arch/api/impl/based_spark/based_hdfs/table.py
- arch/api/utils/string_utils.py
> fix bugs on rdd persist

- examples/federatedml-1.x-examples/homo_nn/pytorch_homo_dnn_multi_label.json
- examples/federatedml-1.x-examples/homo_nn/pytorch_homo_dnn_multi_layer.json
- examples/federatedml-1.x-examples/homo_nn/pytorch_homo_dnn_single_layer.json
- examples/federatedml-1.x-examples/homo_nn/test_homo_dnn_multi_label.json
> fix config

- fate_flow/driver/task_executor.py
Signed-off-by: zengjice <jicezeng@gmail.com>
Changes:
1.
2.
3.
> fix monkey patch using by task executor

- examples/scripts/config.json
> edit statistic test

- examples/federatedml-1.x-examples/hetero_pearson/test_util/README.md
- examples/federatedml-1.x-examples/hetero_pearson/test_util/make_fake_data_testsuite.py
- examples/federatedml-1.x-examples/hetero_pearson/test_util/test_dsl.json
- federatedml/secureprotol/spdz/beaver_triples/he.py
Changes:
1. balance version of beaver triplets generator
> a balance version of beaver triplets generator

- federatedml/feature/feature_selection/iv_top_k_filter.py
- federatedml/feature/feature_selection/iv_value_select_filter.py
> Feature 1.4.2 fix iv bugs

- federatedml/tree/homo/homo_secureboosting_client.py
> homo-sbt - get_metric_param

- federatedml/optim/gradient/test/gradient_method_test.py
> fix unit test

- federatedml/test/run_test.sh
Fixes  ISSUE 
Changes:
1.
2.
3.
> Feature 1.4.2 add flow api test

- fate_flow/apps/model_app.py
Signed-off-by: wzh <15779896112@163.com>
Fixes  ISSUE #1530
Changes:
1. Modify the return structure of the fate flow load interface
> modify load return

- examples/scripts/README.rst
> add work mode explanation

- .travis.yml
- RELEASE.md
Changes:
1. edit release note of 1.4.2 and travis version
> edit release note of fate-1.4.2

- federatedml/nn/backend/tf_keras/nn_model.py
> fix keras bug in homo nn backend

- federatedml/protobuf/generated/psi_model_param_pb2.py
- federatedml/protobuf/proto/psi-model-param.proto
- federatedml/statistic/psi/psi.py
> update psi adapter and protobuf

- examples/test/ohe_alignment/train_job_conf.json
- federatedml/transfer_variable/transfer_class/OHE_alignment_transfer_variable.py
Fixes  ISSUE #1150
Changes:
1. update example of ohe alignment to run on FATE 1.4 because changes in scale keyword 'scale_col_indexes'
> FATE 1.4 changes from scale_column_idx to scale_col_indexes

- federatedml/conf/default_runtime_conf/onehot_encoder_with_alignment_param.json
- federatedml/conf/setting_conf/OHEAlignment.json
- federatedml/feature/OHE_with_alignment/OHE_alignment_arbiter.py
- federatedml/feature/OHE_with_alignment/OHE_alignment_base.py
- federatedml/feature/OHE_with_alignment/__init__.py
- federatedml/feature/test/ohe_alignment_test.py
- federatedml/param/onehot_encoder_with_alignment_param.py
Fixes  ISSUE #1150
Changes:
1. ohe alignment
> ohe_alignment

- cluster-deploy/README.md
- cluster-deploy/README.rst
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.rst
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.rst
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.rst
Fixes  ISSUE #xxx #1540 
Changes:
1.update deployment guide for 1.4.2
2.
3.
> Feature 1.4.2 deploy doc

- examples/min_test_task/run_task.py
Changes:
1. Change --add_sbt paramter in min-test
2.
3.
> change --add_sbt parameters

- cluster-deploy/README.md
- cluster-deploy/README.rst
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.rst
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.rst
Fixes  ISSUE #xxx #1545 
Changes:
1.update 1.4.2 deploy doc
2.
3.
> 1、update version 1.4.2 doc

- docker-build/.env
- docker-build/build_cluster_docker.sh
> Docker build 1.4.2

- cluster-deploy/build.md
Signed-off-by: v_wbymxu <g6xuyiming@163.com>
Fixes  ISSUE #1552 
Changes:
1.update build.md document to 1.4.2
> update deploy document

- federatedml/README.rst
Changes:
1. replace toctree with list
> replace toc with list for secure protol

- examples/federatedml-1.x-examples/homo_nn/mnist_demo/README.md
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/build_conf.py
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/download_data.py
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/mnist_conf_temperate.json
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/mnist_dsl.json
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/upload_test.json
- examples/federatedml-1.x-examples/homo_nn/mnist_demo/upload_train.json
Fixes  ISSUE #1488 
Changes:
1. add mnist example
> Feature 1.4.2 mnist example

- docker-build/.env
- docker-build/build_cluster_docker.sh
* Support Docker Build for 1.4.2
Signed-off-by: root <root@node2.cluster.local>
> Docker build 1.4.2 (#1549)

- examples/federatedml-1.x-examples/intersect/intersect_testsuite.json
Changes:
1. del rsa_cache task in testsuite as it need redis deploy to run successfully
2.
3.
> Feature 1.4.2 intersect testsuite adjust

- .gitmodules
Changes:
1. update gitmodule of fateboard
2.
3.
> upgrade gitmodule of fateboard

- examples/federatedml-1.x-examples/secure_information_retrieval/test_secure_information_retrieval_conf.json
- federatedml/secure_information_retrieval/base_secure_information_retrieval.py
Fix the bug of auto cleaned transmitted dtables in the SecureInformationRetrieval module.
> fix the bug of auto cleaned transmitted dtables

- federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_arbiter.py
- federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_client.py
- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
- federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
- federatedml/ensemble/boosting/boosting_core/homo_boosting.py
- federatedml/util/homo_label_encoder.py
> update log code

- federatedml/model_selection/stepwise/hetero_stepwise.py
Fixes  ISSUE #1617
Changes:
1. use generate_anonymous in stepwise callback & summary
> use generate anonymous

- examples/federatedml-1.x-examples/hetero_linear_regression/test_hetero_linr_validate_job_dsl.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_dsl.json
- examples/federatedml-1.x-examples/hetero_nn/test_hetero_nn_dsl_with_early_stop.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/test_hetero_poisson_validate_job_dsl.json
- examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json
- examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_train_eval_job_dsl.json
- examples/federatedml-1.x-examples/homo_nn/test_homo_nn_train_then_predict.json
- examples/federatedml-1.x-examples/homo_secureboost/test_secureboost_cross_validation_dsl.json
- examples/federatedml-1.x-examples/homo_secureboost/test_secureboost_train_dsl.json
- examples/test/demo/predict_conf.json
- examples/test/demo/train_job_conf.json
Changes:
1. change valdiate_data to eval_data in examples 
2.
3.
> Feature 1.5 example eval

- cluster-deploy/doc/FATE_model_publish_with_serving_guide_en.md
- cluster-deploy/doc/FATE_model_publish_with_serving_guide_zh.md
Signed-off-by: zengjice <jicezeng@gmail.com>
Changes:
1. update model publish with serving document
2.
3.
> update model publish with serving document

- federatedml/model_base.py
adjust some code format
Changes:
1. convert field with type np.ndarray to float in predict output
2. code format
> convert field with type np.ndarray to float

- federatedml/nn/homo_nn/enter_point.py
Changes:
1. add header alignment for homo nn
> Feature 1.5 header alignment homo nn

- federatedml/model_base.py
- federatedml/util/data_io.py
Fixes  ISSUE #1586
Changes:
1. use cache to store header alignment for predict phase 
2. change method usage in dataIO
3.
> Feature 1.5 predict cache

- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
Fixes  ISSUE #1586
Changes:
1. Fix keyerror when abstracting header from schema
> fix schema none error

- federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- federatedml/model_selection/stepwise/hetero_stepwise.py
- federatedml/statistic/data_overview.py
- pipeline/demo/hetero_stepwise/pipeline-stepwise-lr.py
Changes:
1. fix header alignment extra indices error 
2. fix stepwise header abstraction
> Feature 1.5 header align fix

- examples/min_test_task/config/test_hetero_lr_train_job_conf.json
- examples/min_test_task/config/test_secureboost_train_binary_conf.json
- examples/scripts/min_test_config.json
- examples/scripts/upload_default_data.py
- pipeline/component/data_statistics.py
- pipeline/demo/data_statistics/pipeline-data_statistics.py
Changes:
1. edit min-test config files
2. Add min-test version upload script config file
3.Add data_statistics pipeline component
> Add data_statics component

- federatedml/tree/hetero/hetero_decision_tree_guest.py
Fixes  ISSUE #1660 
Changes:
1.
2.
3.
> remove sensitive info of guest sending to host

- cluster-deploy/README.md
- cluster-deploy/README.rst
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.rst
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.rst
- cluster-deploy/doc/Fate_cluster_install_zh_ansible.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.md
- cluster-deploy/doc/Fate_step_by_step_install_zh.rst
Fixes  ISSUE #1562 
Changes:
1.update doc for 1.4.3
> Feature 1.4.3 deploy doc

- docker-build/.env
> feat: Docker build support v1.4.3

- RELEASE.md
Changes:
1. edit release note of fate-1.4.3
2.
3.
> edit release note of fate-v1.4.3

- federatedml/local_baseline/local_baseline.py
Changes:
1. Fix json non-serializable issue cased by numpy.bool_ and numpy.int
> fix json non-serializable in local baseline summary

- federatedml/feature/homo_onehot/homo_ohe_base.py
- federatedml/feature/one_hot_encoder.py
Changes:
1. abnormal detect between str and int type input in onehot
2.
3.
> abnormal detect between str and int type input in onehot

- federatedml/model_selection/data_split/data_split.py
Fixes  ISSUE #1579 
Changes:
1. Fix label ratio calculation error for original data set
> fix label info

- federatedml/statistic/intersect/intersect.py
Signed-off-by: zazd <zhenght5@gmail.com>
Changes:
1. remove raw intersection save_as
> remove raw intersection save_as

- examples/federatedml-1.x-examples/hetero_ftl/hetero_ftl_testsuite.json
- examples/federatedml-1.x-examples/hetero_ftl/test_ftl_predict.json
> update ftl predict

- examples/federatedml-1.x-examples/quick_run.py
Changes:
1. Fix quick_run upload data error
> fix quick_run.py

- fate_flow/scheduler/dsl_parser.py
- fate_flow/utils/parameter_util.py
> edit dsl parser to support parse input of reader

- examples/federatedml-1.x-examples/hetero_secureboost/test_secureboost_train_complete_secure_conf.json
- federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
- federatedml/transfer_variable/auth_conf/ftl_transfer_variable.json
- federatedml/transfer_variable/auth_conf/hetero_boosting.json
- federatedml/transfer_variable/auth_conf/hetero_decision_tree_transfer_variable.json
- federatedml/transfer_variable/auth_conf/hetero_secure_boosting_predict.json
- federatedml/transfer_variable/auth_conf/homo_boosting.json
- federatedml/transfer_variable/auth_conf/homo_label_encoder.json
- federatedml/transfer_variable/transfer_class/ftl_transfer_variable.py
> Feature 1.5 tranvar and path fix

- fate_arch/federation/transfer_variable/_transfer_variable.py
- fate_arch/session/_parties.py
Changes:
1. fix special KeyError case in  in federation
> fix special KeyError case in  in federation

- examples/testsuite/.gitignore
- examples/testsuite/DEV_README.rst
- examples/testsuite/README.rst
- examples/testsuite/fate_testsuite/__init__.py
- examples/testsuite/fate_testsuite/_ascii.py
- examples/testsuite/fate_testsuite/_client.py
- examples/testsuite/fate_testsuite/_config.py
- examples/testsuite/fate_testsuite/_flow_client.py
- examples/testsuite/fate_testsuite/_io.py
- examples/testsuite/fate_testsuite/_parser.py
- examples/testsuite/fate_testsuite/cli.py
- examples/testsuite/pyproject.toml
Changes:
1. implement a new testsuite
> implement fate testsuite

- federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_guest.py
- federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
> board display adaption 

- federatedml/linear_model/logistic_regression/base_logistic_regression.py
> Feature 1.5.0 system engineering pipeline adjust

- federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- federatedml/ensemble/boosting/homo/homo_secureboost_client.py
- federatedml/evaluation/evaluation.py
- federatedml/statistic/psi/psi.py
- federatedml/transfer_learning/hetero_ftl/ftl_guest.py
- federatedml/transfer_learning/hetero_ftl/ftl_host.py
> Feature 1.5 summary fix

- federatedml/ensemble/boosting/homo/homo_secureboost_client.py
fix model loading error while running homo-tree predcition
> fix homo predict

- fate_client/pipeline/demo/data_statistics/pipeline-data_statistics.py
- fate_client/pipeline/demo/hetero_fast_sbt/pipeline-hetero-sbt-layered.py
- fate_client/pipeline/demo/hetero_fast_sbt/pipeline-hetero-sbt-mix.py
- fate_client/pipeline/demo/hetero_feature_binning/pipeline-hetero-binning-optimal.py
- fate_client/pipeline/demo/hetero_feature_binning/pipeline-hetero-binning-quantile.py
- fate_client/pipeline/demo/hetero_feature_selection/pipeline-hetero-feature-selection.py
- fate_client/pipeline/demo/hetero_ftl/pipeline-hetero-ftl-demo.py
- fate_client/pipeline/demo/hetero_lr/pipeline-lr-cv.py
- fate_client/pipeline/demo/hetero_lr/pipeline-lr-multi-host.py
- fate_client/pipeline/demo/hetero_lr/pipeline-lr-ovr.py
- fate_client/pipeline/demo/hetero_lr/pipeline-lr-validate.py
- fate_client/pipeline/demo/hetero_nn/pipeline-hetero-nn-demo.py
- fate_client/pipeline/demo/hetero_sbt/pipeline-hetero-sbt.py
- fate_client/pipeline/demo/homo_feature_selection/pipeline-homo-feature-selection.py
- fate_client/pipeline/demo/homo_lr/pipeline-homo-lr-cv.py
- fate_client/pipeline/demo/homo_lr/pipeline-homo-lr.py
- fate_client/pipeline/demo/homo_nn/pipeline-homo-nn.py
- fate_client/pipeline/demo/homo_sbt/pipeline-homo-sbt.py
- fate_client/pipeline/demo/intersect/pipeline-intersection-with-dataio.py
- fate_client/pipeline/demo/psi/pipeline-psi.py
Changes:
1. update pipeline demo to use util Config for loading config.yaml
2.
3.
> Feature 1.5.0 system engineering

- examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_train_job_fedprox_conf.json
- federatedml/optim/optimizer.py
> fix fedprox

- federatedml/ensemble/README.rst
- federatedml/statistic/psi/README.rst
- federatedml/transfer_learning/hetero_ftl/ftl_base.py
> Feature 1.5 remove debug code

- federatedml/ensemble/boosting/boosting_core/boosting.py
- federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
> es name fix

- examples/federatedml-1.x-examples/psi/psi_cpn_conf.json
- examples/federatedml-1.x-examples/psi/psi_testsuite.json
> psi dataset fix

- federatedml/ensemble/boosting/boosting_core/boosting.py
> remove redundant

- federatedml/README.rst
- federatedml/README_zh.rst
Changes:
1. remove redundant  toctree
> fix toctree

- examples/min_test_task/README.rst
- examples/min_test_task/run_task.py
- fate_flow/apps/table_app.py
- fate_flow/apps/tracking_app.py
Changes:
1. Add serving process in min-test
2. fate flow add get component INFO log api
> Feature 1.4.5 fate flow

- federatedml/ensemble/boosting/boosting_core/boosting.py
- federatedml/ensemble/boosting/boosting_core/homo_boosting.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- federatedml/param/boosting_param.py
- federatedml/param/psi_param.py
- federatedml/statistic/psi/psi.py
- federatedml/transfer_learning/hetero_ftl/ftl_base.py
> Feature 1.5 param fix

- federatedml/ensemble/boosting/boosting_core/boosting.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- federatedml/param/boosting_param.py
- federatedml/transfer_learning/hetero_ftl/ftl_base.py
> Feature 1.5 ftl fix

- federatedml/util/_log.py
Changes:
1. add federatedml logger
> add LOGGER

- federatedml/README.rst
- federatedml/README_zh.rst
Changes:
1. adjust federatedml doc
> update federatedml doc

- federatedml/model_selection/data_split/README.rst
- federatedml/model_selection/data_split/data_split.py
- federatedml/model_selection/data_split/hetero_data_split.py
- federatedml/model_selection/data_split/homo_data_split.py
Changes:
1. Fix error when test size/validate size is set to zero
2. Fix README doc 
3.
> fix pipeline split zero error

- federatedml/statistic/data_overview.py
Changes:
1. Renew schema for data after instance alignment
> fix header align schema

- federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
> fix check label bug

- federatedml/model_base.py
- federatedml/util/component_properties.py
- federatedml/util/io_check.py
- federatedml/util/schema_check.py
Changes:
1. Use util checker is_table for testing RDDTable
> use is table

- examples/federatedml-1.x-examples/hetero_feature_selection/test_hetero_feature_eval_selection_job_conf.json
- examples/federatedml-1.x-examples/hetero_feature_selection/test_hetero_feature_selection_multi_iso_model_conf.json
- federatedml/linear_model/base_linear_model_arbiter.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py
- federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- federatedml/model_selection/indices.py
- federatedml/model_selection/k_fold.py
- federatedml/one_vs_rest/one_vs_rest.py
Changes:
1. fix summary errors
2. fix config
3.
> fix summary and selection config

- federatedml/feature/feature_scale/base_scale.py
- federatedml/feature/feature_scale/min_max_scale.py
- federatedml/feature/feature_scale/standard_scale.py
- federatedml/feature/scale.py
> add scale summary

- federatedml/param/boosting_param.py
> Feature 1.5 objective default

- federatedml/transfer_learning/hetero_ftl/ftl_base.py
> Feature 1.5 overlap check

- federatedml/statistic/intersect/intersect_host.py
- federatedml/statistic/intersect/intersect_model.py
- federatedml/statistic/intersect/repeat_id_process.py
Changes:
1. remove use of session.table as data type
2.
3.
> remove session.table typing

- examples/pipeline/data_split/pipeline-hetero-data-split-multi-model.py
- examples/pipeline/data_split/pipeline-hetero-data-split.py
Changes:
1. fix param loading from config
2.
3.
> fix read from config

- fate_client/pipeline/backend/pipeline.py
- fate_client/pipeline/utils/invoker/job_submitter.py
Changes:
1. Fix pipeline multi data output extraction 
2. Clean up code
3.
> Feature 1.5 pipeline second round

- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-layered.py
- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-mix.py
- examples/pipeline/hetero_ftl/pipeline-hetero-ftl.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt.py
- fate_client/pipeline/param/boosting_param.py
Signed-off-by: weijing <talkingwallace@sohu.com>
> pipeline demo fix

- federatedml/param/ftl_param.py
> alpha check

- .travis.yml
- cluster-deploy/build.md
- standalone-deploy/README.md
- standalone-deploy/README.rst
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Signed-off-by: v_wbymxu <g6xuyiming@163.com>
Fixes  ISSUE #1802 
Changes:
1.update the standalone document to 1.4.4
> update standalone deploy document

- arch/api/impl/based_2x/federation.py
Changes:
1. shutdown log before kill process when federation error rasied
> shutdown log before kill pid

- federatedml/util/column_expand.py
Fixes  ISSUE #1812 
Changes:
1. Record new header after predict (in case of different input data header)
2.
3.
> record new header

- federatedml/util/column_expand.py
Fixes  ISSUE #1812 
Changes:
1. fix future column_expand
2.
3.
> Feature 1.4.6 column expand

- federatedml/util/abnormal_detection.py
Fixes  ISSUE #1580 
Changes:
1. Add repeated value check for values in label_name/sid/header 
2.
3.
> add repeated value check for schema

- federatedml/util/abnormal_detection.py
Fixes  ISSUE #1580 
Changes:
1.
2.
3.
> fix set check error

- federatedml/transfer_learning/hetero_ftl/ftl_guest.py
> add host check

- federatedml/protobuf/model_migrate/converter/binning_model_converter.py
- federatedml/protobuf/model_migrate/converter/converter_base.py
- federatedml/protobuf/model_migrate/converter_factory.py
- federatedml/protobuf/test/test_binning_converter.py
> Add binning converter

- federatedml/protobuf/model_migrate/converter/pearson_model_converter.py
- federatedml/protobuf/model_migrate/converter_factory.py
1. impl model transfer for pearson
> impl pearson model converter

- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
> Fix homo_lr bug

- federatedml/statistic/data_overview.py
Changes:
1. fix shuffle header
2.
3.
> use correct header after shuffle

- fate_flow/scheduler/dsl_parser.py
Changes:
1. fix predict stage using default runtime conf error when component configured in role_parameters
2.
3.
> fix default conf showing in predict stage

- federatedml/model_selection/k_fold.py
> Fix cv bug

- federatedml/util/abnormal_detection.py
Fixes  ISSUE #1580 
Changes:
1.  Allow multiple None values in schema 
2. Allow header to be None
3.
> fix None error in legal schema check

- federatedml/secureprotol/iterative_affine.py
- federatedml/secureprotol/test/iterative_affine_test.py
1. Now iterative-affine module supports randomized and deterministic options.
> now iterative-affine module supports randomized and deterministic options

- federatedml/conf/setting_conf/ColumnExpand.json
- federatedml/feature/column_expand.py
Fixes  ISSUE #1812 
Changes:
1. Move column module to feature directory 
2.
3.
> move column expand to feature

- fate_client/pipeline/backend/config.py
- fate_client/pipeline/pipeline_cli.py
- fate_client/pipeline/utils/invoker/job_submitter.py
Changes:
1. add version info to pipeline backend
2.
3.
> Feature 1.5 pipeline sdk

- examples/federatedml-1.x-examples/hetero_feature_selection/test_hetero_feature_selection_job_dsl.json
- federatedml/protobuf/model_migrate/converter/binning_model_converter.py
- federatedml/protobuf/model_migrate/converter/feature_selection_model_converter.py
- federatedml/protobuf/model_migrate/converter_factory.py
> Add selection converter

- fate_client/pipeline/backend/pipeline.py
> fix pipeline dump and load model problem

- .gitmodules
- fate_arch/computing/eggroll/_csession.py
- fate_flow/controller/job_controller.py
- fate_flow/db/db_models.py
- fate_flow/entity/types.py
- fate_flow/examples/test_hetero_lr_job_conf.json
- fate_flow/examples/test_multi_pipeline_conf.json
- fate_flow/manager/resource_manager.py
- fate_flow/operation/job_saver.py
- fate_flow/scheduler/dag_scheduler.py
> Feature 1.5.0 fate flow schedule

- fate_arch/abc/_computing.py
- fate_arch/computing/eggroll/_table.py
- fate_arch/computing/spark/_table.py
- fate_arch/computing/standalone/_table.py
- fate_arch/standalone/_standalone.py
- federatedml/secureprotol/spdz/utils/random_utils.py
add preserves partitions parameter to mapPartitions
> rename mapPartitions2 to mapPartitions in pearson

- fate_client/pipeline/component/component_base.py
> delete all support in role

- federatedml/param/ftl_param.py
- federatedml/transfer_learning/hetero_ftl/ftl_guest.py
> Feature 1.5 fix ftl

- federatedml/util/abnormal_detection.py
Fixes  ISSUE #1580 
Changes:
1. Allow label name in header
2. add some debug log
3.
> allow label name in header

- federatedml/ensemble/boosting/boosting_core/homo_boosting.py
- federatedml/ensemble/boosting/homo/homo_secureboost_client.py
- federatedml/util/homo_label_encoder.py
> add homo label alignment force check

- federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py
> Fix homo_lr arbiter weights bug

- federatedml/feature/column_expand.py
- federatedml/param/column_expand_param.py
Fixes  ISSUE #1812 
Changes:
1. Allow single-column input
2. Fix typo in error message
> allow single column input

- federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_arbiter.py
- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
adapt to new eggroll interface
> Feature 1.5 map partition2 modify

- examples/federatedml-1.x-examples/column_expand/column_expand_testsuite.json
- examples/federatedml-1.x-examples/data_split/data_split_testsuite.json
- examples/federatedml-1.x-examples/hetero_poisson_regression/hetero_poisson_testsuite.json
- federatedml/feature/column_expand.py
Changes:
1. Reorder data to be uploaded in test suite 
2.
3.
> reorder data to upload in testsuite

- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
> fix feature_histogram.py para

- federatedml/ensemble/boosting/homo/homo_secureboost_client.py
> fix homo-sbt

- examples/federatedml-1.x-examples/kmeans/hetero_kmeans_testsuite.json
- examples/federatedml-1.x-examples/kmeans/test_hetero_kmeans_job_conf.json
- examples/federatedml-1.x-examples/kmeans/test_hetero_kmeans_job_dsl.json
- examples/federatedml-1.x-examples/kmeans/test_hetero_kmeans_job_multi_host_conf.json
- examples/federatedml-1.x-examples/kmeans/test_hetero_kmeans_validate_job_conf.json
- examples/federatedml-1.x-examples/kmeans/test_hetero_kmeans_validate_job_dsl.json
- examples/federatedml-1.x-examples/kmeans/test_kmeans_with_feature_engineering_dsl.json
- examples/federatedml-1.x-examples/kmeans/test_kmeans_with_feature_engineering_job_conf.json
- examples/federatedml-1.x-examples/kmeans/test_predict_conf.json
- federatedml/evaluation/metrics/clustering_metric.py
- federatedml/protobuf/generated/hetero_kmeans_param_pb2.py
- federatedml/protobuf/proto/hetero-kmeans-param.proto
- federatedml/unsupervise/kmeans/kmeans_model_base.py
Fixes  ISSUE #1868 
Changes:
1.fix clustering bugs
2.add header_param
> Feature 1.5 add kmeans

- examples/federatedml-1.x-examples/kmeans/test_kmeans_with_feature_engineering_dsl.json
- federatedml/conf/setting_conf/Evaluation.json
- federatedml/evaluation/metric_interface.py
- federatedml/param/evaluation_param.py
- federatedml/unsupervise/kmeans/hetero_kmeans/hetero_kmeans_arbiter.py
- federatedml/unsupervise/kmeans/hetero_kmeans/hetero_kmeans_client.py
> fix kmeans

- federatedml/ensemble/boosting/boosting_core/boosting.py
- federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- federatedml/ensemble/boosting/homo/homo_secureboost_client.py
> Feature 1.5 ensemble predict fix

- federatedml/conf/setting_conf/Evaluation.json
- federatedml/evaluation/evaluation.py
- federatedml/evaluation/metric_interface.py
> add lost files

- fate_client/pipeline/param/consts.py
- fate_client/pipeline/param/evaluation_param.py
> Feature 1.5 evaluation files

- examples/pipeline/hetero_kmeans/__init__.py
- examples/pipeline/hetero_kmeans/pipeline-kmeans.py
- fate_client/pipeline/component/hetero_kmeans.py
- fate_client/pipeline/param/hetero_kmeans_param.py
- federatedml/param/hetero_kmeans_param.py
> Add  kmeans pipeline

- federatedml/framework/homo/blocks/aggregator.py
- federatedml/framework/homo/blocks/diffie_hellman.py
- federatedml/framework/homo/blocks/has_converged.py
- federatedml/framework/homo/blocks/loss_scatter.py
- federatedml/framework/homo/blocks/model_broadcaster.py
- federatedml/framework/homo/blocks/model_scatter.py
- federatedml/framework/homo/blocks/paillier_cipher.py
- federatedml/framework/homo/blocks/random_padding_cipher.py
- federatedml/framework/homo/blocks/secure_aggregator.py
- federatedml/framework/homo/blocks/secure_mean_aggregator.py
- federatedml/framework/homo/blocks/secure_sum_aggregator.py
- federatedml/framework/homo/blocks/uuid_generator.py
- federatedml/framework/homo/procedure/aggregator.py
- federatedml/framework/homo/procedure/paillier_cipher.py
- federatedml/framework/homo/procedure/table_aggregator.py
remove default transfer variable
> remove default transfer variable

- fate_client/pipeline/backend/pipeline.py
Changes:
1. add train & predict dsl & conf pipeline getter 
2.
3.
> add conf & dsl getter

- federatedml/statistic/data_overview.py
Changes:
1. removed in-place compute in header align
2.
3.
> remove inplace compute in align header

- fate_flow/scheduler/dsl_parser.py
- fate_flow/utils/dsl_exception.py
Changes:
1. add exception when non-exist component want to get component info
2.
3.
> Feature 1.5 dsl parser 4 round

- federatedml/evaluation/evaluation.py
> Feature 1.5 fix kmeans

- federatedml/param/statistics_param.py
Changes:
1. edit statics logic
2.
3.
> Feature 1.5 fix error round 3

- federatedml/local_baseline/local_baseline.py
Changes:
1. remove session import & use in local baseline 
2.
3.
> remove session use in local baseline

- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- federatedml/evaluation/evaluation.py
> Feature 1.5 eval fix

- federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
> Feature 1.5 float error fix

- python/fate_arch/common/profile.py
- python/fate_arch/computing/standalone/_table.py
- python/fate_arch/federation/transfer_variable/_transfer_variable.py
- python/requirements.txt
> make profile pretty

- python/fate_client/pipeline/backend/config.py
Changes:
1. raise error when config and / or port setting missing from pipeline config
2.
3.
> raise error at missing ip & port

- python/fate_arch/common/profile.py
> lower table width

- python/federatedml/util/data_io.py
> fix dataio in memory table modify

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
> remove inplace agg op

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/protobuf/model_migrate/converter/converter_base.py
> update naming rule

- python/federatedml/feature/feature_scale/base_scale.py
- python/federatedml/feature/feature_scale/min_max_scale.py
- python/federatedml/feature/feature_scale/standard_scale.py
- python/federatedml/feature/imputer.py
Changes:
1.fix scale imputer odd
> Feature 1.5 new scale imputer rdd

- python/fate_flow/scheduler/detector.py
> improve detector

- examples/dsl/v1/secure_information_retrieval/secure_information_retrieval_testsuite.json
> reorder data order in testsuite

- python/federatedml/feature/feature_scale/test/min_max_scale_test.py
- python/federatedml/feature/feature_scale/test/standard_scale_test.py
- python/federatedml/feature/test/imputer_test.py
- python/federatedml/feature/test/sampler_test.py
- python/federatedml/nn/hetero_nn/test/paillier_tensor_test.py
- python/federatedml/nn/hetero_nn/test/random_number_generator_test.py
- python/federatedml/statistic/intersect/test/intersection_guest_test.py
- python/federatedml/statistic/intersect/test/intersection_host_test.py
- python/federatedml/util/test/classify_label_checker_test.py
- python/federatedml/util/test/data_io_test.py
- python/federatedml/util/test/param_extract_test.py
Changes:
1. fix unit test of feature scale\dataio\intersect\imputer\paillier_tensor\random_number_generater...
2.
3.
> Feature 1.5 fix unittest error

- python/federatedml/secureprotol/iterative_affine.py
> fix dead loop of iterative affine

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
> fast sbt - fast hist fix

- python/federatedml/feature/feature_selection/filter_base.py
- python/federatedml/feature/feature_selection/iso_model_filter.py
Changes:
1. fix selection error
2.
3.
> fix selection error

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/fast_feature_histogram.py
- python/federatedml/ensemble/test/feature_histogram_test.py
- python/federatedml/evaluation/metrics/clustering_metric.py
> Feature 1.5 unnitest update

- .gitmodules
- RELEASE.md
- cluster-deploy/build.sh
> Release 1.4.5

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
> temp update for fast sbt

- python/federatedml/model_selection/data_split/data_split.py
Changes:
1. fix ratio compute when validate size is None
2. fix order issue with collect
3. fix incorrect data count due to float
> fix ratio compute & order

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/fast_feature_histogram.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
> Feature 1.5 sbt reduce interface revert

- examples/dsl/v2/column_expand/test_column_expand_predict_job_dsl.json
> fix predict dsl

- examples/dsl/v1/homo_onehot/homo_onehot_testsuite.json
- examples/dsl/v2/hetero_logistic_regression/hetero-lr-normal-predict-conf.json
- examples/dsl/v2/hetero_logistic_regression/hetero-lr-normal-predict-dsl.json
- examples/dsl/v2/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/dsl/v2/homo_onehot/homo_onehot_testsuite.json
> add onehot testsuite and hetero-lr test case

- .readthedocs.yml
- python/fate_arch/abc/_computing.py
- python/fate_arch/computing/eggroll/_table.py
- python/fate_arch/computing/spark/_table.py
- python/fate_arch/computing/standalone/_table.py
- python/federatedml/optim/gradient/sqn_sync.py
- python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
- python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
- python/federatedml/secure_information_retrieval/secure_information_retrieval_host.py
> Feature 1.5 exactly sample

- examples/dsl/v2/psi/psi_cpn_conf.json
- examples/dsl/v2/psi/psi_cpn_dsl.json
- examples/dsl/v2/psi/psi_testsuite.json
- examples/pipeline/psi/pipeline-psi.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
> Feature 1.5 tree sparse float error fix

- python/federatedml/evaluation/metrics/clustering_metric.py
- python/federatedml/unsupervised_learning/kmeans/hetero_kmeans/hetero_kmeans_arbiter.py
- python/federatedml/unsupervised_learning/kmeans/hetero_kmeans/hetero_kmeans_client.py
> Feature 1.5 kmeans fix bugs

- .readthedocs.yml
- python/fate_test/README.rst
> fix readthedoc

- examples/benchmark_quality/hetero_linear_regression/hetero_linr_sklearn_benchmark.json
- examples/benchmark_quality/hetero_linear_regression/linr_config.yaml
- examples/dsl/v2/column_expand/README.md
- examples/dsl/v2/data_split/README.md
- examples/dsl/v2/hetero_linear_regression/README.md
- examples/dsl/v2/hetero_poisson_regression/README.md
- examples/dsl/v2/hetero_stepwise/README.md
- examples/dsl/v2/local_baseline/README.md
- examples/dsl/v2/upload/README.md
- examples/pipeline/column_expand/README.md
- examples/pipeline/data_split/README.md
- examples/pipeline/hetero_linear_regression/README.md
- examples/pipeline/hetero_poisson/README.md
- examples/pipeline/hetero_stepwise/README.md
- examples/pipeline/local_baseline/README.md
- examples/pipeline/union/README.md
- examples/pipeline/upload/README.md
- python/fate_test/fate_test/cli.py
> add pipeline job name

- python/federatedml/protobuf/model_migrate/converter/converter_base.py
- python/federatedml/protobuf/model_migrate/converter/pearson_model_converter.py
> integrate auto replacer

- python/fate_arch/computing/spark/_table.py
> fix bug: _flat_map return NoneType

- examples/benchmark_quality/hetero_nn/hetero_nn_benchmark.json
- examples/benchmark_quality/hetero_nn/hetero_nn_breast_config.yaml
- examples/benchmark_quality/hetero_nn/hetero_nn_default_credit_config.yaml
- examples/benchmark_quality/hetero_nn/hetero_nn_epsilon_5k_config.yaml
- examples/benchmark_quality/hetero_nn/hetero_nn_give_credit_config.yaml
- examples/benchmark_quality/hetero_nn/hetero_nn_keras.py
- examples/benchmark_quality/hetero_nn/hetero_nn_vehicle_scale_config.yaml
- examples/benchmark_quality/hetero_nn/pipeline-hetero-nn.py
> add hetero_nn benchmark

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_host.py
- python/federatedml/param/boosting_param.py
> Feature 1.5 fast hist rename

- python/fate_flow/scheduler/dsl_parser.py
- python/fate_flow/utils/parameter_util.py
> edit dsl_parser not check predict parameter redundant of dsl v1

- python/fate_test/fate_test/cli.py
> add data-only support

- examples/dsl/v2/hetero_secureboost/hetero_secureboost_testsuite.json
> fix testsuite

- federatedml/param/scorecard_param.py
- federatedml/statistic/scorecard/score_transformer.py
Fixes  ISSUE #2043 
Changes:
1. Fix result data schema if running single-scorecard-module job
2.
3.
> Feature 1.4.6 scorecard

- python/fate_test/fate_test/cli.py
> load suite safe

- python/fate_test/fate_test/_flow_client.py
> fix progress

- examples/toy_example/run_toy_example.py
- examples/toy_example/toy_example_conf.json
> edit toy example to support spark backend

- examples/benchmark_quality/hetero_sbt/fate_sbt_binary.yaml
- examples/benchmark_quality/hetero_sbt/fate_sbt_eplison_5k.yaml
- examples/benchmark_quality/hetero_sbt/fate_sbt_multi.yaml
- examples/benchmark_quality/hetero_sbt/fate_sbt_regression.yaml
- examples/dsl/v2/hetero_secureboost/test_secureboost_train_binary_with_missing_value_conf.json
- examples/dsl/v2/homo_secureboost/test_secureboost_train_binary_with_missing_value_conf.json
> Feature 1.5 all sbt benchmark

- examples/dsl/v2/intersect/intersect_testsuite.json
- examples/dsl/v2/intersect/test_intersect_job_dsl.json
- examples/dsl/v2/intersect/test_intersect_job_raw_conf.json
- examples/dsl/v2/intersect/test_intersect_job_raw_multi_host_conf.json
- examples/dsl/v2/intersect/test_intersect_job_rsa_conf.json
- examples/dsl/v2/intersect/test_intersect_job_rsa_multi_host_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/hetero_lr_testsuite.json
- examples/experiment_template/dsl/v2/hetero_secureboost/hetero_sbt_testsuite.json
> Feature 1.5 pipeline examples

- examples/benchmark_quality/hetero_lr/hetero_lr_sklearn_benchmark.json
- examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
- examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
- examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
- examples/benchmark_quality/homo_lr/pipeline-lr-binary.py
- examples/benchmark_quality/homo_lr/sklearn-lr-binary.py
> edit benchmark

- examples/federatedml-1.x-examples/scorecard/test_scorecard_job_conf.json
- federatedml/param/scorecard_param.py
- federatedml/statistic/scorecard/README.rst
- federatedml/statistic/scorecard/score_transformer.py
Fixes  ISSUE #2043 
Changes:
1. add configurable param factor base
2. edit examples & document
3.
> add configurable param factor base

- examples/dsl/v2/hetero_feature_binning/README.md
- examples/dsl/v2/hetero_feature_binning/hetero_feature_binning_testsuite.json
- examples/dsl/v2/hetero_feature_selection/README.md
- examples/dsl/v2/hetero_logistic_regression/README.md
- python/federatedml/statistic/README.rst
Changes:
1. Add statistic readme
2.
3.
> add data statistic readme

- examples/pipeline/intersect/intersect_testsuite.json
> add testsuite of pipeline intersect

- examples/pipeline/homo_nn/pipeline_homo_nn_multi_label.py
- examples/pipeline/homo_nn/pipeline_homo_nn_multi_layer.py
- examples/pipeline/homo_nn/pipeline_homo_nn_single_layer.py
- examples/pipeline/homo_nn/runner.py
- python/fate_test/fate_test/_parser.py
- python/fate_test/fate_test/cli.py
> move config reflash inside suite

- examples/dsl/v2/hetero_pearson/README.md
- examples/dsl/v2/homo_nn/README.md
- examples/pipeline/hetero_pearson/README.md
- examples/pipeline/homo_nn/README.md
- add dsl/pipeline docs for homo nn and pearson
- add dsl/pipeline docs for homo nn and pearson
> doc 1.5.0 homo nn dsl and pipeline

- python/fate_client/pipeline/backend/config.py
Changes:
1. fix status code for pipeline 
2.
3.
> Feature 1.5 doc update

- python/fate_arch/storage/hdfs/_table.py
> add file exist check

- examples/benchmark_quality/hetero_nn/local-hetero_nn.py
> fix hetero_nn local benchmark

- README.md
- README_zh.md
> edit readme

- examples/benchmark_quality/hetero_fast_sbt/fate-fast-sbt.py
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_layered_epsilon_5k.yaml
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_layered_multi.yaml
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_layered_regression.yaml
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_mix_epsilon_5k.yaml
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_mix_multi.yaml
- examples/benchmark_quality/hetero_fast_sbt/fate_fast_sbt_mix_regression.yaml
- examples/benchmark_quality/hetero_fast_sbt/gbdt-binary.py
- examples/benchmark_quality/hetero_fast_sbt/gbdt-multi.py
- examples/benchmark_quality/hetero_fast_sbt/gbdt-regression.py
- examples/benchmark_quality/hetero_fast_sbt/hetero_fast_sbt_gbdt_benchmark.json
- examples/benchmark_quality/hetero_sbt/fate_sbt_epsilon_5k.yaml
- examples/benchmark_quality/hetero_sbt/fate_sbt_multi.yaml
- examples/benchmark_quality/hetero_sbt/gbdt-binary.py
- examples/benchmark_quality/hetero_sbt/gbdt-multi.py
- examples/benchmark_quality/hetero_sbt/gbdt-regression.py
- examples/benchmark_quality/hetero_sbt/hetero_sbt_gbdt_benchmark.json
- examples/benchmark_quality/homo_sbt/fate_sbt_eplison_5k.yaml
- examples/benchmark_quality/homo_sbt/fate_sbt_multi.yaml
- examples/benchmark_quality/homo_sbt/gbdt-binary.py
- examples/benchmark_quality/homo_sbt/gbdt-multi.py
- examples/benchmark_quality/homo_sbt/gbdt_config_binary.yaml
- examples/benchmark_quality/homo_sbt/homo_sbt_gbdt_benchmark.json
- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-mix-binary-multi-host.py
- python/federatedml/param/boosting_param.py
> update benchmark/ fix param doc/ fix pipeline

- python/federatedml/linear_model/logistic_regression/README.rst
- python/federatedml/param/logistic_regression_param.py
> Add fedprox description

- conf/service_conf.yaml
- examples/pipeline/hetero_pearson/pipeline_hetero_pearson.py
- examples/pipeline/hetero_pearson/pipeline_hetero_pearson_host_only.py
- examples/pipeline/hetero_pearson/pipeline_hetero_pearson_mix_rand.py
- examples/pipeline/hetero_pearson/pipeline_hetero_pearson_sole.py
- fix hetero pearson pipeline examples
- set service_conf.yaml work_mode 1
> bugfix 1.5.0 pipeline example hetero pearson

- examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
- examples/pipeline/hetero_feature_binning/hetero_feature_binning_testsuite.json
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-asymmetric.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-bucket-binning.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-category-binning.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-large-bin.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multi-host-optimal.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multi-host-sparse-optimal.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multi-host.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-optim-chi-square.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-optim-gini.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-optim-iv.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-optim-ks.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-quantile-binning.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-skip-statistic.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-bucket-binning.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-chi-square.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-gini.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-iv.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-ks.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-woe-binning.py
- examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
> fix pipeline

- python/fate_test/fate_test/scripts/_options.py
- python/fate_test/fate_test/scripts/benchmark_cli.py
- python/fate_test/fate_test/scripts/cli.py
- python/fate_test/fate_test/scripts/config_cli.py
- python/fate_test/fate_test/scripts/data_cli.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
> support use command's options in subcommand

- examples/benchmark_quality/homo_nn/fate-homo_nn.py
- examples/benchmark_quality/homo_nn/local-homo_nn.py
- examples/benchmark_quality/homo_nn/param_conf_binary.yaml
- examples/benchmark_quality/homo_nn/param_conf_multi.yaml
> better configuration

- python/federatedml/ensemble/README.rst
- python/federatedml/transfer_learning/hetero_ftl/README.rst
> Feature 1.5 doc review

- examples/dsl/v2/homo_logistic_regression/homo_logistic_regression_testsuite.json
> edit homo_lr dsl v2 predict error

- python/fate_arch/federation/rabbitmq/_federation.py
- python/fate_arch/federation/rabbitmq/_mq_channel.py
> fixed rabbitmq/federation

- examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-iv-top-k.py
- examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-manually-left.py
- examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-manually.py
- examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-multi-host.py
> fix pipeline error

- python/fate_test/fate_test/scripts/_options.py
> add work-mode/backend option to fate_test

- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_job_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_manually_job_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_pearson_job_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_sample_job_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_union_job_conf.json
- examples/experiment_template/dsl/v2/hetero_lr/test_hetero_lr_train_verify_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
> upgrade experiment_template parameter format

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/fast_feature_histogram.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- python/federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
- python/federatedml/ensemble/boosting/boosting_core/homo_boosting.py
> Feature 1.5 remove eggroll old interface

- python/fate_arch/computing/eggroll/_table.py
- python/fate_arch/federation/eggroll/_federation.py
> rollback eggroll 2.2

- python/fate_arch/computing/spark/_materialize.py
- python/fate_arch/federation/rabbitmq/_federation.py
> Feature 1.5 rabbitmq dylan

- examples/pipeline/demo/pipeline-quick-demo.py
- python/fate_client/pipeline/backend/pipeline.py
> Add pipeline quick mode & modify pipeline 

- python/fate_test/fate_test/scripts/testsuite_cli.py
> rename complete to success

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/fast_feature_histogram.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
> correct model name

- python/federatedml/framework/hetero/procedure/table_aggregator.py
- python/federatedml/framework/hetero/procedure/table_random_padding_cipher.py
- python/federatedml/secureprotol/encrypt.py
Changes:
1. Edit table aggregator
2.
3.
> edit table aggregator

- python/fate_arch/computing/spark/_table.py
- python/fate_arch/federation/rabbitmq/_federation.py
> distributed receive table and change collect stratege

- python/fate_flow/apps/data_access_app.py
- python/fate_test/fate_test/_config.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
> add clean data switcher

- python/fate_arch/_standalone.py
> table maybe clean in multihost

- examples/pipeline/hetero_nn/pipeline-hetero-nn-train-binary.py
- examples/pipeline/hetero_nn/pipeline-hetero-nn-train-multi.py
- examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-early-stop.py
- python/fate_client/pipeline/component/component_base.py
- python/fate_client/pipeline/component/hetero_nn.py
- python/fate_client/pipeline/component/nn/models/sequantial.py
> Feature 1.5 fix hetero nn pipeline error

- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-optim-iv.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-multi.py
- python/federatedml/linear_model/logistic_regression/base_logistic_regression.py
fix pipeline error
Changes:
1.
2.
3.
> fix hetero_lr

- python/fate_flow/db/db_models.py
> fix t_task no job id primary key

- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_manually_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_one_hot_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_pearson_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_test_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_union_sbt.py
Changes:
1.Secureboost: Removes the arbiter parameter
2.Onehot component name and component parameter changes
> sbt_one_hot and sbt_arbiter

- doc/dsl_conf_v2_setting_guide.rst
> Feature 1.5 update doc 1028

- examples/dsl/v1/hetero_feature_binning/test_sparse_optimal_binning_chi_square_job_conf.json
- python/federatedml/unsupervised_learning/kmeans/hetero_kmeans/hetero_kmeans_arbiter.py
> Feature 1.5 formal fix

- python/fate_flow/apps/data_access_app.py
Changes:
1. fix fate flow upload data bug
> fix upload bug

- python/fate_flow/apps/model_app.py
> fix import model

- python/federatedml/param/hetero_kmeans_param.py
> add k check

- python/federatedml/linear_model/logistic_regression/base_logistic_regression.py
fix comments: one_ve_rest should be one_vs_rest
Changes:
1. the comments: one_ve_rest should be one_vs_rest
> fix comments: one_ve_rest should be one_vs_rest

- python/fate_flow/apps/tracking_app.py
- python/fate_flow/pipelined_model/migrate_model.py
- python/fate_flow/utils/config_adapter.py
- python/fate_flow/utils/job_utils.py
Changes:
1. fix problem of getting output model from migrated model failed
2.
3.
> fix problem of getting output model from migrated model failed

- cluster-deploy/build.md
- standalone-deploy/README.md
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Fixes  ISSUE #1987 
Changes:
1.update standalone deploy document for 1.5.0
> Featrue 1.5.0 deploy standalone

- python/fate_arch/storage/metastore/base_model.py
- python/fate_flow/db/db_models.py
> fix datatime field in sqlite

- python/fate_flow/scheduler/dsl_parser.py
> dsl version 2 allow reader as a predict component

- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
> edit log info

- doc/dsl_conf_v2_setting_guide.rst
- python/fate_flow/doc/Fate_Flow_Model_Migration_Guide.md
> Feature 1.5 update doc 1030

- doc/dsl_conf_v2_setting_guide.rst
- examples/README.rst
- examples/experiment_template/user_usage/dsl_v1_predict_tutorial.md
- examples/experiment_template/user_usage/dsl_v2_predict_tutorial.md
- examples/experiment_template/user_usage/pipeline_predict_tutorial.md
- python/fate_client/pipeline/README.rst
> Feature 1.5 user tutorial

- python/fate_arch/federation/rabbitmq/_federation.py
> fixed federation bug in arbiter mode

- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-ovr-sqn.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-multi-host.py
Changes:
1. fix pipeline-examples error
2.
3.
> Feature 1.5 fix example 1031

- examples/dsl/v1/hetero_fast_secureboost/test_fast_sbt_layered_conf.json
- examples/dsl/v1/hetero_fast_secureboost/test_fast_sbt_layered_multiclass_conf.json
- examples/dsl/v1/hetero_fast_secureboost/test_fast_sbt_layered_regression_conf.json
- examples/dsl/v2/homo_secureboost/test_secureboost_train_binary_with_missing_value_conf.json
- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-layered-binary.py
- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-layered-multi.py
- examples/pipeline/hetero_fast_sbt/pipeline-hetero-sbt-layered-regression.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-complete-secure.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-cv.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-missing-value.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-early-stop.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-multi-cv.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-multi.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-regression-cv.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-regression-multi-host.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-regression.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-cv.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt-binary-multi-host.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt-multi-cv.py
- examples/pipeline/homo_sbt/pipeline-homo-sbt-regression-cv.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/decision_tree.py
- python/federatedml/ensemble/boosting/boosting_core/boosting.py
- python/federatedml/param/boosting_param.py
> Feature 1.5 rdd&conf fix

- examples/README.rst
- examples/benchmark_quality/hetero_linear_regression/local-linr.py
- examples/config.yaml
- examples/pipeline/demo/pipeline-quick-demo.py
- python/fate_test/README.rst
- python/fate_test/fate_test/scripts/benchmark_cli.py
- python/federatedml/param/linear_regression_param.py
- python/federatedml/param/poisson_regression_param.py
Changes:
1. edit quick pipeline demo
2. edit benchmark cli
3. edit examples & doc
> Feature 1.5 quick run doc

- examples/pipeline/README.rst
- examples/pipeline/upload/pipeline-upload.py
- python/fate_client/pipeline/utils/tools.py
Changes:
1. use 'data base dir' in pipeline tools config loader
2. edit doc & example
3.
> edit example & doc

- examples/benchmark_quality/homo_nn/homo_nn_benchmark.json
- examples/benchmark_quality/homo_nn/local-homo_nn.py
----
Changes:
1. use data_base_dir to search data
2. format with black
> fix local data path and format with black

- python/fate_flow/apps/model_app.py
Changes:
1. fix model app
2.
3.
> feature-1.5.0-system-engineering

- python/fate_flow/operation/task_executor.py
> fix task executor job parameters on party

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_cluster_install_guide_ansible.md
- cluster-deploy/doc/Fate_guest_install_guide_ansible.md
Changes:
1. cluster deploy doc modify
2.
3.
> Feature 1.5.0 lts deploy doc

- python/fate_flow/utils/parameter_util.py
Changes:
1. fix get reader dataset in dsl version 2
2.
3.
> fix get input dataset name in dsl version 2

- examples/dsl/v2/homo_nn/mnist_demo/build_mnist_testsuite.py
> fix mnist demo in dsl v2

- python/federatedml/README_zh.rst
----
Changes:
1. fix list-tables
2.
3.
> fix list-tables

- README.md
- doc/readthedoc/index.rst
> fix readthedoc index

- python/fate_flow/service.sh
> fate flow service.sh add exec

- examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
- examples/benchmark_quality/hetero_lr/vechile_config.yaml
- examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
- examples/benchmark_quality/homo_lr/sklearn-lr-binary.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- python/federatedml/optim/initialize.py
- python/federatedml/optim/optimizer.py
> Remove log & fix benchmark

- python/federatedml/test/run_test.sh
> delete unittest of fate_flow

- .travis.yml
- README.md
Changes:
1. edit travis ci
2.
3.
> Feature 1.5 edit travis

- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
fix dtable interface in spdz module can't return right result when make add operation
for example:
a = 1.1234
b = 2.1111
a + b = 32345
> fix spdz table add

- examples/dsl/v1/hetero_logistic_regression/test_lr_with_feature_engineering_dsl.json
> edit dsl file， remove need_deploy

- docker-build/build_cluster_docker.sh
"[INFO] Package fateboard start" should be "[INFO] Package eggroll  start"
Changes:
1.
2.
3.
> fix log:  fateboard should be  eggroll

- python/fate_arch/abc/_computing.py
> fix doc format view in readthedoc

- doc/dsl_conf_v2_setting_guide.rst
> fix doc error

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/param/boosting_param.py
> fix fast sbt param naming error

- examples/min_test_task/run_task.py
Changes:
1. Add load/bind in min-test
2.
3.
> edit min-test

- doc/readthedoc/conf.py
> fix md links

- python/federatedml/model_base.py
> clarify error message

- examples/dsl/v2/intersect/test_intersect_job_rsa_conf.json
- examples/pipeline/intersect/pipeline-intersect-rsa.py
- python/fate_client/pipeline/param/intersect_param.py
- python/federatedml/param/intersect_param.py
- python/federatedml/secureprotol/hash/hash_factory.py
- python/federatedml/statistic/intersect/intersect.py
- python/federatedml/statistic/intersect/intersect_guest.py
- python/federatedml/statistic/intersect/intersect_host.py
- python/federatedml/statistic/intersect/test/intersection_guest_test.py
- python/federatedml/util/consts.py
- python/requirements.txt
Fixes  ISSUE ##2354
Changes:
1. add RSAParams
2. add sm3 as a hash method option 
3. edit some examples
> Feature 1.6 intersect gm

- python/fate_client/pipeline/README.rst
- python/fate_client/pipeline/backend/pipeline.py
- python/fate_client/pipeline/utils/invoker/job_submitter.py
- python/fate_test/fate_test/_flow_client.py
- python/fate_test/fate_test/_parser.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
Fixes  ISSUE #2379 
Changes:
1. adapts to changes in ISSUE #2378 
2. some changes to Pipeline
3. some changes to FATE-Test, distinguishes information fed to v1 & v2 dsl of prediction job
> Feature 1.5.1 pipeline predict

- python/fate_arch/storage/_utils.py
- python/fate_arch/storage/metastore/db_models.py
- python/fate_flow/apps/job_app.py
- python/fate_flow/apps/table_app.py
- python/fate_flow/apps/tracking_app.py
- python/fate_flow/components/reader.py
- python/fate_flow/components/upload.py
- python/fate_flow/controller/job_controller.py
- python/fate_flow/db/db_models.py
- python/fate_flow/entity/types.py
- python/fate_flow/manager/data_manager.py
- python/fate_flow/operation/job_clean.py
- python/fate_flow/operation/job_saver.py
- python/fate_flow/operation/task_executor.py
- python/fate_flow/scheduler/dag_scheduler.py
- python/fate_flow/scheduler/federated_scheduler.py
- python/fate_flow/scheduler/task_scheduler.py
- python/fate_flow/scheduling_apps/party_app.py
- python/fate_flow/scheduling_apps/tracker_app.py
- python/fate_flow/utils/api_utils.py
- python/fate_flow/utils/authentication_utils.py
> Feature 1.5.1 fate flow api

- python/fate_client/pipeline/param/logistic_regression_param.py
- python/federatedml/param/logistic_regression_param.py
> edit default parameters in homo-lr

- python/fate_arch/federation/rabbitmq/_rabbit_manager.py
> when partions >=10, task is blocked. Fixed bug in policy pattern

- docker-build/build_cluster_docker.sh
- docker-build/docker/base/Dockerfile
- docker-build/docker/modules/python-nn/Dockerfile
- docker-build/docker/modules/python/Dockerfile
- python/requirements.txt
Signed-off-by: Bisheng Li <lbisheng@vmware.com>
Changes:
1.  Splitting python image to nn and non-nn
> Splitting python image to nn and non-nn

- .github/workflows/docker_push.yaml
- docker-build/build_cluster_docker.sh
Add github action to build and push image once on master update or tag
> finished the build and push workflow of github action

- cluster-deploy/doc/fate_on_spark_deployment_guide.md
- cluster-deploy/doc/fate_on_spark_deployment_guide_zh.md
> fix fate on spark deploy document

- python/fate_flow/pipelined_model/migrate_model.py
Changes:
1. fix model migration
2.
3.
> Feature 1.5.0 migrate fix

- python/fate_flow/apps/model_app.py
Changes:
1. modify output format of predict dsl
2.
3.
> Feature 1.5.1 fateflow model

- .github/workflows/docker_push.yaml
- docker-build/build_cluster_docker.sh
- docker-build/docker/base/Dockerfile
- docker-build/docker/modules/python-nn/Dockerfile
- docker-build/docker/modules/python/Dockerfile
- python/requirements.txt
1. Update script to reduce the size of images by splitting nn and non-nn.
2. Add github action workflow to build and push images on master changed or tagged.
> Reduce the Images Size

- python/fate_client/pipeline/component/README.rst
- python/federatedml/README_zh.rst
Changes:
1. fix doc link
2.
3.
> fix link in doc

- python/federatedml/ensemble/boosting/boosting_core/predict_cache.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_host.py
- python/federatedml/evaluation/metrics/classification_metric.py
- python/federatedml/util/validation_strategy.py
- python/requirements.txt
> Feature 1.5.1 psi&sbt fix

- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
> fix predict cache

- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_sample_job_conf.json
- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_select_job_conf.json
- examples/experiment_template/dsl/v1/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
Changes:
1. tag delimitor update
2. eggroll_run update
> Feature 1.5.1 fix sbt experimemt template

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_plan.py
fix host id matching in fast-sbt mix mode
> fix fast sbt host id type

- python/federatedml/feature/binning/quantile_binning.py
- python/federatedml/feature/binning/quantile_summaries.py
> fix collect problem

- python/fate_arch/_standalone.py
> [#2454] fix bug

- examples/toy_example/run_toy_example.py
Changes:
1. toy_example: raise error when job_log command execution fails
2.
3.
> toy example enhance: raise error when job_log command is failed

- python/fate_flow/scheduler/task_scheduler.py
- python/fate_flow/settings.py
> Feature 1.5.1 fate flow

- python/requirements.txt
> add cryptography requirement

- docker-build/build_cluster_docker.sh
> fix the source dir variable in image build script

- python/federatedml/evaluation/metrics/classification_metric.py
> fix psi interval

- python/federatedml/feature/binning/quantile_binning.py
Changes:
1. Fix statistic error
2.
3.
> fix binning

- python/federatedml/secureprotol/README.rst
> fix spdz docs

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/param/boosting_param.py
> fix param typo

- examples/dsl/v2/data_split/data_split_testsuite.json
- examples/dsl/v2/data_split/test_homo_data_split_validate_job_conf.json
- examples/pipeline/data_split/data_split_testsuite.json
- examples/pipeline/data_split/pipeline-homo-data-split-validate.py
- python/federatedml/model_selection/data_split/data_split.py
- python/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py
- python/federatedml/statistic/intersect/intersect_guest.py
- python/federatedml/statistic/union/union.py
Changes:
1. fix test size calculation when only input validate size
2. clean & format log 
3.
> Feature 1.5.1 data split fix

- python/fate_client/pipeline/param/consts.py
- python/fate_client/pipeline/param/cross_validation_param.py
- python/federatedml/model_selection/k_fold.py
- python/federatedml/model_selection/start_cross_validation.py
- python/federatedml/param/cross_validation_param.py
- python/federatedml/util/component_properties.py
- python/federatedml/util/consts.py
Fixes  ISSUE #2362 
Changes:
1. Add optional data usage history of CV fold
2. Edit CrossValidationParam(federatedml & pipeline)
3. Edit Fold
> Feature 1.6 cv output

- python/fate_client/pipeline/param/scale_param.py
- python/federatedml/param/scale_param.py
Changes:
1. edit default param for scale module & pipeline
2.
3.
> edit default param

- python/federatedml/feature/binning/optimal_binning/optimal_binning.py
- python/federatedml/feature/homo_onehot/homo_ohe_base.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
- python/federatedml/optim/gradient/hetero_sqn_gradient.py
- python/federatedml/optim/optimizer.py
> rm some log

- python/fate_test/fate_test/_config.py
> support additional role type

- python/fate_flow/manager/resource_manager.py
> fix resource manager request_task_cores compatibility with 1.5.0

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_host.py
- python/federatedml/param/boosting_param.py
> fix param typo/ modify predict check

- python/fate_flow/examples/publish_load_model.json
- python/fate_test/flow_test/config/settings.json
- python/fate_test/flow_test/run_task.py
> modify fate flow run task

- python/fate_flow/apps/job_app.py
- python/fate_flow/doc/fate_flow_http_api.rst
Changes:
1. update fate flow api doc
2. fix predict dsl generator
3.
> Feature 1.5.1 flow doc

- python/fate_flow/tests/grpc/client.py
- python/fate_flow/tests/grpc/server.py
- python/fate_flow/tests/grpc/xthread.py
> add grpc tests

- cluster-deploy/build.sh
> modify build tar file name

- python/federatedml/statistic/intersect/intersect.py
Fixes  #2433 
Changes:
1. fix intersect unified calculation 
2.
3.
> fix rsa unified

- cluster-deploy/upgrade/1_5_0-1_5_1/Fate_v1.5.0-v1.5.1_upgrade_guide_zh.md
- cluster-deploy/upgrade/1_5_0-1_5_1/upgrade_fate_flow_db.sql
Changes:
1. add upgrade guide and sql file
2.
3.
> add upgrade guide and sql file

- python/fate_test/fate_test/_config.py
> edit fate-test

- python/federatedml/statistic/feldman_verifiable_sum/feldman_verifiable_sum_host.py
Fixes  #2488 
Changes:
1. fix repeated transfer variable tag
2.
3.
> fix repeated tag

- python/fate_test/fate_test/scripts/benchmark_cli.py
Changes:
1. catch exception while running benchmark
2.
3.
> Feature 1.6 benchmark catch

- python/fate_flow/components/reader.py
> fix reader component bug

- python/fate_client/pipeline/test/test_upload.py
- python/fate_test/fate_test/_flow_client.py
- python/federatedml/param/stepwise_param.py
> fix arch use

- python/federatedml/evaluation/evaluation.py
> support fateboard

- python/federatedml/statistic/intersect/intersect.py
Changes:
1. fix rsa with fraction
2.
3.
> Feature 1.6 linr fix

- examples/min_test_task/config/test_hetero_lr_train_job_conf.json
- examples/min_test_task/config/test_intersect_job_conf.json
- examples/min_test_task/config/test_secureboost_train_binary_conf.json
- examples/toy_example/toy_example_conf.json
> change processor per node to task cores

- python/federatedml/util/validation_strategy.py
> Feature 1.5.1 early stop strategy

- python/fate_arch/common/versions.py
> add fn `get_fate_version`

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/node.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitter.py
- python/federatedml/ensemble/boosting/homo/homo_secureboost_client.py
- python/federatedml/ensemble/boosting/homo/homo_secureboosting_aggregator.py
- python/federatedml/ensemble/test/hack_encrypter.py
> Feature 1.6 sbt fix

- python/federatedml/feature/binning/optimal_binning/optimal_binning.py
> rm useless collect

- examples/dsl/v2/hetero_linear_regression/README.md
- examples/dsl/v2/hetero_linear_regression/test_hetero_linr_cv_job_conf.json
- examples/dsl/v2/hetero_logistic_regression/README.md
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_cv_conf.json
- python/fate_client/pipeline/param/cross_validation_param.py
- python/federatedml/model_selection/k_fold.py
- python/federatedml/param/cross_validation_param.py
Fixes  #2363 
Changes:
1.  choose between score and instance value for cv output
2.
3.
> edit cv output

- python/fate_client/pipeline/param/pearson_param.py
-------
Changes:
1. add local vif param to pipeline
> add local vif param to pipeline

- python/fate_arch/_standalone.py
- python/fate_arch/computing/standalone/_table.py
1. reimplement map_reduce_partition
2. add partition shuffle to flat_map
3. format with black
-------
Changes:
1. reimplement map_reduce_partition
2. add partition shuffle to flat_map
3. format with black
> fix standalone implements

- examples/pipeline/sample_weight/pipeline-sample-weight-balanced.py
- examples/pipeline/sample_weight/pipeline-sample-weight-feature-engineering.py
- examples/pipeline/sample_weight/pipeline-sample-weight-multi-host.py
- examples/pipeline/sample_weight/pipeline-sample-weight-name.py
Changes:
1. fix sample weight examples 
2.
3.
> Feature 1.6 cv pred output

- python/fate_arch/federation/rabbitmq/_federation.py
- python/fate_arch/federation/standalone/_federation.py
Changes:
1. add duplicated tag detaction for standalone
2. add duplicated tag detaction for spark
3. format with black
> add duplicated tag detection

- examples/pipeline/sample_weight/pipeline-sample-weight-feature-engineering.py
> fix sample weight examples

- python/federatedml/ensemble/boosting/boosting_core/boosting.py
- python/federatedml/nn/hetero_nn/hetero_nn_base.py
- python/federatedml/transfer_learning/hetero_ftl/ftl_base.py
- python/federatedml/util/validation_strategy.py
> fix arbiter

- .travis.yml
> Feature 1.5.1 travis

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/param/boosting_param.py
> fix pipeline param

- examples/README.rst
- examples/README_zh.rst
- examples/dsl/v2/multi_model_pipeline/test_multi_pipeline_dsl.json
- examples/pipeline/local_baseline/local_baseline_testsuite.json
- examples/pipeline/local_baseline/pipeline-local-baseline-sample-weight.py
Changes:
1. add doc for cv task
2.  fix some dsl bugs:link cv's output to evaluation
3.
> Feature 1.6 fix cv with evaluation

- examples/dsl/v2/homo_feature_binning/homo_feature_binning_testsuite.json
- python/fate_client/pipeline/component/homo_feature_binning.py
> Add binning component in pipeline

- python/fate_client/pipeline/param/logistic_regression_param.py
> Add binning and selection

- python/fate_client/pipeline/param/hetero_nn_param.py
- python/federatedml/nn/hetero_nn/backend/hetero_nn_model.py
- python/federatedml/nn/hetero_nn/hetero_nn_base.py
- python/federatedml/param/hetero_nn_param.py
Changes:
1. add hetero_nn param check and delete unused param
2.
3.
> Feature 1.6 hetero nn add param check

- examples/dsl/v2/hetero_linear_regression/test_hetero_linr_train_job_conf.json
- examples/pipeline/hetero_linear_regression/pipeline-hetero-linr.py
- python/fate_client/pipeline/param/linear_regression_param.py
- python/fate_client/pipeline/param/logistic_regression_param.py
- python/fate_client/pipeline/param/poisson_regression_param.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_base.py
- python/federatedml/param/linear_regression_param.py
- python/federatedml/param/logistic_regression_param.py
- python/federatedml/param/poisson_regression_param.py
Fixes  ISSUE #
Changes:
1.
2.
3.
> linr & poisson support float point

- python/fate_flow/utils/parameter_util.py
Changes:
1. dsl parser: modify the rule that when running some module, if the module does not support some role, it will be detete from runtime conf
2.
3.
> fix dsl parser, change submit_conf's role to depend on module

- python/federatedml/nn/hetero_nn/strategy/selector.py
Changes:
1. fix selective strategy error of hetero-nn
2.
3.
> fix select strategy of nn

- python/federatedml/statistic/intersect/intersect_model.py
- python/federatedml/statistic/intersect/repeat_id_process.py
Changes:
1.change repeatedid order, it will be more safe
2.add sample id process for 1.6.1 for next version
> repeated_id

- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/evaluation/evaluation.py
> evaluation not support cv

- python/fate_flow/utils/parameter_util.py
Changes:
1. fix function-called style problem
2.
3.
> fix parameter util naming problem

- examples/dsl/v2/homo_nn/mnist_demo/homo_nn_image_testsuite.json
> remove image testsuite

- examples/benchmark_quality/hetero_lr/epsilon_5k_config.yaml
- examples/benchmark_quality/hetero_lr/hetero_lr_sklearn_benchmark.json
- examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
- examples/benchmark_quality/hetero_lr/sklearn-lr-multi.py
- examples/benchmark_quality/hetero_lr/vechile_pipeline_config.yaml
- examples/scripts/query_schema.py
- python/federatedml/feature/homo_feature_binning/recursive_query_binning.py
- python/federatedml/feature/homo_feature_binning/virtual_summary_binning.py
- python/federatedml/param/logistic_regression_param.py
> Feature 1.6 fix lr binning

- python/federatedml/feature/homo_feature_binning/homo_binning_base.py
> rm useless log

- examples/dsl/v2/local_baseline/README.md
- examples/dsl/v2/local_baseline/local_baseline_testsuite.json
- examples/dsl/v2/local_baseline/test_local_baseline_homo_predict_job_conf.json
- examples/dsl/v2/local_baseline/test_local_baseline_homo_predict_job_dsl.json
- examples/dsl/v2/local_baseline/test_local_baseline_predict_job_conf.json
- examples/dsl/v2/local_baseline/test_local_baseline_predict_job_dsl.json
- examples/pipeline/local_baseline/pipeline-local-baseline-homo.py
- examples/pipeline/local_baseline/pipeline-local-baseline.py
- python/fate_test/fate_test/_config.py
- python/federatedml/local_baseline/local_baseline.py
- python/federatedml/model_selection/k_fold.py
- python/federatedml/model_selection/start_cross_validation.py
Changes:
1.   add load model to local baseline 
2. add examples 
3. fix comment
> local baseline load model

- python/federatedml/nn/backend/pytorch/data.py
- python/federatedml/nn/homo_nn/_torch.py
- python/federatedml/nn/homo_nn/enter_point.py
> fix homo nn board

- python/federatedml/secureprotol/encrypt.py
Since `pytorch` is not required for "non-nn" workflow, the underlying encryption model should be work without torch as dependency. this PR updates the torch import condition to address such situation.
> update the torch import condition

- python/fate_client/pipeline/param/__init__.py
> edit param

- python/fate_arch/computing/non_distributed.py
- python/requirements.txt
> add sid_name to local data

- examples/pipeline/data_transform/pipeline-data-transform-missing-fill.py
> enhance data transform example
