FederatedAI/FATE

- python/federatedml/statistic/correlation/hetero_pearson.py
> hetero pearson remove logs

- python/federatedml/statistic/intersect/intersect.py
Changes:
1. always generate at least 1 random base value
2.
3.
> edi intersect param

- examples/dsl/v2/feature_scale/README.md
- examples/dsl/v2/feature_scale/feature_scale_testsuite.json
- examples/dsl/v2/feature_scale/test_feature_scale_cap_conf.json
- examples/dsl/v2/feature_scale/test_feature_scale_cap_dsl.json
- examples/dsl/v2/feature_scale/test_feature_scale_normal_conf.json
- examples/dsl/v2/feature_scale/test_feature_scale_normal_dsl.json
- examples/pipeline/feature_scale/README.md
- examples/pipeline/feature_scale/feature_scale_testsuite.json
- examples/pipeline/feature_scale/pipeline-feature-scale-cap.py
- examples/pipeline/feature_scale/pipeline-feature-scale-normal.py
- examples/pipeline/multi_model/README.md
- examples/pipeline/multi_model/pipeline-multi-model.py
- python/fate_client/pipeline/param/scale_param.py
- python/federatedml/param/scale_param.py
Changes:
1. add examples & doc
2.
3.
> Feature 1.6 param fix

- python/fate_client/pyproject.toml
- python/fate_client/setup.py
- python/fate_test/pyproject.toml
- python/fate_test/setup.py
- python/federatedml/nn/backend/tf_keras/nn_model.py
- python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
- python/requirements.txt
> bump requirements

- python/fate_client/pyproject.toml
- python/fate_test/pyproject.toml
> fix dependencies

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/criterion.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/splitinfo_cipher_compressor.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/subsample.py
- python/federatedml/param/boosting_param.py
- python/federatedml/statistic/data_overview.py
> Feature 1.6 tree fix

- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
> fix fast sbt sample weight

- README.md
- examples/dsl/v2/README.rst
> fix doc link

- python/federatedml/evaluation/evaluation.py
- python/federatedml/util/validation_strategy.py
> Feature 1.6 pipeline summary fix

- python/federatedml/param/hetero_nn_param.py
Changes:
1. add range check for param drop_out_keep_rate
2.
3.
> add checker for hetero_nn_param's drop_out_keep_rate

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
> Feature 1.6 fix bin num

- examples/benchmark_quality/hetero_fast_sbt/fate-fast-sbt.py
- examples/benchmark_quality/hetero_linear_regression/fate-linr.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/benchmark_quality/hetero_lr/sklearn-lr-binary.py
- examples/benchmark_quality/hetero_nn/fate-hetero_nn.py
- examples/benchmark_quality/hetero_sbt/fate-sbt.py
- examples/benchmark_quality/homo_lr/pipeline-lr-binary.py
- examples/benchmark_quality/homo_nn/fate-homo_nn.py
- examples/benchmark_quality/homo_sbt/fate-sbt.py
- examples/benchmark_quality/parse_result.py
- examples/flow_test_template/flow_test_config.yaml
- python/fate_test/fate_test/_flow_client.py
- python/fate_test/fate_test/flow_test/flow_cli_api.py
- python/fate_test/fate_test/flow_test/flow_process.py
- python/fate_test/fate_test/flow_test/flow_rest_api.py
- python/fate_test/fate_test/flow_test/flow_sdk_api.py
- python/fate_test/fate_test/scripts/flow_test_cli.py
- python/fate_test/fate_test/utils.py
- python/fate_test/setup.py
Changes:
1.benchmark quality update
2.flow api test
> 1、benchmark quality update

- examples/pipeline/homo_feature_binning/homo_feature_binning_pipeline_testsuite.json
- examples/pipeline/homo_feature_binning/pipeline-homo-recursive-binning-predict.py
- examples/pipeline/homo_feature_binning/pipeline-homo-virtual-summary-binning-predict.py
- python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
> fix homo-binning

- python/federatedml/feature/scale.py
Changes:
1.fix scale bug for predict
> Dev 1.6 scale bug

- examples/dsl/v1/homo_onehot/train_job_conf.json
> fix homo-onehot

- python/fate_client/flow_client/README.rst
- python/fate_client/flow_client/README_zh.rst
> fix cli doc

- examples/dsl/v2/intersect/test_intersect_job_rsa_conf.json
- examples/pipeline/intersect/pipeline-intersect-rsa.py
- python/fate_client/pipeline/param/intersect_param.py
- python/federatedml/param/intersect_param.py
- python/federatedml/statistic/intersect/intersect.py
Changes:
1. add key_length to intersect param
2.
3.
> add intersect param

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/criterion.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/decision_tree.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/subsample.py
- python/federatedml/util/consts.py
fix hetero SBT float error/ stability bug
> Feature 1.6 float error

- python/fate_client/pipeline/backend/__init__.py
- python/fate_client/pipeline/backend/config.py
- python/fate_client/pipeline/config.yaml
- python/fate_client/pipeline/utils/invoker/job_submitter.py
- python/fate_client/pipeline/utils/logger.py
Changes:
1. add switch to control log output to console 
2.
3.
> edit logger

- python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
> fix homo-binning output data format

- examples/dsl/v2/homo_nn/mnist_demo/mnist_conf.json
fix data name
Fixes  example data
> 🐛 Fix a bug

- examples/dsl/v2/hetero_secureboost/test_secureboost_train_binary_cipher_compress_conf.json
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-cipher-compress.py
- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/decision_tree.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- python/federatedml/param/boosting_param.py
add stable reduce to ensure the stability of histogram computation
> Feature 1.6 stable reduce

- python/federatedml/util/data_io.py
> Feature 1.6 add dataio deprecated

- python/federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_client.py
> fix bin num

- python/fate_test/fate_test/_flow_client.py
- python/fate_test/fate_test/scripts/generate_mock_data.py
Changes:
1. timeout error update 
2. generate mock data update
> timeout error update and generate mock data update

- python/fate_client/pipeline/param/__init__.py
- python/fate_client/pipeline/param/intersect_param.py
- python/federatedml/param/intersect_param.py
- python/federatedml/statistic/intersect/intersect_model.py
- python/federatedml/statistic/intersect/repeat_id_process.py
Changes:
1. edit intersect param
2. fix pipeline param import 
3.
> Feature 1.6 repeated id edit

- examples/pipeline/README.rst
- examples/pipeline/demo/pipeline-quick-demo.py
- examples/pipeline/demo/pipeline-upload.py
- examples/pipeline/upload/pipeline-upload.py
- python/fate_client/README.rst
Changes:
1. edit pipeline & examples document 
2.
3.
> Feature 1.6 pipeline doc update

- python/federatedml/feature/binning/quantile_binning.py
> remove copy in merge

- python/federatedml/secureprotol/encrypt.py
>  🐛 Fix torch import issue

- python/federatedml/statistic/intersect/intersect_guest.py
- python/federatedml/statistic/intersect/intersect_host.py
Changes:
1. edit rsa op order
2. clean up log 
3.
> Feature 1.6 intersect split fix

- python/fate_client/pipeline/component/README.rst
- python/fate_client/pipeline/param/__init__.py
- python/federatedml/README.rst
- python/federatedml/README_zh.rst
- python/federatedml/param/__init__.py
- python/federatedml/util/README.rst
> Feature 1.6 doc edit

- python/federatedml/protobuf/model_migrate/converter/tree_model_converter.py
> add tree migrate anonymous check

- python/fate_flow/doc/fate_flow_http_api.rst
Changes:
1.fix deploy http api doc
2.
3.
> fix deploy http api doc

- examples/pipeline/sbt_feature_transformer/pipeline-sbt-transformer-fast-sbt.py
> fix pipeline example

- python/federatedml/feature/binning/base_binning.py
- python/federatedml/feature/binning/bin_inner_param.py
- python/federatedml/feature/binning/quantile_summaries.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
- python/federatedml/transfer_variable/auth_conf/hetero_feature_binning_transfer_variable.json
- python/federatedml/transfer_variable/transfer_class/hetero_feature_binning_transfer_variable.py
> Feature 1.6 binning optimize

- python/fate_client/pipeline/param/pearson_param.py
- python/federatedml/param/pearson_param.py
- python/federatedml/statistic/correlation/hetero_pearson.py
1. "VIF" stands for "Variance inflation factor"
> :pencil2: rename use_local_vaf to use_local_vif

- python/federatedml/util/test/sample_weight_test.py
> edit unittest

- python/federatedml/feature/binning/base_binning.py
- python/federatedml/feature/binning/optimal_binning/optimal_binning.py
- python/federatedml/feature/binning/test/bucket_binning_test.py
- python/federatedml/optim/gradient/test/hetero_lr_gradient_test.py
- python/federatedml/util/test/data_io_test.py
> fix unittest

- cluster-deploy/doc/fate_on_spark/FATE_on_spark_with_pulsar_zh.md
- conf/service_conf.yaml
- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_pulsar_manager.py
1. Topic TTL is the combination of `subscriptionExpirationTimeMinutes` and `ttlDurationDefaultInSeconds`
> Support Setting Topic TTL in FATE and Task Level

- cluster-deploy/README.md
- cluster-deploy/doc/Fate-allinone_deployment_guide_install_zh.md
- cluster-deploy/doc/Fate-exchange_deployment_guide_zh.md
- cluster-deploy/doc/Fate_cluster_install_guide_ansible.md
- cluster-deploy/doc/Fate_guest_install_guide_ansible.md
Fixes  ISSUE #2500 
Changes:
1.update doc for version 1.6.0
> Feature 1.6.0 deploy doc

- python/fate_test/fate_test/scripts/data_cli.py
> edit data cli

- standalone-deploy/README.md
- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
Signed-off-by: v_wbymxu <g6xuyiming@163.com>
Fixes  ISSUE #2702 
Changes:
1.update standalone document, add version reference
> update document file of standalone deploy

- examples/pipeline/sample_weight/pipeline-sample-weight-name.py
- python/federatedml/util/sample_weight.py
> sample weight add transform

- python/fate_client/flow_sdk/client/api/model.py
Changes:
1.fix model import function
2.
3.
> fix model import function

- python/federatedml/nn/hetero_nn/README.rst
> edit doc of hetero_nn: add new features

- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/ensemble/boosting/homo/homo_secureboost_client.py
> fix sbt eval

- .github/ISSUE_TEMPLATE/algorithm_implementation.md
standard issue template
Changes:
1. add issue template for new algorithm implemention
> create issue template for algorithm implemention

- .github/ISSUE_TEMPLATE/algorithm_implementation.md
1. add mgqa34 and dylan-fan as default algorithm issue assignee
> 📝 add assignee

- python/fate_client/flow_client/flow_cli/commands/model.py
update `flow` command short help
> update command short help

- doc/develop_guide.rst
- doc/develop_guide_zh.rst
Fixes  ISSUE #2746 
Changes:
1. Fix doc links
2.
3.
> Feature 1.6 fix doc

- python/fate_client/pipeline/backend/config.py
> better error message

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/feature_histogram.py
Changes:
1. secureboost 中 zero_opt_node_sum & zero_optim 计算逻辑优化
2.
3.
> optimize compute g_h on node's feature level and node level

- python/federatedml/feature/binning/base_binning.py
- python/federatedml/feature/binning/bin_inner_param.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
Fixes  ISSUE #2781 
Changes:
1. add woe/iv result of category features in hetero_binning algorithm
2.
3.
> add woe/iv result of category features in hetero_binning algorithm

- python/federatedml/linear_model/linear_model_weight.py
- python/federatedml/linear_model/linear_regression/base_linear_regression.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/optim/optimizer.py
Changes:
1. give warning instead of raising error when LinR model weights are greater than threshold 
2.
3.
> overflow warn for linr

- cluster-deploy/README.md
in 5.2 Minimize Test 5.2.2 fast mode
'cd /data/projects/fate/examples/toy_example/' should be '/data/projects/fate/examples/min_test_task/'
Signed-off-by: Yao544303 <yao544303963@gmail.com>
Changes:
1.
2.
3.
> fix readme.md

- python/fate_flow/apps/info_app.py
- python/fate_flow/fate_flow_server.py
> fate flow: api for get fateboard information

- python/federatedml/secureprotol/gmpy_math.py
> ✨ add crt powmod to gmpy_math

- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
Changes:
1. Optimize loss compute
2.
3.
> optimizer loss compute

- python/federatedml/param/base_param.py
> fix params

- python/fate_flow/tools/deal_rollsite_audit_log.py
- python/fate_flow/tools/rollsite_exchange_audit_index.json
- python/fate_flow/utils/job_utils.py
> Feature 1.5.2 tools

- python/fate_flow/db/db_models.py
- python/fate_flow/pipelined_model/pipelined_model.py
> pickle.dump bugfix

- examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_local_only_conf.json
- examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_local_only_dsl.json
- examples/dsl/v2/hetero_feature_selection/hetero_feature_selection_testsuite.json
- examples/pipeline/generated_testsuite.py
- examples/pipeline/hetero_feature_selection/hetero_feature_selection_testsuite.json
- examples/pipeline/hetero_feature_selection/pipeline-hetero-feature-selection-local-only.py
- python/federatedml/feature/binning/base_binning.py
- python/federatedml/feature/binning/bin_inner_param.py
- python/federatedml/feature/hetero_feature_selection/base_feature_selection.py
Fixes  ISSUE #2791 #2782 
Changes:
1. Fix selection error that cannot select locally in hetero-feature selection.
2. Fix category columns that cannot calculate iv. (Provided by huajinghua)
3.
> Fix binning and selection errors

- python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
- python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
Fixes  ISSUE #2760 
Changes:
1.
2.
3.
> sir support non-ascii id

- examples/dsl/v2/hetero_logistic_regression/hetero_lr_validate_conf.json
- examples/pipeline/hetero_logistic_regression/common_tools.py
- examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-ovr-validate.py
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-validate.py
- python/fate_client/pipeline/param/logistic_regression_param.py
- python/federatedml/linear_model/logistic_regression/base_logistic_regression.py
- python/federatedml/one_vs_rest/one_vs_rest.py
- python/federatedml/param/logistic_regression_param.py
Fixes  ISSUE #2853 
Changes:
1. Fix bug that fail to load model when fit_intercept is False
2. Fix bug that fail to set key_length for LR
3.
> Feature 1.5.2 fix lr

- examples/pipeline/hetero_logistic_regression/common_tools.py
- examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-ovr-validate.py
- python/federatedml/one_vs_rest/one_vs_rest.py
Fixes  ISSUE #2852 
Changes:
1. Fix validate function in ovr senario
2.
3.
> fix one_vs_rest validate

- README.md
- python/federatedml/README.rst
A typo of readme
Fixes  ISSUE #2841 
Changes:
1. Update readme typo
> A typo of document

- python/fate_arch/storage/_table.py
- python/fate_arch/storage/mysql/_table.py
- python/fate_flow/components/upload.py
- python/fate_flow/operation/job_tracker.py
> Feature 1.5.2 fate flow mysql

- python/fate_flow/scheduler/dsl_parser.py
Fixes  ISSUE #2867 
Changes:
1. add component param check for single component
2.
3.
> add component param check in parser

- python/fate_arch/computing/eggroll/_table.py
> 🐛 enhance sample strategy

- examples/dsl/v1/homo_onehot/train_job_conf.json
> Fix dsl v1 config

- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
> fix multiclass model loading

- python/fate_arch/common/profile.py
1. add "h" prefix to hash result to workround beautifultable bug
-------
Changes:
1.
2.
3.
> 🐛 workround beautifultable bug

- python/fate_client/flow_client/flow_cli/commands/data.py
- python/fate_flow/apps/__init__.py
- python/fate_flow/apps/data_access_app.py
- python/fate_flow/apps/info_app.py
- python/fate_flow/apps/job_app.py
- python/fate_flow/apps/model_app.py
- python/fate_flow/apps/permission_app.py
- python/fate_flow/apps/pipeline_app.py
- python/fate_flow/apps/proxy_app.py
- python/fate_flow/apps/table_app.py
- python/fate_flow/apps/tracking_app.py
- python/fate_flow/apps/version_app.py
- python/fate_flow/fate_flow_server.py
- python/fate_flow/scheduling_apps/initiator_app.py
- python/fate_flow/scheduling_apps/party_app.py
- python/fate_flow/scheduling_apps/tracker_app.py
- python/fate_flow/utils/api_utils.py
> Feature 1.7: register blueprint dynamically

- python/fate_flow/scheduler/dsl_parser.py
Fixes  ISSUE #2895 
Changes:
1.  fix deploy bug when some component has multiple input but not all its input is deployed
2.
3.
> fix dsl_parse deploy bug when multple input, but some is not deploy

- python/federatedml/loss/regression_loss.py
> fix loss func

- python/federatedml/linear_model/linear_model_weight.py
- python/federatedml/linear_model/linear_regression/base_linear_regression.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/linear_model/poisson_regression/base_poisson_regression.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- python/federatedml/optim/optimizer.py
Changes:
1.  remove model weights overflow error for Hetero LinR & Poisson
2.
3.
> edit overflow error

- python/fate_flow/utils/authentication_utils.py
> authentication exception

- python/fate_arch/_standalone.py
- python/fate_arch/computing/non_distributed.py
1. update license for "_standalone.py" and "non_distributed"
-------
Changes:
1.
2.
3.
> 📄 update license

- python/federatedml/framework/hetero/procedure/batch_generator.py
Fixes  ISSUE #2913 
Changes:
1.
2.
3.
> Fix join order problem

- python/federatedml/linear_model/linear_model_weight.py
- python/federatedml/linear_model/linear_regression/base_linear_regression.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/linear_model/poisson_regression/base_poisson_regression.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- python/federatedml/optim/optimizer.py
Changes:
1. do not raise overflow error for model weights of Hetero LinR & Poisson model
2.
3.
> fix overflow error

- doc/model_publish_with_serving_guide.md
- doc/model_publish_with_serving_guide_zh.md
- python/fate_flow/pipelined_model/publish_model.py
update load model to use transfer URL defined on serving server.
> update  function to use transfer url on serving

- python/fate_arch/_standalone.py
1. cache function deserialization
> 🐛 Fix function serde issue in standalone mode

- python/fate_arch/common/remote_status.py
- python/fate_arch/federation/eggroll/_federation.py
- python/fate_arch/session/_session.py
- python/fate_flow/operation/task_executor.py
1. blocking until all remote done
-------
Changes:
1.
2.
3.
> ✨ blocking until all remote done

- python/fate_client/pipeline/param/intersect_param.py
- python/federatedml/param/intersect_param.py
> edit intersect param

- examples/dsl/v2/data_statistics/data_statistics_all_columns_conf.json
- examples/dsl/v2/data_statistics/data_statistics_all_columns_dsl.json
- examples/dsl/v2/data_statistics/data_statistics_partial_column_conf.json
- examples/dsl/v2/data_statistics/data_statistics_partial_column_dsl.json
- examples/dsl/v2/data_statistics/data_statistics_partial_column_name_conf.json
- examples/dsl/v2/data_statistics/data_statistics_partial_column_name_dsl.json
- examples/dsl/v2/data_statistics/data_statistics_testsuite.json
- examples/pipeline/data_statistics/__init__.py
- examples/pipeline/data_statistics/data_statistics_pipeline_testsuite.json
- examples/pipeline/data_statistics/pipeline-data-statistics-all-columns.py
- examples/pipeline/data_statistics/pipeline-data-statistics-partial-column-name.py
- examples/pipeline/data_statistics/pipeline-data-statistics-partial-column.py
- python/federatedml/feature/binning/base_binning.py
Fixes  ISSUE #2921 
Changes:
1.
2.
3.
> Fix data statistic partial column in query quantile point

- python/fate_flow/controller/engine_adapt.py
- python/fate_flow/controller/engine_operation/base.py
- python/fate_flow/controller/engine_operation/eggroll.py
- python/fate_flow/controller/engine_operation/linkis_spark.py
- python/fate_flow/controller/engine_operation/spark.py
- python/fate_flow/controller/task_controller.py
- python/fate_flow/scheduler/detector.py
> separate computing engine

- python/fate_flow/scheduler/dsl_parser.py
> merge 1.5.2's parse' modify into 1.6.1

- python/federatedml/ensemble/boosting/boosting_core/boosting.py
- python/federatedml/evaluation/evaluation.py
- python/federatedml/util/validation_strategy.py
> add support for inst id

- python/fate_client/pipeline/param/encrypt_param.py
- python/federatedml/param/encrypt_param.py
> edit param doc

- python/federatedml/model_selection/data_split/data_split.py
Changes: merge data split update from contributor
1. from pr #2957 
2.
3.
> Feature 1.6.1 data split join

- python/federatedml/framework/scheduler/interface.py
- python/federatedml/framework/scheduler/setting_conf_parser.py
- python/federatedml/framework/scheduler/setting_conf_plugins.py
- python/federatedml/param/base_param.py
- python/federatedml/util/param_extract.py
> implement plugins based on setting conf

- cluster-deploy/doc/fate_on_spark/FATE_on_spark_with_pulsar_zh.md
- conf/service_conf.yaml
- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_mq_channel.py
- python/fate_flow/components/reader.py
- python/fate_flow/components/upload.py
1. Add more log info in federation
2. Refine message sending
3. Refine message receiving
4. Update the formatting
5. Refine Deployment of Pulsar Document
6. Refine the cancel function of federation
7. Append env reading of upload setting
> Feature 1.6.1 Add Try Catch to Partitions Recevie Process

- python/fate_arch/common/__init__.py
- python/fate_arch/common/_types.py
- python/fate_arch/session/_session.py
- python/fate_arch/storage/_session.py
- python/fate_arch/storage/metastore/base_model.py
- python/fate_arch/storage/metastore/db_models.py
> Feature 1.7.0 fate arch

- python/federatedml/feature/binning/bin_result.py
- python/federatedml/feature/binning/iv_calculator.py
- python/federatedml/feature/binning/test/iv_calculator_test.py
- python/federatedml/feature/feature_selection/model_adapter/binning_adapter.py
- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
> fix binning error

- python/fate_flow/scheduler/dsl_parser.py
Fixes  ISSUE  #2981 
Changes:
1. fix dsl_parser bug when not deploy some multiple output module like data-split
2.
3.
> fix dsl_parser bug when not deploy some multiple output module like data-split

- python/federatedml/model_base.py
> component output model json and fix bugs that component output model api

- python/federatedml/util/data_io.py
> dataio cache test

- python/fate_arch/federation/transfer_variable/_transfer_variable.py
1. add role parameters to `get` api
> ✨ `get` supports role parameters

- python/fate_arch/session/_session.py
- python/fate_arch/storage/_session.py
> fix bugs that get component output data from part of data

- python/fate_client/pipeline/backend/pipeline.py
- python/fate_client/pipeline/component/intersection.py
- python/fate_client/pipeline/interface/__init__.py
- python/fate_client/pipeline/interface/cache.py
- python/fate_client/pipeline/interface/output.py
Fixes  ISSUE #2993 
Changes:
1.  Support Cache in pipeline
2.
3.
> pipeline support cache

- python/fate_test/fate_test/_parser.py
- python/fate_test/fate_test/scripts/performance_cli.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
Changes:
1. Results display optimization
> Results display optimization

- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-early-stop.py
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-warm-start.py
- python/federatedml/callbacks/callback_base.py
- python/federatedml/callbacks/callback_list.py
- python/federatedml/callbacks/validation_strategy.py
- python/federatedml/evaluation/evaluation.py
- python/federatedml/linear_model/base_linear_model_arbiter.py
- python/federatedml/linear_model/linear_model_base.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_arbiter.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
- python/federatedml/model_base.py
- python/federatedml/util/component_properties.py
- python/requirements.txt
> Feature 1.7 callbacks

- python/federatedml/callbacks/callback_list.py
- python/federatedml/cipher_compressor/compressor.py
- python/federatedml/ensemble/boosting/boosting_core/boosting.py
- python/federatedml/feature/binning/bin_result.py
- python/federatedml/feature/binning/iv_calculator.py
- python/federatedml/feature/binning/quantile_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
> Feature 1.7 Fix Binning, Add compressor into binning

- python/fate_arch/storage/_table.py
> fix sqlite bug

- docker-build/build_cluster_docker.sh
- docker-build/docker/base/Dockerfile
- docker-build/docker/modules/python/Dockerfile
> Fix: docker build add conf and update Dockerfile

- python/requirements.txt
> fix requirement

- examples/dsl/v2/data_transform/data_transform_testsuite.json
- examples/pipeline/data_transform/data_transform_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-one-vs-all.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-review-guest.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr.py
- python/fate_client/pipeline/component/model_loader.py
- python/federatedml/callbacks/model_checkpoint.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_arbiter.py
- python/federatedml/model_base.py
- python/federatedml/one_vs_rest/one_vs_rest.py
2. Fix ovr
3. Fix data transform
Changes:
1.
2.
3.
> 1. Model loader

- python/federatedml/model_selection/k_fold.py
> fix k_fold

- python/federatedml/unsupervised_learning/kmeans/hetero_kmeans/hetero_kmeans_arbiter.py
> Feature 1.7 callback updates

- python/fate_client/pipeline/param/local_baseline_param.py
- python/federatedml/param/local_baseline_param.py
> fix local baseline param

- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-all-reveal-in-guest.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-review-guest.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
> change words

- python/federatedml/model_base.py
> Add step name replacement

- python/requirements.txt
> fate client requirements

- python/federatedml/components/components.py
- python/federatedml/components/homo_secure_boost.py
> Feature 1.7 homo sbt alias

- standalone-deploy/doc/Fate-standalone_deployment_guide_zh.md
> Feature 1.5.2 homo sbt aggreagator

- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-reveal-guest.py
> config error

- python/fate_test/setup.py
> modify fate test setup

- python/fate_flow/apps/service_app.py
> add service query

- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/__init__.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_arbiter.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_base.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_guest.py
- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
Fixes  ISSUE #3061 
Changes:
1.
2.
3.
> edit homo_lr single predict

- python/federatedml/model_base.py
> change step_name

- RELEASE.md
> release 1.6.1 fate flow

- python/fate_flow/scheduler/dsl_parser.py
- python/fate_flow/utils/parameter_util.py
Fixes  ISSUE #3061 
Changes:
1. dsl parser support homo algorithm predicting in single party
2.
3.
> Feature 1.6.1 dsl parser support single predict

- python/fate_flow/README.md
- python/fate_flow/README_zh.md
> modify fate flow doc

- python/fate_arch/federation/transfer_variable.py
> add bound check

- python/federatedml/secureprotol/fixedpoint.py
> fix detect logic

- python/federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py
- python/federatedml/util/component_properties.py
> add homo_lr single predict

- python/federatedml/linear_model/base_linear_model_arbiter.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
> fix  checkpoint error

- python/federatedml/param/sir_param.py
> edit sir param

- RELEASE.md
- python/federatedml/nn/hetero_nn/README.rst
Changes:
1. fix doc format of release note
2. fix doc error of hetero nn
3.
> fix doc of release doc & hetero nn

- python/fate_flow/utils/service_utils.py
> fix zookeeper bug

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/ensemble/boosting/boosting_core/boosting.py
- python/federatedml/param/boosting_param.py
> Feature 1.7 add param check

- examples/toy_example/run_toy_example.py
Changes:
1. fix toy example show log problem
2.
3.
> fix toy example show log

- python/federatedml/feature/feature_imputation.py
> raise missing col name error

- python/fate_arch/metastore/base_model.py
- python/federatedml/feature/instance.py
- python/federatedml/feature/sparse_vector.py
> fix component output bug

- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- python/federatedml/model_base.py
> Add warm_start callback info

- python/fate_arch/federation/_datastream.py
- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_mq_channel.py
- python/fate_arch/federation/rabbitmq/_federation.py
Signed-off-by: dylan-fan dylanfan@webank.com
Changes:
1. add datastream in federaion
2. merge pulsar from 1.6.1
> add datastream file and merge pulsar from 1.6.1

- python/fate_arch/storage/mysql/_table.py
> fix mysql storage table bug

- examples/pipeline/upload/README.md
- examples/pipeline/upload/pipeline-upload-extend-sid.py
- python/fate_client/pipeline/backend/pipeline.py
- python/fate_client/pipeline/utils/invoker/job_submitter.py
> update pipeline upload

- python/federatedml/framework/homo/blocks/random_padding_cipher.py
> purge logs

- python/fate_client/pipeline/param/homo_nn_param.py
- python/federatedml/nn/homo_nn/_version_0.py
- python/federatedml/nn/homo_nn/enter_point.py
- python/federatedml/param/homo_nn_param.py
> fix callback

- python/federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
- python/federatedml/ensemble/boosting/boosting_core/homo_boosting.py
> fateboard support

- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-cv.py
- python/fate_client/pipeline/param/hetero_sshe_lr_param.py
- python/federatedml/linear_model/base_linear_model_arbiter.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_arbiter.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
- python/federatedml/param/hetero_sshe_lr_param.py
2. callback init_iter for hetero_lr, homo_lr, sshe_lr
Changes:
1.
2.
3.
> 1. sshe_lr cv

- python/federatedml/feature/feature_imputation.py
- python/federatedml/feature/imputer.py
> fix feature imputation

- examples/dsl/v2/hetero_linear_regression/README.md
- examples/dsl/v2/hetero_linear_regression/hetero_linr_testsuite.json
- examples/dsl/v2/hetero_linear_regression/test_hetero_linr_train_sample_weight_job_conf.json
- examples/dsl/v2/hetero_linear_regression/test_hetero_linr_train_sample_weight_job_dsl.json
- examples/dsl/v2/sample_weight/README.md
- examples/dsl/v2/sample_weight/sample_weight_testsuite.json
- examples/dsl/v2/sample_weight/sample_weight_transform_job_dsl.json
- examples/pipeline/hetero_linear_regression/README.md
- examples/pipeline/hetero_linear_regression/hetero_linr_testsuite.json
- examples/pipeline/hetero_linear_regression/pipeline-hetero-linr-sample-weight.py
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-repeat.py
- examples/pipeline/sample_weight/README.md
- examples/pipeline/sample_weight/pipeline-sample-weight-transform.py
- examples/pipeline/sample_weight/sample_weight_testsuite.json
- python/federatedml/linear_model/linear_model_base.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_base.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- python/federatedml/optim/gradient/hetero_linear_model_gradient.py
- python/federatedml/optim/gradient/hetero_linr_gradient_and_loss.py
- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
- python/federatedml/statistic/data_overview.py
- python/federatedml/transfer_variable/transfer_class/hetero_linr_transfer_variable.py
- python/federatedml/transfer_variable/transfer_class/hetero_lr_transfer_variable.py
- python/federatedml/util/sample_weight.py
> edit sample weight

- python/federatedml/nn/hetero_nn/hetero_nn_base.py
- python/federatedml/nn/hetero_nn/hetero_nn_guest.py
- python/federatedml/nn/hetero_nn/hetero_nn_host.py
> fix hetero nn warm start round

- python/federatedml/statistic/intersect/raw_intersect/raw_intersect_base.py
> raw intersect temp fix

- python/fate_test/fate_test/_flow_client.py
> fix fate test

- python/federatedml/feature/imputer.py
> fix imputer

- python/requirements.txt
> fix requirements.txt

- python/federatedml/param/intersect_param.py
- python/federatedml/param/linear_regression_param.py
- python/federatedml/param/poisson_regression_param.py
- python/federatedml/param/sir_param.py
> temp fix deprecated param

- python/federatedml/param/logistic_regression_param.py
> remove deprecated param

- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-sample-weights.py
> fix sample weights case

- examples/dsl/v2/sample_weight/README.md
- examples/dsl/v2/sample_weight/sample_weight_name_job_conf.json
- examples/dsl/v2/sample_weight/sample_weight_name_job_dsl.json
- examples/dsl/v2/sample_weight/sample_weight_testsuite.json
- examples/pipeline/sample_weight/pipeline-sample-weight-name.py
> Feature 1.7 warm start linr

- examples/pipeline/homo_logistic_regression/pipeline-homo-lr-warm-start.py
- python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
- python/federatedml/linear_model/base_linear_model_arbiter.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_arbiter.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_guest.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
> fix binning & glm errors

- python/federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
- python/federatedml/ensemble/boosting/boosting_core/homo_boosting.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
> warm start bug fix

- python/fate_client/pipeline/param/hetero_sshe_lr_param.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
- python/federatedml/model_base.py
- python/federatedml/param/hetero_sshe_lr_param.py
- python/federatedml/protobuf/proto/lr-model-param.proto
- python/federatedml/secureprotol/fixedpoint.py
- python/federatedml/secureprotol/spdz/beaver_triples/he.py
- python/federatedml/secureprotol/spdz/secure_matrix/secure_matrix.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_endec.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
- python/federatedml/secureprotol/spdz/utils/__init__.py
- python/federatedml/secureprotol/spdz/utils/random_utils.py
- python/federatedml/secureprotol/spdz/utils/random_utils2.py
- python/federatedml/transfer_variable/transfer_class/sshe_model_transfer_variable.py
- python/federatedml/util/consts.py
> Feature 1.7 dylan sshe

- examples/min_test_task/run_task.py
- examples/toy_example/run_toy_example.py
- examples/toy_example/toy_example_conf_v2.json
Changes:
1. delete work_mode
2. get server changes
3.
> Feature 1.7 min test

- examples/dsl/v2/hetero_sshe_lr/hetero_lr_all_reveal_in_guest_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_compute_loss_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_compute_loss_not_reveal_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_cv_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_l1_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_normal_not_fit_intercept_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_l1_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_none_penalty_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_ovr_reveal_guest_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_with_validate_conf.json
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-all-reveal-in-guest.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-compute-loss-not-reveal.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-compute-loss.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-cv.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-l1.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal-not-fit-intercept.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-normal.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-l1.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-none-penalty.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr-reveal-guest.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-ovr.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-with-validate.py
- python/federatedml/nn/hetero_nn/test/paillier_tensor_test.py
- python/federatedml/nn/hetero_nn/test/random_number_generator_test.py
Changes:
1. fix example of sshe-lr
2.
3.
> fix error of sshe-lr examples

- examples/dsl/v2/hetero_logistic_regression/hetero_lr_ovr_validate_conf.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_validate_conf.json
> Feature 1.7 pipeline param fix

- python/fate_client/pipeline/param/feature_imputation_param.py
- python/federatedml/feature/feature_imputation.py
- python/federatedml/feature/imputer.py
- python/federatedml/param/feature_imputation_param.py
> edit feature imputation

- python/fate_client/flow_client/flow.py
- python/fate_client/flow_client/flow_cli/commands/test.py
- python/fate_client/flow_client/flow_cli/utils/cli_args.py
- python/fate_client/flow_sdk/client/__init__.py
- python/fate_client/flow_sdk/client/api/__init__.py
- python/fate_client/flow_sdk/client/api/test.py
1. flow sdk and flow cli support toy test
2.  flow sdk support setting appkey and secret for flow server
> 1. flow sdk and flow cli support toy test

- examples/min_test_task/run_task.py
Changes:
1.  Add host obtaining
2.
3.
> Add host obtaining

- python/federatedml/statistic/intersect/intersect_model.py
- python/federatedml/statistic/intersect/rsa_intersect/rsa_intersect_guest.py
> fix cardinality

- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_mq_channel.py
- python/fate_arch/federation/pulsar/_pulsar_manager.py
- python/fate_arch/federation/rabbitmq/_federation.py
Fixes  ISSUE #3291
Signed-off-by: dylanfan 289765648@qq.com
Changes:
1.
2.
3.
> avoid hang on consume on rabbitmq

- python/fate_test/fate_test/_config.py
- python/fate_test/fate_test/scripts/cli.py
- python/fate_test/fate_test/scripts/quick_test_cli.py
Changes:
1. add quick test
2.
3.
> add quick test

- doc/api/fate_test.md
- examples/benchmark_performance/README.md
- examples/dsl/v2/hetero_sshe_lr/README.md
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_warm_start_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
- examples/pipeline/hetero_sshe_lr/README.md
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-warm-start.py
> Feature 1.7 doc examples update

- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
> fix federation table as left table in using join op problem

- python/fate_test/fate_test/_flow_client.py
- python/fate_test/fate_test/_parser.py
Changes:
1. upload images update
2.
3.
> upload images

- python/fate_client/flow_client/flow_cli/commands/provider.py
> modify provider flow cli

- examples/scripts/query_schema.py
- examples/scripts/submit.py
- examples/scripts/upload_default_data.py
Changes:
1. command update
2.
3.
> Featur 1.7 example scripts

- python/fate_client/pipeline/param/intersect_param.py
- python/federatedml/param/intersect_param.py
- python/federatedml/statistic/intersect/intersect_model.py
> Feature 1.7 intersect cache fix

- python/fate_arch/federation/rabbitmq/_federation.py
Changes:
1. change rabbitmq union_name, policy_id generation
2.
3.
> fixed union_name

- .gitignore
- build/package-build/build.sh
> Feature-1.7.0-schduling

- .gitignore
- python/fate_client/flow_client/flow_cli/commands/job.py
- python/fate_client/flow_sdk/client/api/job.py
- python/fate_test/fate_test/flow_test/flow_cli_api.py
> ignore *.db*

- examples/benchmark_quality/hetero_fast_sbt/gbdt-binary.py
- examples/benchmark_quality/hetero_fast_sbt/gbdt-multi.py
- examples/benchmark_quality/hetero_fast_sbt/gbdt-regression.py
- examples/benchmark_quality/hetero_sbt/gbdt-binary.py
- examples/benchmark_quality/hetero_sbt/gbdt-multi.py
- examples/benchmark_quality/hetero_sbt/gbdt-regression.py
- examples/benchmark_quality/homo_sbt/gbdt-binary.py
- examples/benchmark_quality/homo_sbt/gbdt-multi.py
- examples/benchmark_quality/homo_sbt/gbdt-regression.py
> update sbt benchmark

- .gitpod.Dockerfile
- .gitpod.yml
add [gitpod](https://gitpod.io/projects) support
> add gitpod support

- examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_encrypted_not_reveal_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_encrypted_not_reveal_dsl.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_respectively_not_reveal_conf.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_converged_weight_diff_respectively_not_reveal_dsl.json
- examples/dsl/v2/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
- examples/min_test_task/run_task.py
- examples/pipeline/hetero_sshe_lr/hetero_sshe_lr_pipeline_testsuite.json
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-converged-weight-diff-encrypted-not-reveal.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-converged-weight-diff-respectively-not-reveal.py
- examples/scripts/upload_default_data.py
- python/federatedml/feature/binning/optimal_binning/optimal_binning.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
Changes:
1. fix optimal binning predict error
2. sshe lr does not callback loss when running ovr
3. add some examples of sshe-lr
> fix optimal binning predict error, add some test cases. 

- python/federatedml/param/base_param.py
- python/federatedml/secureprotol/spdz/utils/naming.py
Changes:
1. fix static param problem
2. not using bultin _md5, hashlib'md5 instead
3.
> Feature 1.7 fix static param and not using bultin md5

- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_base.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_sshe_logistic_regression/hetero_lr_host.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
Signed-off-by: dylan-fan 289765648@qq.com
Fixes ISSUE #xxx
Changes:
1. optim sshe-lr logs
2. fixed tensor bugs
3. align api interface for fixedpoint_numpy and fixedpoint_table
> optim sshe-lr and spdz/tensor

- examples/scripts/upload_default_data.py
> fix upload data problem

- examples/scripts/upload_default_data.py
> fix import error of uplodate_default_data scripts

- doc/api/computing.md
- doc/api/federation.md
- doc/api/session.md
Signed-off-by: WenbinWei <wbwmat@gmail.com>
> add comments

- build/docker-build/docker/modules/python/Dockerfile
> fix docker-build of python

- build/docker-build/docker/modules/python/Dockerfile
> fix fate_client install

- deploy/cluster-deploy/doc/fate_on_eggroll/Fate-allinone_deployment_guide_install.md
- deploy/cluster-deploy/doc/fate_on_eggroll/Fate-allinone_deployment_guide_install_zh.md
- deploy/cluster-deploy/doc/fate_on_eggroll/Fate-exchange_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_eggroll/Fate-exchange_deployment_guide_zh.md
Fixes  ISSUE #3377 
Changes:
1.update deploy doc
> Develop 1.7.0 deploy doc

- examples/dsl/v2/data_transform/README.md
- examples/dsl/v2/data_transform/data_transform_testsuite.json
- examples/dsl/v2/data_transform/test_data_transform_svmlight.json
- examples/dsl/v2/hetero_nn/README.md
- examples/dsl/v2/hetero_nn/hetero_nn_testsuite.json
- examples/pipeline/data_transform/README.md
- examples/pipeline/hetero_nn/README.md
- examples/pipeline/hetero_nn/hetero_nn_testsuite.json
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
- python/fate_client/pipeline/backend/pipeline.py
- python/federatedml/optim/gradient/test/gradient_method_test.py
Changes:
1.  fix pipiline predict process bug: which cannot get training component 's taskinfo instance
2. add an example in testsuite
3. fix gradient_method unittest
> fix pipiline predict process bug: which cannot get training component 's taskinfo instance

- python/fate_client/flow_client/flow_cli/commands/test.py
- python/fate_client/flow_client/flow_cli/utils/cli_args.py
- python/fate_client/flow_sdk/client/api/test.py
Changes:
1. flow client toy test support task-cores argument
2.
3.
> Feature-1.7.0-flow_client

- python/federatedml/callbacks/validation_strategy.py
> Feature 1.7 ovr validation fix

- build/docker-build/docker/base/Dockerfile
This is the association of https://github.com/FederatedAI/FATE-Flow/pull/127 PR, if that PR is merged, then this PR can be merged
> [fix] homo-deploy need import torch and tensorflow be fixed,

- deploy/cluster-deploy/doc/fate_on_spark/FATE_on_spark_local_zh.md
- deploy/cluster-deploy/doc/fate_on_spark/spark_access/spark_on_cluster_zh.md
- deploy/cluster-deploy/doc/fate_on_spark/spark_access/spark_on_local_zh.md
- deploy/cluster-deploy/upgrade/1_5_0-1_5_1/resource/requirements.txt
Signed-off-by: zhihuiwan 15779896112@163.com
Changes:
1.
2.
3.
> Feature 1.7 wzh doc update

- deploy/cluster-deploy/README.md
- deploy/cluster-deploy/README.zh.md
> change deploy index.md to README.md

- RELEASE.md
Signed-off-by: dylan-fan 289765648@qq.com
Changes:
1. add 1.7 release for fate_arch
2.
3.
> add release for 1.7.0

- deploy/standalone-deploy/README.zh.md
> fixed standalone doc bug

- .gitpod.Dockerfile
> slim gitpod image

- build/standalone-docker-build/Dockerfile
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
> Feature 1.7.0 schduling

- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/benchmark_quality/homo_lr/pipeline-lr-binary.py
- examples/dsl/v2/hetero_pearson/hetero_pearson_testsuite.json
- examples/dsl/v2/homo_nn/mnist_demo/upload.json
- examples/dsl/v2/upload/upload_conf.json
- examples/dsl/v2/upload/upload_tag_conf.json
- examples/pipeline/hetero_ftl/pipeline-hetero-ftl-communication-efficient.py
- examples/pipeline/hetero_ftl/pipeline-hetero-ftl-encrypted.py
- examples/pipeline/hetero_ftl/pipeline-hetero-ftl-plain.py
- examples/pipeline/hetero_pearson/hetero_pearson_testsuite.json
- examples/pipeline/intersect/pipeline-intersect-with-union.py
Signed-off-by:mgqa34 mgq3374541@163.com
Changes:
1. fix examples: delete work_mode/backend
2. fix examples: detelet outdated code annotation
3.
> Feature 1.7 fix examples

- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
> fix doc of standalone-deploy

- deploy/cluster-deploy/doc/fate_on_spark/fate-exchange_deployment_with_pulsar.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.md
Signed-off-by: zhihuiwan 15779896112@163.com
Changes:
1.
2.
3.
> update spark doc

- examples/experiment_template/dsl/v2/column_expand/column_expand_testsuite.json
Changes:
1. test suite update
2.
3.
> test-suite update

- doc/develop/develop_guide.md
- doc/develop/develop_guide.zh.md
Changes:
1. fix develop guide
2.
3.
> fix develop guide

- python/requirements.txt
> fix requests version

- RELEASE.md
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
Changes:
1. fix standalone deploy doc
2.
3.
> Fix Standalone deploy doc

- doc/federatedml_component/ensemble.md
> fix ensemble format

- build/package-build/build.md
- build/package-build/build.zh.md
> update build package doc

- doc/tutorial/fate_test_tutorial.md
> update fate_test doc

- doc/develop/develop_guide.md
- doc/develop/develop_guide.zh.md
Signed-off-by: gxcuit gxcuit@163.com
Fixes  ISSUE #3498 #3500
Changes: 
1. re-commit without changing the code
2. Update the develop doc. Add explanation about  ` __init__`  function when developing new model.
> update dev doc. Add __init__

- bin/common.sh
- bin/install_os_dependencies.sh
- build/package-build/build.sh
- build/standalone-docker-build/base/python/init.sh
- build/standalone-docker-build/build.sh
- build/standalone-docker-build/docker-entrypoint.sh
- build/standalone-install-build/build.sh
- build/standalone-install-build/init.sh
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.md
- deploy/standalone-deploy/doc/standalone_fate_source_code_deployment_guide.zh.md
Signed-off-by: jarviszeng.zjc@qq.com
Fixes  ISSUE #3492
Changes:
1. fix doc using bash instead of sh
2. improve sudo or root
3. improve install_os_dependencies.sh
> Fix bugs that using the standalone install in Ubuntu

- doc/federatedml_component/homo_framework.md
Signed-off-by: gxcuit <gxcuit@163.com>
Fixes  the path of pic in doc(homo_framework.md)
Changes:
1.
2.
3.
> update the path of pic in doc

- .github/workflows/autopep8-command.yml
- python/fate_arch/storage/_session.py
- python/fate_client/flow_client/flow_cli/utils/cli_utils.py
- python/fate_test/fate_test/flow_test/flow_cli_api.py
- python/fate_test/fate_test/flow_test/flow_sdk_api.py
- python/federatedml/evaluation/metric_interface.py
- python/federatedml/framework/weights.py
- python/federatedml/linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
Signed-off-by: tanmingchao <tanmingchao@sfmail.sf-express.com>
Fixes  ISSUE #3508
> fix homo_lr learning_rate decay bug

- python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
- python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
- python/federatedml/statistic/data_statistics.py
- python/federatedml/statistic/statics.py
Changes:
1. data statistics support missing value in Instance
2. enhance SIR security using system random generator 
3.
> Feature 1.8 statistics

- python/federatedml/statistic/statics.py
> edit stats

- python/federatedml/secureprotol/spdz/tensor/fixedpoint_endec.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
Signed-off-by: dylan-fan 289765648@qq.com
Changes:
1.
2.
3.
> fixed spdz default encoder bugs

- python/fate_test/fate_test/flow_test/flow_cli_api.py
- python/fate_test/fate_test/scripts/flow_test_cli.py
- python/fate_test/fate_test/scripts/generate_mock_data.py
> problem repair

- python/fate_arch/computing/eggroll/_table.py
- python/fate_arch/computing/spark/_table.py
- python/fate_arch/computing/standalone/_table.py
> add cache to `count`

- python/federatedml/secure_information_retrieval/base_secure_information_retrieval.py
- python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
- python/federatedml/statistic/data_statistics.py
- python/federatedml/statistic/statics.py
Fixes  ISSUE #3569 
Changes:
1. fix missing count & check np.none for missing value in Statistics 
2. SIR uses more secure system random number generator
3.
> edit stats & sir

- python/federatedml/param/encrypt_param.py
> add iterativeAffine auto reset

- examples/README.zh.md
> Fix example doc

- examples/flow_test_template/flow_test_config.yaml
- python/fate_test/fate_test/flow_test/flow_process.py
- python/fate_test/fate_test/scripts/flow_test_cli.py
> remove hardcode of online inference id test

- python/fate_arch/common/profile.py
add driver profile info, such as:
> [INFO] [2021-12-31 09:35:04,065] [202112310934351692330] [69017:139943064920448] - [profile.profile_ends] [line:280]: Total: 6.4635, Driver: 0.8811s(13.63%), Federation: 0.5433s(8.41%), Computing: 5.0391s(77.96%)
> add driver profile info

- python/fate_flow/manager/data_manager.py
> Fix sql injection

- python/fate_arch/_standalone.py
- python/fate_arch/abc/_computing.py
- python/fate_arch/computing/eggroll/_table.py
- python/fate_arch/computing/spark/_table.py
- python/fate_arch/computing/standalone/_table.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/secureprotol/spdz/tensor/fixedpoint_table.py
> fix sample api for standalone

- python/fate_arch/computing/eggroll/_table.py
> fix count cache bug

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/cross_entropy_test.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/regression_loss_test.py
Signed-off-by: gxcuit gxcuit@163.com
Fixes  ISSUE #3558
Changes:
1. Correct the path of loss.
2.
3.
> fix the wrong path of federatedml.loss in the test

- python/fate_flow/examples/test_inference.py
> Feature 1.6.2 fate test

- examples/benchmark_performance/hetero_lr/hetero_lr_testsuite.json
- examples/benchmark_performance/hetero_sbt/hetero_sbt_testsuite.json
- examples/benchmark_performance/hetero_sshe_lr/hetero_sshe_lr_testsuite.json
- examples/benchmark_performance/hetero_sshe_lr/test_hetero_sshe_lr_train_job_conf.json
- examples/benchmark_performance/intersect_multi/intersect_multi_testsuite.json
- examples/benchmark_performance/intersect_multi/test_intersect_multi_job_conf.json
- examples/benchmark_performance/intersect_single/intersect_single_testsuite.json
- examples/benchmark_performance/intersect_single/test_intersect_single_job_conf.json
- examples/flow_test_template/hetero_lr/flow_test_config.yaml
- examples/flow_test_template/homo_lr/flow_test_config.yaml
- python/fate_test/fate_test/flow_test/flow_process.py
- python/fate_test/fate_test/scripts/flow_test_cli.py
- python/fate_test/fate_test/scripts/generate_mock_data.py
Changes:
1. benchmark performance config update
2. generate data optimization
3.
> Deature 1.7.1 fate test

- python/federatedml/feature/feature_selection/selection_properties.py
Fixes  ISSUE #3608 
Changes:
1.
2.
3.
> edit selection

- python/federatedml/cipher_compressor/compressor.py
> remove log

- python/fate_client/flow_client/flow_cli/commands/test.py
- python/fate_client/flow_sdk/client/api/test.py
> improve toy test

- examples/benchmark_performance/README.md
> Adding a Timeout Setting

- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
Signed-off-by: gxcuit <gxcuit@163.com>
Fixes  ISSUE #3596 
Changes:
1.Detailed explanation can be found in ISSUE #3596 
2.
3.
> fix compute `wxg_wxh` of Guest's loss in `hetero lr`

- doc/api/fate_client/pipeline.md
- examples/README.zh.md
> Merge master in to develop-1.7.1

- build/docker-build/docker/modules/eggroll/Dockerfile
- build/docker-build/docker/modules/python/Dockerfile
- Fix some path of Python container.
- Cancel the installation of fate_client in Python container.
> docker-build fix for v1.7

- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_host.py
> Feature 1.7.1 predict inplace fix

- python/fate_arch/storage/hdfs/_table.py
> Feature 1.7.1 fate flow

- python/fate_client/pipeline/param/encrypt_param.py
> remove iterativeAffine support in FATE-1.7.1

- .gitmodules
> update gitmodule file and commit of submodule

- examples/dsl/v1/hetero_secureboost/README.md
- examples/dsl/v2/hetero_secureboost/README.md
- python/federatedml/ensemble/README.rst
- python/federatedml/ensemble/boosting/boosting_core/hetero_boosting.py
> update param and conf/dsl and doc

- examples/experiment_template/user_usage/pipeline_predict_tutorial.md
> update doc of pipeline_predict_tutorial

- python/federatedml/statistic/intersect/base_intersect.py
- python/federatedml/statistic/intersect/dh_intersect/dh_intersect_base.py
- python/federatedml/statistic/intersect/dh_intersect/dh_intersect_guest.py
- python/federatedml/statistic/intersect/dh_intersect/dh_intersect_host.py
Changes:
1. faster DH intersect
2.
3.
> edit dh intersect

- python/fate_arch/_standalone.py
- python/fate_arch/computing/standalone/_csession.py
- python/fate_arch/session/_session.py
add `task_cores` for standalone
this fix #3503
> add task_cores to standalone mode

- python/federatedml/ensemble/secureboost/secureboost_util/boosting_tree_predict.py
> Feature 1.8 secureboost update

- .gitignore
Changes: 
1.  recovery gitmodule of fateflow & fateboard
> recover submodule of fateflow & fateboard

- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
> sbt bug fix

- python/federatedml/secureprotol/spdz/spdz.py
Signed-off-by: dylan-fan 289765648@qq.com
Fixes  ISSUE #3687
Changes:
1.
2.
3.
> fixed default q_filed for spdz

- python/fate_client/pipeline/param/logistic_regression_param.py
- python/federatedml/framework/hetero/procedure/batch_generator.py
- python/federatedml/linear_model/linear_model_base.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/model_selection/indices.py
- python/federatedml/model_selection/mini_batch.py
- python/federatedml/optim/gradient/hetero_linear_model_gradient.py
- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
- python/federatedml/param/logistic_regression_param.py
- python/federatedml/util/data_transform.py
Fixes  ISSUE #3691 
Changes:
1. Use batch masked strategy and batch shuffle strategy to enhance hetero logistic regression
2.
3.
> Feature 1.7.2 lr

- python/federatedml/optim/gradient/hetero_sqn_gradient.py
Changes:
1. fix error of sqn gradient computing function's parameters passing
2.
3.
> fix sqn compute gradient parameter

- examples/dsl/v2/hetero_fast_secureboost/test_fast_sbt_mix_multiclass_conf.json
- python/fate_client/pipeline/param/__init__.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_fast_secureboost_host.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_guest.py
- python/federatedml/ensemble/boosting/hetero/hetero_secureboost_host.py
> Feature 1.7.2 eini inference

- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/model_selection/mini_batch.py
- python/federatedml/optim/gradient/hetero_linear_model_gradient.py
- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
Changes:
1. fix bug of  lr-batch and optimize code logic
2.
3.
> optimize mini batch generator logic and hetero-lr batch logic

- python/fate_client/pipeline/param/hetero_nn_param.py
- python/federatedml/param/encrypted_mode_calculation_param.py
- python/federatedml/param/hetero_nn_param.py
- python/federatedml/secureprotol/encrypt_mode.py
Changes:
1. enhance encryot_mode tool
2.
3.
> enhance encrypt_mode tool

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
> fix board display of fast-sbt host

- python/fate_arch/common/address.py
- python/fate_arch/storage/mysql/_table.py
- python/fate_client/flow_client/flow_cli/commands/table.py
> Feature 1.7.2 fate flow

- python/fate_client/pipeline/component/__init__.py
- python/fate_client/pipeline/component/nn/backend/keras/model_builder.py
- python/fate_client/pipeline/component/nn/backend/pytorch/model_builder.py
- python/fate_client/pipeline/component/nn/models/sequantial.py
- python/fate_client/pyproject.toml
- python/fate_client/setup.py
Changes:
1. remove tensorflow and torch dependencies of fate-client
2.
3.
> remove tensorflow-keras and pytorch dependencies of fate-client

- DISCLAIMER
> add disclaimer

- .gitmodules
- examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/dsl/v2/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_batch_random_strategy_conf.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_batch_random_strategy_dsl.json
- examples/dsl/v2/hetero_sshe_lr/hetero_lr_warm_start_conf.json
- examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_pipeline_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-batch-random-strategy.py
- examples/pipeline/hetero_sshe_lr/pipeline-hetero-lr-warm-start.py
- python/fate_client/pipeline/param/hetero_sshe_lr_param.py
- python/federatedml/feature/homo_feature_binning/homo_binning_base.py
- python/federatedml/param/hetero_sshe_lr_param.py
Changes:
1. add examples of hetero-lr: batch_random strategy
> update examples of hetero-lr,

- examples/benchmark_performance/hetero_lr/test_hetero_lr_train_job_dsl.json
- examples/benchmark_performance/hetero_sbt/test_hetero_secureboost_train_job_dsl.json
Signed off by: dylan-fan <289765648@qq.com>
Changes:
1.
2.
3.
> fixed benchmarck_performance training dsl

- .gitmodules
Changes:
1. update gitmodule
2.
3.
> update gitmodule and submodule-ref of fateboard-v1.7.2.2, fateflow-1.7.2

- python/fate_arch/common/address.py
> fix bug: circular reference

- examples/benchmark_quality/hetero_lr/pipeline-lr-binary.py
- examples/benchmark_quality/hetero_lr/pipeline-lr-multi.py
- examples/dsl/v2/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_batch_random_strategy_conf.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_batch_random_strategy_dsl.json
- examples/pipeline/hetero_logistic_regression/hetero_logistic_regression_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-batch-random-strategy.py
- python/federatedml/optim/gradient/hetero_linear_model_gradient.py
- python/federatedml/optim/gradient/hetero_lr_gradient_and_loss.py
Changes:
1. add examples
2. fix gradient average bug
3.
> update examples, fix bug, #3691

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_fast_decision_tree_host.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
- python/federatedml/ensemble/secureboost/secureboost_util/boosting_tree_predict.py
Merge EINI into branch 1.8 #3707
> update EINI content #3707

- python/federatedml/ensemble/secureboost/secureboost_util/boosting_tree_predict.py
solve #3702 , add int type optimization in SBT inference stage
> optimize int size in sbt predict transfer #3702

- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_host.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
- python/federatedml/ensemble/secureboost/secureboost_util/boosting_tree_predict.py
- python/federatedml/evaluation/evaluation.py
> fix predict codes

- python/federatedml/feature/binning/quantile_summaries.py
Fixes  ISSUE #3765 
Changes:
1. fix homo-binning
2.
3.
> fix quantile summary using in homo binning

- examples/dsl/v2/hetero_sshe_linr/hetero_linr_validate_conf.json
Fixes  ISSUE #3766 
Changes:
1.
2.
3.
> Feature 1.8 sshe glm update

- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
> update feature importance sync

- python/fate_arch/metastore/db_models.py
- python/fate_arch/storage/__init__.py
- python/fate_arch/storage/_session.py
- python/fate_arch/storage/_table.py
- python/fate_arch/storage/_types.py
> data origin

- python/federatedml/param/logistic_regression_param.py
> fix lr param

- examples/dsl/v2/hetero_ftl/test_ftl_encrypted_conf.json
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
> 1.8 update

- .gitmodules
Changes:
1. update gitmodule of fate-v1.8, for first-round testing
2.
3.
> update gitmodule of fate

- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
> update model name

- build/package-build/build.sh
Signed-off-by: Jat <jat@sinosky.org>
> add npm when building fateboard

- doc/mkdocs/requirements.txt
- python/federatedml/param/boosting_param.py
fix readthedocs 
this fix #3786
> fix mkdocs (#3786)

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/param/boosting_param.py
> add param check

- python/fate_arch/abc/_storage.py
- python/fate_arch/metastore/db_models.py
- python/fate_arch/session/_session.py
- python/fate_arch/storage/_table.py
- python/fate_client/flow_client/flow_cli/commands/table.py
> disable table can't to be used

- python/federatedml/secureprotol/spdz/communicator/federation.py
- python/federatedml/secureprotol/spdz/spdz.py
- python/federatedml/transfer_variable/transfer_class/secret_share_transfer_variable.py
Fixes  ISSUE #3823 
Changes:
1. fixed spdz bugs
2. add q_field align
3.
> fixed spdz bugs. add qield align

- python/federatedml/feature/hetero_feature_selection/base_feature_selection.py
- python/federatedml/transfer_variable/transfer_class/hetero_feature_selection_transfer_variable.py
Fixes  ISSUE #3805
Changes:
1. fix Hetero feature selection 
2.
3.
> Feature 1.8 Fix Hetero Feature Selection

- python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_model.py
- python/federatedml/linear_model/coordinated_linear_model/linear_regression/base_linear_regression.py
- python/federatedml/linear_model/coordinated_linear_model/linear_regression/hetero_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/coordinated_linear_model/linear_regression/hetero_linear_regression/hetero_linr_host.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/linear_model/coordinated_linear_model/poisson_regression/base_poisson_regression.py
- python/federatedml/linear_model/coordinated_linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_guest.py
- python/federatedml/linear_model/coordinated_linear_model/poisson_regression/hetero_poisson_regression/hetero_poisson_host.py
- python/federatedml/linear_model/linear_model_base.py
- python/federatedml/nn/hetero_nn/model/interactive_layer.py
- python/federatedml/optim/gradient/hetero_linear_model_gradient.py
- python/federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
- python/federatedml/optim/gradient/hetero_sqn_gradient.py
- python/federatedml/secureprotol/paillier_tensor.py
- python/federatedml/transfer_learning/hetero_ftl/ftl_base.py
Changes:
1.  clean code of deleting encrypted_mode_calculator
2.
3.
> clean code of using encrypted_mode_calculator

- examples/data/upload_config/all_examples_data_testsuite.json
- examples/data/upload_config/min_test_data_testsuite.json
- python/fate_test/fate_test/_config.py
- python/fate_test/fate_test/_flow_client.py
- python/fate_test/fate_test/_parser.py
- python/fate_test/fate_test/fate_test_config.yaml
- python/fate_test/fate_test/scripts/cli.py
- python/fate_test/fate_test/scripts/data_cli.py
- python/fate_test/fate_test/scripts/op_test/fate_he_performance_test.py
- python/fate_test/fate_test/scripts/op_test/performance_assess.py
- python/fate_test/fate_test/scripts/op_test/spdz_conf/job_conf.json
- python/fate_test/fate_test/scripts/op_test/spdz_conf/job_dsl.json
- python/fate_test/fate_test/scripts/op_test/spdz_test.py
- python/fate_test/fate_test/scripts/pipeline_conversion_cli.py
- python/fate_test/fate_test/scripts/secure_protocol_cli.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
- python/fate_test/fate_test/utils.py
- python/federatedml/components/spdz_test_cpn.py
- python/federatedml/test/spdz_test/spdz_test.py
- python/federatedml/test/spdz_test/spdz_test_param.py
Fixes  ISSUE #3780 #3781 #3782 
Changes:
1. Provide tools like pipeline to dsl, upload data, download mnist etc
2. Support paillier and spdz operations testing
3. Optimize prinout
> update fate-test 1.8, fixed #3780, #3781, #3782

- python/fate_client/pipeline/param/boosting_param.py
- python/federatedml/cipher_compressor/packer.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/hetero/hetero_decision_tree_guest.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/g_h_optim.py
- python/federatedml/ensemble/boosting/hetero_boosting.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/secureboost_util/tree_model_io.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- python/federatedml/param/boosting_param.py
- python/federatedml/secureprotol/encrypt.py
remove encrypt calculator in FATE-1.8
> Feature 1.8 remove sbt encrypt calculator

- python/federatedml/feature/binning/quantile_summaries.py
Changes:
1. fix batch query problem in sparse quantile summary
2.
3.
> fix sparse quantile summary's query interface

- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
> Feature 1.8 fix fast sbt pipeline

- .github/workflows/docker_push.yaml
- build/docker-build/build_cluster_docker.sh
Signed-off-by: owlet42 <owlet42@126.com>
- update docker build to support v1.8
- fix workflow of docker push
> update docker build for v1.8

- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md
Changes:
1. upload allInOne deployment doc's data upload logic
2.
3.
> edit upload data logic of allInOne deploy doc

- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/pulsar/_mq_channel.py
- python/fate_arch/federation/rabbitmq/_mq_channel.py
Changes:
1. rabbitmq MqChanel connection_retry raise exception when timeout
2. pular MqChanel connection_retry raise exception when timeout
3. remove 'continue' operation for receive_obj in pulsar
> optim federation and raise exception

- .flake8
- doc/mkdocs/requirements.txt
- python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_guest.py
- python/federatedml/linear_model/bilateral_linear_model/hetero_sshe_linear_regression/hetero_linr_host.py
- python/federatedml/protobuf/generated/poisson_model_meta_pb2.py
- python/federatedml/statistic/statics.py
Changes:
1. fix requirements
2. fix autopep8
> fix checks

- doc/federatedml_component/intersect.md
Fixes  ISSUE #3766
Changes:
1. include DH intersection illustrations contributed in #3881 
2.
3.
> edit doc (#3766)

- build/standalone-docker-build/docker-entrypoint.sh
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
Signed-off-by: Jat <jat@sinosky.org>
> update docker deploy doc

- python/fate_arch/session/_session.py
Changes:
1. add return for commpute_session stop api.
2.
3.
> add return for commpute_session stop api.

- RELEASE.md
Changes:
1. update release note of fate-v1.8
2.
3.
> update release note of fate-v1.8

- python/fate_arch/common/file_utils.py
> fix mkdocs issue (#3910)

- doc/federatedml_component/secureprotol.md
- examples/benchmark_quality/homo_lr/homo_lr_sklearn_benchmark.json
- examples/benchmark_quality/homo_lr/pipeline-lr-multi.py
- examples/benchmark_quality/homo_lr/sklearn-lr-multi.py
- examples/benchmark_quality/homo_lr/vehicle_lr_config.yaml
- examples/dsl/v2/homo_logistic_regression/README.md
- examples/dsl/v2/homo_logistic_regression/homo_logistic_regression_testsuite.json
- examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_conf.json
- examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_dsl.json
- examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_conf.json
- examples/dsl/v2/homo_logistic_regression/homo_lr_one_vs_all_encrypted_host_dsl.json
- examples/pipeline/homo_logistic_regression/README.md
- examples/pipeline/homo_logistic_regression/homo_logistic_regression_pipeline_testsuite.json
- examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all-encrypted-host.py
- examples/pipeline/homo_logistic_regression/pipeline-homo-lr-one-vs-all.py
- python/federatedml/ensemble/test/gh_packing_compressing_test.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_arbiter.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_base.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/homo_logistic_regression/homo_lr_host.py
- python/federatedml/secureprotol/__init__.py
- python/federatedml/secureprotol/encrypt.py
Fixes  ISSUE #3402 #3766 
Changes:
1. update multi-class dsl examples for homo-lr
2. update multi-class benchmark-quality example for homo-lr
3. not callback loss when running ovr task in homo-lr
> add multi-class dsl examples for homo-logistic-regression

- python/fate_arch/storage/hdfs/_table.py
- python/fate_arch/storage/localfs/_table.py
> Feature 1.8.0 fate arch

- examples/data/README.md
- python/fate_test/fate_test/scripts/performance_cli.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
Signed-off-by: Zhang Hui <zhang_hui0019@163.com>
fix some doc
> fix some doc

- python/fate_arch/common/conf_utils.py
@zhihuiwan 
修改文件：
python/fate_arch/common/conf_utils.py
修改内容：
增强get_base_config函数能力，支持一次查询service_conf.conf文件所有配置内容
> conf_utils optimization

- deploy/upgrade/sql/1.6.0-1.6.1.sql
- deploy/upgrade/sql/1.6.1-1.7.0.sql
- deploy/upgrade/sql/1.7.0-1.7.1.sql
- deploy/upgrade/sql/1.7.1-1.7.2.sql
- deploy/upgrade/sql/1.7.2-1.8.0.sql
- python/fate_arch/metastore/base_model.py
change `JSONField` for backward compatibility
> add upgrade sql

- doc/federatedml_component/secureprotol.md
- python/federatedml/secureprotol/spdz/test/guest.py
- python/federatedml/secureprotol/spdz/test/host.py
Signed-off-by: magic-hya <huangya@asiainfo.com>
Fixes  ISSUE #4000 
Changes:
1.update spdz part in secureprotol.md
2.add spdz example code guest.py and host.py
> update SPDZ document and example code

- python/fate_arch/federation/_federation.py
Fixes  ISSUE #3866 
Changes:
1. optim _receive_obj func memory
2.
3.
> optim _receive_obj func memory for federation (#3866)

- examples/dsl/v2/feature_imputation/feature_imputation_method_job_dsl.json
- examples/dsl/v2/feature_imputation/feature_imputation_testsuite.json
- examples/dsl/v2/label_transform/README.md
- examples/dsl/v2/label_transform/label_transform_encoder_wo_label_list_conf.json
- examples/dsl/v2/label_transform/label_transform_testsuite.json
- examples/pipeline/feature_imputation/pipeline-feature-imputation-method.py
- examples/pipeline/label_transform/README.md
- examples/pipeline/label_transform/pipeline-label-transform-encoder-wo-label-list.py
- python/fate_client/pipeline/param/feature_imputation_param.py
- python/fate_client/pipeline/param/label_transform_param.py
- python/federatedml/feature/fate_element_type.py
- python/federatedml/feature/feature_imputation.py
- python/federatedml/feature/imputer.py
- python/federatedml/model_selection/data_split/data_split.py
- python/federatedml/model_selection/data_split/hetero_data_split.py
- python/federatedml/model_selection/data_split/homo_data_split.py
- python/federatedml/param/feature_imputation_param.py
- python/federatedml/param/label_transform_param.py
- python/federatedml/util/label_transform.py
Fixes  ISSUE #3958 #3961 #3932 #4047
Changes:
1.
2.
3.
> Feature 1.9 data split display

- .github/workflows/build_wheel.yml
- rust/fate_crypto/README.md
- rust/fate_crypto/pyproject.toml
- rust/fate_crypto/tests/test_psi_bench.py
> fix maturin build path

- python/fate_arch/federation/_federation.py
Fixes  ISSUE #3866 
Changes:
1.
2.
3.
> fixed bug for optim _receive_obj func memory for federation (#3866)

- python/federatedml/param/callback_param.py
- python/federatedml/param/column_expand_param.py
- python/federatedml/param/feldman_verifiable_sum_param.py
- python/federatedml/param/homo_onehot_encoder_param.py
- python/federatedml/param/pearson_param.py
- python/federatedml/param/sir_param.py
- python/federatedml/param/statistics_param.py
> fix parameter init problem, #4032

- python/federatedml/feature/feature_selection/correlation_filter.py
Fixes  ISSUE #3936
Changes:
1.
2.
3.
> fix correlation filter (#3936)

- conf/service_conf.yaml
- python/fate_arch/federation/_federation.py
- python/fate_arch/federation/pulsar/_federation.py
- python/fate_arch/federation/rabbitmq/_federation.py
> add max_message_size conf in service conf (#3866)

- python/federatedml/nn/hetero_nn/backend/hetero_nn_model.py
- python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
- python/federatedml/nn/hetero_nn/model/interactive_layer.py
- python/federatedml/secureprotol/paillier_tensor.py
> fix selective back propagation of hetero_nn, issue #4007

- python/federatedml/statistic/correlation/hetero_pearson.py
> fix: correct summary["num_local_features"]

- python/federatedml/model_selection/data_split/data_split.py
- python/federatedml/model_selection/data_split/hetero_data_split.py
- python/federatedml/model_selection/data_split/homo_data_split.py
> edit data split 

- python/federatedml/feature/binning/bin_inner_param.py
- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
- python/federatedml/feature/one_hot_encoder.py
- python/federatedml/model_base.py
- python/federatedml/param/data_transform_param.py
- python/federatedml/protobuf/generated/data_transform_param_pb2.py
- python/federatedml/protobuf/model_migrate/converter/binning_model_converter.py
- python/federatedml/protobuf/model_migrate/converter/converter_base.py
- python/federatedml/protobuf/model_migrate/converter/data_transform_converter.py
- python/federatedml/protobuf/model_migrate/converter/pearson_model_converter.py
- python/federatedml/protobuf/model_migrate/converter_factory.py
- python/federatedml/protobuf/proto/data-transform-param.proto
- python/federatedml/statistic/data_overview.py
- python/federatedml/util/anonymous_generator_util.py
- python/federatedml/util/data_format_preprocess.py
- python/federatedml/util/data_transform.py
- python/federatedml/util/test/anonymous_generator_test.py
Fixes  ISSUE #3860 #4097 
Changes:
1. add anonymous generation util
2. modify model migration of  pearson\binning\data_transform
3.
> Feature 1.9.0 anonymous header

- rust/fate_crypto/fate_crypto/psi/__init__.pyi
- rust/fate_crypto/src/psi/curve25519.rs
> feat: Curve25519 supports none args (#3859)

- python/federatedml/ensemble/boosting/homo_boosting.py
> Feature 1.9.0 homo sbt init fix

- python/federatedml/feature/binning/optimal_binning/optimal_binning.py
Fixes  ISSUE #3860 
Changes:
1. fix bug in anonymous header using of optimal binning
2.
3.
> fix optimal binning anonymous header using

- python/federatedml/feature/homo_onehot/homo_ohe_arbiter.py
- python/federatedml/feature/homo_onehot/homo_ohe_base.py
Changes:
1. fix homo-onehot 
2.
3.
> fix homo onehot

- python/federatedml/util/data_io.py
Fixes  ISSUE #4116 
Changes:
1. disable dataio's using
2.
3.
> disabled dataio, #4116

- python/federatedml/ensemble/boosting/boosting.py
- python/federatedml/ensemble/boosting/hetero_boosting.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
- python/federatedml/feature/feature_selection/model_adapter/tree_adapter.py
- python/federatedml/nn/hetero_nn/model/hetero_nn_model.py
> Feature 1.9.0 nn sbt bug fix

- python/fate_client/pipeline/__init__.py
> fix fate client import

- examples/dsl/v2/hetero_logistic_regression/hetero_lr_one_vs_all_conf.json
- examples/dsl/v2/hetero_logistic_regression/hetero_lr_ovr_validate_conf.json
- examples/dsl/v2/intersect/README.md
- examples/dsl/v2/intersect/test_intersect_job_ecdh_cache_loader_conf.json
- examples/dsl/v2/label_transform/README.md
- examples/dsl/v2/label_transform/label_transform_encoder_partial_conf.json
- examples/dsl/v2/label_transform/label_transform_testsuite.json
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-early-stop.py
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-ovr-validate.py
- examples/pipeline/hetero_logistic_regression/pipeline-hetero-lr-validate.py
- examples/pipeline/intersect/README.md
- examples/pipeline/intersect/pipeline-intersect-ecdh-cache-loader.py
- examples/pipeline/label_transform/README.md
- examples/pipeline/label_transform/label_transform_testsuite.json
- examples/pipeline/label_transform/pipeline-label-transform-encoder-partial.py
- python/federatedml/model_base.py
- python/federatedml/one_vs_rest/one_vs_rest.py
Fixes  ISSUE #4081
Changes:
1.
2.
3.
> edit examples(#4081)

- python/federatedml/util/abnormal_detection.py
- python/federatedml/util/data_transform.py
Fixes  ISSUE #3860 
Changes:
1. compatiblity for training data_transform in older version, but predict in v1.9
2.
3.
> compatiblity for training data_transform in older version, but predict in v1.9

- python/federatedml/nn/hetero_nn/protection_enhance/coae.py
> fix ce loss

- python/federatedml/nn/hetero_nn/backend/pytorch/pytorch_nn_model.py
- python/federatedml/nn/hetero_nn/model/hetero_nn_top_model.py
- python/federatedml/nn/hetero_nn/protection_enhance/coae.py
fix bug in selective bp when using torch backend
> Feature 1.9.0 nn fix

- python/fate_arch/relation_ship.py
- python/fate_arch/session/_session.py
- python/fate_arch/tests/test_arch_api.py
> add __del__ for session

- python/fate_client/flow_client/flow.py
- python/fate_client/flow_client/flow_cli/commands/key.py
- python/fate_client/flow_client/flow_cli/commands/privilege.py
- python/fate_client/flow_client/flow_cli/utils/cli_args.py
> Feature 1.9.0 fate flow provider

- python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
> fix bias update

- python/federatedml/evaluation/evaluation.py
- python/federatedml/model_base.py
- python/federatedml/statistic/data_overview.py
- python/federatedml/util/label_transform.py
Fixes  ISSUE #4154
Changes:
1.
2.
3.
> replace predict detail type(#4154)

- conf/service_conf.yaml
- python/fate_arch/common/conf_utils.py
- python/fate_arch/metastore/base_model.py
- python/fate_client/flow_client/flow.py
- python/federatedml/model_base.py
Signed-off-by: Jat <jat@sinosky.org>
Changes:
1.
2.
3.
> auto add f_create_time

- python/federatedml/statistic/intersect/intersect_model.py
Fixes  ISSUE #4143
Changes:
1. modify output entry content type of Intersect with left_join mode
2.
3.
> Feature 1.9 intersect update

- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
Changes:
1. fix binning transform stage iv calculation problem
2.
3.
> Feature 1.9.0 test round1 bug fix

- python/federatedml/statistic/correlation/hetero_pearson.py
> fix: support nan output

- python/fate_client/pipeline/component/nn/backend/fate_torch/base.py
- python/fate_client/pipeline/component/nn/backend/fate_torch/serialization.py
- python/fate_client/pipeline/param/hetero_nn_param.py
- python/federatedml/nn/backend/fate_torch/base.py
- python/federatedml/nn/backend/fate_torch/serialization.py
- python/federatedml/nn/hetero_nn/model/hetero_nn_model.py
- python/federatedml/nn/hetero_nn/model/interactive_layer.py
- python/federatedml/param/hetero_nn_param.py
> fix nn warm start bugs

- python/federatedml/util/data_format_preprocess.py
- python/federatedml/util/data_transform.py
Changes:
1. fix anonymous header using with match_ids in svmlight\tag input format
> fix anonymous when using tag&svmlight data format

- examples/dsl/v2/intersect/test_intersect_job_raw_sm3_conf.json
- examples/pipeline/intersect/pipeline-intersect-raw-sm3.py
- python/federatedml/secureprotol/hash/hash_factory.py
Signed-off-by: nemirorox <yolandawu131@gmail.com
Fixes  ISSUE #4180
Changes:
1. fix issue
2. edit examples
3.
> fix sm3 base64(#4180)

- python/fate_client/setup.py
> fix import

- python/federatedml/util/anonymous_generator_util.py
Changes:
1. add get role and party_id from anonymous
2.
3.
> support get role and party_id from anonymous column

- python/federatedml/util/data_io.py
- python/federatedml/util/data_transform.py
Changes:
1. add compatibility in dataio transformation stage
2.
3.
> add compatibility for dataio transformation

- python/federatedml/util/data_format_preprocess.py
Changes:
1. add clean header interface in data format preprocess to support intersection  "only_output_keys"
> add clean header interface in data format preprocess

- python/federatedml/components/column_expand.py
- python/federatedml/feature/column_expand.py
- python/federatedml/statistic/intersect/intersect_model.py
Fixes  ISSUE #3860
Changes:
1.
2.
3.
> edit column expand(#3860)

- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
fix model migrate & anonymous problem
> Feature 1.9 sbt anonymous migrate fix

- python/federatedml/ensemble/boosting/boosting.py
- python/federatedml/ensemble/boosting/hetero_boosting.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_guest.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
fix feature-importance / model migrate
> fix load feature importance

- python/federatedml/model_selection/data_split/data_split.py
- python/federatedml/model_selection/stepwise/step.py
- python/federatedml/model_selection/stepwise/test/stepwise_test.py
> remove dataio import

- python/federatedml/util/data_transform.py
Changes:
1. fix data_transform exclusive data type and need_run=False parsing model error
2.
3.
> fix data_transform exclusive data type and need_run=False parsing model error

- python/federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_client.py
- python/federatedml/evaluation/metrics/classification_metric.py
> homo sbt sklearn update

- python/federatedml/evaluation/metrics/classification_metric.py
- python/federatedml/nn/homo_nn/_torch.py
1. add support for Python 3.7 - 3.9
2. bumps some dependencies version
> chore: upgrade python version and dependencies

- python/federatedml/__init__.py
- python/federatedml/ensemble/secureboost/hetero_secoreboost/hetero_secureboost_host.py
- python/federatedml/feature/feature_selection/model_adapter/tree_adapter.py
- python/federatedml/util/consts.py
fix error in sbt feature selection
> warm start header alignment

- .gitmodules
> update submodule of fate-1.9.0

- python/federatedml/util/anonymous_generator_util.py
- python/federatedml/util/data_io.py
- python/federatedml/util/data_transform.py
Changes:
1. fix data_io predicting does not return data
2. add compatible old anonymous header generate interface for selection
3. optimize data_transform
> Feature 1.9.0 test round2 bug fix

- build/package-build/build.sh
Signed-off-by: ArvinHuang <1095369685@qq.com>
Changes:
1.  NPM download has been added to Maven's package command while v1.9.0
> Front-end dependent duplicate installation

- python/federatedml/feature/binning/bin_result.py
- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/transfer_variable/transfer_class/hetero_feature_binning_transfer_variable.py
- python/federatedml/util/anonymous_generator_util.py
Changes:
1.  binning: update anonymous header when migrate from lower version to fate-v1.9.0
2.
3.
> binning: update anonymous header when migrate from lower version to fate-v1.9.0

- python/federatedml/feature/feature_selection/filter_factory.py
> Feature 1.9.0 sbt selection fix

- python/fate_arch/storage/hdfs/_table.py
> update hdfs path to file_path

- python/federatedml/nn/backend/tf_keras/nn_model.py
- python/federatedml/nn/hetero_nn/backend/tf_keras/interactive/dense_model.py
- python/federatedml/nn/homo_nn/_torch.py
this commit rewrite nn with tensorflow 2.x api,
which has better supports and post compatibility.
> refactor: upgrade tensorflow to 2.x

- python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py
Changes:
1. fix homo binning transform data 
2.
3.
> fix homo_binning_transform

- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-EINI-with-random-mask.py
- examples/pipeline/hetero_sbt/pipeline-hetero-sbt-binary-with-predict.py
- python/fate_client/pipeline/utils/invoker/job_submitter.py
Changes:
1. fix pipeline get predict output data interface
2. fix secureboost examples
3.
> fix pipeline get predict data and fix secureboost example

- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
Changes:
1. fix homo binning saving problem.
2.
3.
> fix homo feature binning arbiter model saving

- python/requirements.txt
> update pulsar client version

- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multiclass-multihost-woe.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-multiclass.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-bucket-binning.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-chi-square.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-gini.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-iv.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-optimal-ks.py
- examples/pipeline/hetero_feature_binning/pipeline-hetero-binning-sparse-quantile-binning.py
Changes:
1. fix hetero feature binning pipeline examples
> fix feature binning examples

- python/fate_client/pipeline/backend/pipeline.py
- python/fate_client/pipeline/utils/invoker/job_submitter.py
Fixes  ISSUE #4240
Changes:
1. edit pipeline job submitter & backend
2.
3.
> edit pipeline(#4240)

- python/federatedml/statistic/scorecard/score_transformer.py
- python/federatedml/unsupervised_learning/kmeans/kmeans_model_base.py
- python/federatedml/util/abnormal_detection.py
> edit schema check

- python/federatedml/nn/backend/tf_keras/nn_model.py
> fix: fix nn loss fn

- .gitignore
- conf/service_conf.yaml
- python/fate_arch/metastore/db_models.py
- python/fate_client/flow_client/flow.py
- python/fate_client/flow_client/flow_cli/commands/job.py
- python/fate_client/flow_client/flow_cli/utils/cli_utils.py
- python/fate_client/setup.py
- python/fate_test/fate_test/flow_test/flow_cli_api.py
- python/fate_test/fate_test/flow_test/flow_rest_api.py
- python/fate_test/fate_test/flow_test/flow_sdk_api.py
- python/requirements.txt
1. fix fate_test
2. remove flask on fate_client
> fix fate_test

- python/fate_arch/abc/_computing.py
- python/fate_arch/computing/eggroll/_csession.py
- python/fate_arch/computing/spark/_csession.py
- python/fate_arch/computing/standalone/_csession.py
- python/fate_arch/federation/eggroll/_federation.py
- python/fate_arch/session/_session.py
Changes:
1. add federation destroy for eggroll
2. remove cleanup func for session
3.
> remove cleanup func in session

- python/federatedml/secureprotol/spdz/tensor/fixedpoint_numpy.py
- python/federatedml/statistic/correlation/hetero_pearson.py
> chore: add/remove logger

- python/federatedml/statistic/correlation/hetero_pearson.py
> feat: use faster eigval version

- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_manually_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_one_hot_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_pearson_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_union_job_dsl.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_conf.json
- examples/experiment_template/dsl/v2/hetero_secureboost/test_hetero_secureboost_train_verify_job_dsl.json
- examples/experiment_template/pipeline/hetero_lr/hetero_lr_testsuite.json
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_lr.py
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_manually_lr.py
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_pearson_lr.py
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_sample_lr.py
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_test_lr.py
- examples/experiment_template/pipeline/hetero_lr/pipeline_train_union_lr.py
- examples/experiment_template/pipeline/hetero_secureboost/hetero_sbt_testsuite.json
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_manually_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_one_hot_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_pearson_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_test_sbt.py
- examples/experiment_template/pipeline/hetero_secureboost/pipeline_train_union_sbt.py
> edit examples.experiment_template

- python/federatedml/feature/feature_selection/model_adapter/pearson_adapter.py
> edit selection model adapter 

- python/federatedml/util/data_format_preprocess.py
Changes:
1. fix data format preprocess
> update data_format_preprocess: fix extend columns with match_id

- python/fate_client/flow_client/flow_cli/commands/component.py
- python/fate_client/flow_client/flow_cli/commands/model.py
- python/fate_client/flow_sdk/client/api/component.py
- python/fate_client/flow_sdk/client/api/model.py
- python/fate_test/fate_test/flow_test/flow_cli_api.py
- python/fate_test/fate_test/flow_test/flow_rest_api.py
- python/fate_test/fate_test/flow_test/flow_sdk_api.py
Signed-off-by: Jat <jat@sinosky.org>
Changes:
1.
2.
3.
> update cli & sdk

- conf/service_conf.yaml
> update pulsar ttl

- doc/tutorial/README.md
- doc/tutorial/pipeline/index.md
- doc/tutorial/pipeline/pipeline_tutorial_multiple_id_columns.ipynb
- doc/tutorial/pipeline/pipeline_tutorial_uploading_data_with_meta.ipynb
Changes:
1. add tutorial with uploading data with meta
2. add tutorial with multiple match id columns using.
> add tutorials for uploading data with meta and multiple match id columns

- deploy/cluster-deploy/doc/fate_on_spark/common/hadoop_spark_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/common/hadoop_spark_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/common/nginx_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/common/nginx_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/common/pulsar_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/common/pulsar_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/common/spark_standalone_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/common/spark_standalone_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.zh.md
Fixes  ISSUE #4287 
Changes:
1.update doc
2.
3.
> Feature 1.9.0 deploy doc

- RELEASE.md
Changes:
1. update release note of fate-v1.9.0
> update release note of fate-v1.9.0

- README.md
- README_zh.md
> optim readme

- .github/workflows/codeql-analysis.yml
> chore: fix codeql github action

- RELEASE.md
Changes:
1. fix typo of release note
> fix typo of RELEASE note

- doc/tutorial/dsl_conf/dsl_conf_tutorial.md
Signed-off-by: yaoyf <yaoyf@asiainfo.com>
fix doc when use dsl to predict job
> fix doc when use dsl to predict job

- doc/2.0/fate_flow/docker_load.md
> Dev 2.0 alpha fate flow

- deploy/upgrade/sql/1.8.0-1.9.0.sql
Signed-off-by: Chen Jing <jingch@vmware.com>
Changes:
Fix the upgrade script, content provided by @zhihuiwan
> fix the upgrade script from 180 to 190

- python/fate_test/fate_test/_parser.py
- python/fate_test/fate_test/scripts/_options.py
- python/fate_test/fate_test/scripts/benchmark_cli.py
- python/fate_test/fate_test/scripts/data_cli.py
- python/fate_test/fate_test/scripts/performance_cli.py
- python/fate_test/fate_test/scripts/testsuite_cli.py
Fixes  ISSUE #4400
Changes:
1.
2.
3.
> Feature 1.10 fate test data

- python/federatedml/statistic/intersect/intersect_model.py
Fixes  ISSUE #4338
Changes:
1.
2.
3.
> edit intersect summary(#4338)

- examples/pipeline/positive_unlabeled/README.md
- examples/pipeline/positive_unlabeled/positive_unlabeled_pipeline_testsuite.json
- python/federatedml/semi_supervised_learning/positive_unlabeled/positive_unlabeled_transformer.py
Signed-off-by: Xinye Fan xfan2@wpi.edu
Fixes  ISSUE #3930 
Changes:
1. Updating semi-supervised learning component
> Update-1.10.0 Semi-Supervised Learning Component 

- python/federatedml/secure_information_retrieval/secure_information_retrieval_guest.py
- python/federatedml/statistic/intersect/dh_intersect/dh_intersect_guest.py
Fixes  ISSUE 
Changes:
1.  update use of DH Intersect in SIR module
2.
3.
> Feature 1.10 ecdh mpsi

- RELEASE.md
> update release note of fate-v1.9.1

- schemas/jobs/lr.yaml
> Dev 2.0 alpha flow

- schemas/jobs/lr.yaml
> update job yaml：delete tasks parties

- examples/pipeline/positive_unlabeled/pipeline-positive-unlabeled-sshe-lr.py
- python/federatedml/semi_supervised_learning/positive_unlabeled/positive_unlabeled_transformer.py
Fixes  ISSUE #3930 
Changes:
1. add metric type for module summary display on FATE-Board
2. edit example
3.
> add metric type

- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
- python/federatedml/param/feature_binning_param.py
Fixes  ISSUE #
Changes:
1.
2.
3.
> Feature 1.10 binning

- examples/pipeline/hetero_nn/pipeline-hetero-nn-train-multi.py
- examples/pipeline/hetero_nn/pipeline-hetero-nn-train-with-check-point.py
- python/fate_client/pipeline/__init__.py
- python/federatedml/nn/hetero/base.py
- python/federatedml/nn/hetero/guest.py
- python/federatedml/nn/hetero/host.py
- python/federatedml/nn/hetero/interactive/base.py
- python/federatedml/nn/hetero/interactive/he_interactive_layer.py
- python/federatedml/nn/hetero/interactive/utils/numpy_layer.py
- python/federatedml/nn/hetero/model.py
- python/federatedml/nn/hetero/nn_component/bottom_model.py
- python/federatedml/nn/hetero/nn_component/top_model.py
- python/federatedml/nn/hetero/nn_component/torch_model.py
- python/federatedml/nn/hetero/protection_enhance/coae.py
- python/federatedml/nn/homo/trainer/fedavg_trainer.py
- python/federatedml/nn/homo/trainer/trainer_base.py
fix hetero-nn bug & homo-nn bug
- fix coae
- fix hetero-nn cv
- enhance homo-nn param check
> Feature 1.10 nn fix

- python/federatedml/linear_model/linear_model_weight.py
Signed-off-by: fangxiaoran <xiaoran.fang@intel.com>
Changes:
1. Fix a Paillier type check bug
> Fix some bugs after merging IPCL

- python/federatedml/framework/hetero/procedure/paillier_cipher.py
- python/federatedml/framework/hetero/sync/paillier_keygen_sync.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_guest.py
- python/federatedml/linear_model/coordinated_linear_model/logistic_regression/hetero_logistic_regression/hetero_lr_host.py
- python/federatedml/transfer_variable/transfer_class/hetero_lr_transfer_variable.py
> edit transfer var

- python/fate/arch/context/_io.py
> flow: predict

- python/federatedml/secureprotol/encrypt.py
> remove ipcl import warning

- python/fate_client/pipeline/__init__.py
- python/fate_client/pipeline/component/hetero_nn.py
- python/fate_client/pipeline/config.yaml
> Feature 1.10 ipcl import

- RELEASE.md
Changes:
1. update release note of v1.10.0
> update release note of fate-v1.10.0

- python/fate_client/pipeline/component/nn/backend/torch/base.py
- python/fate_client/pipeline/component/nn/interface.py
- python/federatedml/nn/backend/torch/base.py
> pipeline fix

- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_eggroll/fate-allinone_deployment_guide.zh.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.md
- deploy/cluster-deploy/doc/fate_on_spark/fate_on_spark_deployment_guide.zh.md
Fixes  ISSUE #4549 
Changes:
1.update doc
2.
3.
> Feature 1.10.0 deploy doc

- RELEASE.md
Changes:
1. update release note
> update release note of v1.10.0

- python/requirements.txt
> edit requirements

- .gitmodules
> update submodule of fate-v1.10.0

- python/fate_client/pyproject.toml
- python/fate_client/setup.py
> update fate_client requirements

- python/fate/components/loader/federation.py
> fix pulsar federation

- RELEASE.md
- doc/2.0/README.md
> fateflow: update doc

- RELEASE.md
- doc/2.0/README.md
> Dev 2.0 alpha doc update

- python/fate/components/spec/logger.py
> update logging handle

- python/fate/arch/_standalone.py
this fix lmdb bug in standalone mode
> fix(arch): fix lmdb bug

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/_frame_reader.py
- python/fate/arch/dataframe/entity/types.py
- python/fate/arch/dataframe/io/_json_schema.py
- python/fate/arch/dataframe/io/_json_serialization.py
- python/fate/arch/dataframe/manager/__init__.py
- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/manager/data_manager.py
- python/fate/arch/dataframe/manager/schema_manager.py
- python/fate/arch/dataframe/ops/__init__.py
- python/fate/arch/dataframe/ops/_arithmetic.py
- python/fate/arch/dataframe/ops/_column_extract.py
- python/fate/arch/dataframe/ops/_compress_block.py
- python/fate/arch/dataframe/ops/_field_extract.py
- python/fate/arch/dataframe/ops/_indexer.py
- python/fate/arch/dataframe/ops/_promote_types.py
- python/fate/arch/dataframe/ops/_secure_boost_ops.py
- python/fate/arch/dataframe/ops/_set_item.py
- python/fate/arch/dataframe/ops/_transformer.py
- python/fate/arch/dataframe/storage/_match_index.py
- python/fate/arch/dataframe/storage/_sample_index.py
- python/fate/components/components/reader.py
- python/fate/ml/intersection/raw_intersection.py
Fix Issues #4688 #4656 
Changes:
1. add data manager to manage blocks
2. support setitem/getitem/getattr/create_frame/artithmetic... api
> Feature 2.0.0 beta dataframe update

- python/fate_arch/_standalone.py
this fix lmdb error happen occasionally in standalone mode.
basically, this issue related to lmdb _Environment management and cursor management.
Be aware that,  _Environment should not be opened twice in same Process in same time!
> fix(arch): fix lmdb error

- conf/service_conf.yaml
- python/fate_arch/common/conf_utils.py
- python/fate_arch/common/encrypt_utils.py
> Feature 1.11.0 fate flow

- python/federatedml/feature/binning/base_binning.py
- python/federatedml/feature/binning/bin_result.py
- python/federatedml/feature/hetero_feature_binning/base_feature_binning.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_guest.py
- python/federatedml/feature/hetero_feature_binning/hetero_binning_host.py
Fixes  ISSUE #4711
Changes:
1.
2.
3.
> fix bin num(#4711)

- python/federatedml/util/data_transform.py
- python/federatedml/util/fixpoint_solver.py
Fixes  ISSUE #4723 #4724 
Changes:
1. fix exclusive data type not working problme
2. fix input data type is object, but fixpoint_solver fails
> Feature 1.11.0 exclusive type bug fix

- doc/tutorial/pipeline/nn_tutorial/Homo-NN-Customize-Trainer.ipynb
> fix doc bug

- python/federatedml/nn/homo/client.py
- python/federatedml/nn/model_zoo/pellm/parameter_efficient_llm.py
> remove redundant code

- RELEASE.md
Changes:
1. update release note
> update release note of fate-v1.11

- RELEASE.md
Changes:
1. update release note
> update release note of fate-v1.11.0

- doc/tutorial/pipeline/nn_tutorial/Bert-example.ipynb
> update bert doc

- RELEASE.md
> fix RELEASE doc

- doc/tutorial/pipeline/nn_tutorial/Homo-Graph.ipynb
- python/requirements-graph-nn.txt
- python/requirements.txt
Changes:
1. remove the lines about pyg in requriements.txt
2. add them to requriements-graph-nn.txt
3. show the installation steps in doc
> pyg installation and doc

- doc/tutorial/pipeline/nn_tutorial/Homo-Graph.ipynb
- doc/tutorial/pipeline/nn_tutorial/README.md
- python/federatedml/nn/homo/trainer/fedavg_graph_trainer.py
review and update
fix doc
fix cuda parameter
> Feature 1.11.1 graph bug fix

- python/federatedml/nn/dataset/graph.py
> fix import when geometric is not installed

- doc/tutorial/fate_llm/GPT2-multi-task.ipynb
update doc, fix padding direction
> fix padding

- python/requirements-fate-llm.txt
Changes:
1. update requirements
> update fate_llm requirements

- python/fate_test/pyproject.toml
- python/fate_test/setup.py
Changes:
1. update requirements of fate_test
> update fate_test: fix click req

- .gitmodules
- doc/tutorial/pipeline/nn_tutorial/README.md
- python/federatedml/nn/homo/trainer/fedavg_trainer.py
> update doc of nn

- python/federatedml/nn/homo/trainer/fedavg_trainer.py
Changes:
1. fix secure aggregate parameters
> Fix secure agg 

- .pre-commit-config.yaml
- python/fate/arch/_standalone.py
- python/fate/arch/context/_federation.py
- python/fate/arch/context/_mlmd.py
- python/fate/components/cpn.py
- python/fate/components/params/__init__.py
> fix some mirror bug

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_stat.py
> update dataframe: support skew/kurt/power

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_missing.py
- python/fate/arch/dataframe/ops/_stat.py
Signed-off-by:  mgqa34 mgq3374541@163.com
Changes:
1. dataframe: support variation/isna/na_count
> dataframe interface update

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_stat.py
> update dataframe: add describe

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/manager/data_manager.py
- python/fate/arch/dataframe/manager/schema_manager.py
- python/fate/arch/dataframe/ops/_encoder.py
Changes:
1. dateframe: support get_dummies
> dataframe api update

- examples/pipeline/test_statistics.py
- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_stat.py
- python/fate/components/components/statistics.py
- python/fate/components/params/__init__.py
- python/fate/components/params/_metrics.py
- python/fate/ml/statistics/__init__.py
- python/fate/ml/statistics/statistics.py
Signed-off-by: yolandwu131@gmail.com
Fixes  ISSUE #4663
Changes:
1. add stat module & component
2.
3.
> Feature 2.0.0 stat

- python/fate/arch/dataframe/_frame_reader.py
- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/components/components/dataframe_transformer.py
> Feature 2.0.0 beta flow upload

- python/fate/arch/_standalone.py
- python/fate/arch/tensor/distributed/_tensor.py
- python/fate/components/components/__init__.py
- python/fate/components/components/artifact_test.py
- python/fate/components/components/evaluation.py
- python/fate/components/components/homo_nn.py
- python/fate/components/core/_cpn_search.py
- python/fate/components/core/component_desc/_component.py
- python/fate/components/core/component_desc/_component_io.py
- python/fate/components/core/component_desc/_parameter.py
- python/fate/components/core/spec/component.py
- python/fate/components/entrypoint/component_cli.py
- fix metric
- fix metric
- fix metric
- fix metric
- add union artifact
- add parameter desc
- fix bug
- fix output bug
- remove fate.interface
- remove fate.interface
- add debug logs for standalone
- fix model directory typing
- add multi type checking
- fix import
- refactor component execution io
- fix artifact-type
- refactor build in cpn search to support lazy
- add optional field to artifact-type
- fix parameter merge corner case
> updates about fix and improve today

- python/fate/arch/context/_context.py
- python/fate/components/components/artifact_test.py
- python/fate/components/core/component_desc/_component_io.py
- python/fate/components/core/component_desc/artifacts/_base_type.py
- python/fate/components/core/component_desc/artifacts/data/_dataframe.py
- python/fate/components/core/component_desc/artifacts/data/_directory.py
- python/fate/components/core/component_desc/artifacts/data/_table.py
- python/fate/components/core/component_desc/artifacts/metric/_json.py
- python/fate/components/core/component_desc/artifacts/model/_directory.py
- python/fate/components/core/component_desc/artifacts/model/_json.py
- python/fate/components/core/spec/artifact.py
- python/fate/components/entrypoint/component.py
> fix model overview

- python/fate/components/components/intersection.py
Changes:
1. fix intersection io
> fix intersection io

- python/fate/components/components/homo_nn.py
- python/fate/components/components/nn/runner/default_runner.py
> Dev 2.0.0 homo nn predict fix

- python/fate/arch/dataframe/ops/_set_item.py
> dataframe: fix when df.label = ... cause type promoting

- examples/pipeline/test_scale.py
- python/fate/arch/context/_context.py
- python/fate/arch/dataframe/ops/_set_item.py
- python/fate/arch/tensor/distributed/_ops_binary.py
- python/fate/arch/tensor/distributed/_tensor.py
- python/fate/components/components/feature_scale.py
- python/fate/components/components/homo_nn.py
- python/fate/components/components/intersection.py
- python/fate/components/components/nn/runner/default_runner.py
- python/fate/components/core/component_desc/_parameter.py
Fixes  ISSUE #4670
Changes:
1.
2.
3.
> Feature 2.0.0 scale

- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/ops/_fillna.py
- python/fate/arch/dataframe/ops/_where.py
- python/fate/arch/dataframe/utils/_dataloader.py
Changes:
1. dataframe api update: support df[mask] with float type
2. dataframe bugfix: fix fillna
> Dev 2.0.0 beta merge

- examples/pipeline/test_statistics.py
Fixes  ISSUE #4663 
Changes:
1. edit example
2.
3.
> edit stat example

- python/fate/arch/context/_context.py
> fix bug introduced in code merging

- python/fate/arch/computing/spark/_csession.py
- python/fate/components/core/component_desc/artifacts/data/_dataframe.py
- python/fate/components/core/spec/logger.py
- python/fate/components/core/spec/task.py
Signed-off-by: zhihuiwan [15779896112@163.com]
Changes:
1.
2.
3.
> fate on spark

- python/fate/ml/glm/hetero/coordinated_linr/guest.py
- python/fate/ml/glm/hetero/coordinated_lr/guest.py
Fixes  ISSUE #4659
Changes:
1. switch computation steps in GLM gradient computation 
2.
3.
> optimize glm centralized gradient compute(#4659)

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_dimension_scaling.py
- python/fate/arch/dataframe/utils/__init__.py
- python/fate/arch/dataframe/utils/_dataloader.py
- python/fate/arch/dataframe/utils/_sample.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/test/test_loss.py
- python/fate/ml/nn/trainer/test/test_trainer.py
Add the experimental decision tree
> Dev 2.0.0 secureboost

- python/fate/components/core/params/_fields.py
> add smart_union to parameter parse

- examples/pipeline/test_data_split.py
- examples/pipeline/test_sample.py
- python/fate/components/components/data_split.py
- python/fate/components/components/sample.py
- python/fate/ml/model_selection/data_split.py
- python/fate/ml/model_selection/sample.py
Fixes  ISSUE #4662 #4779
Changes:
1. edit data split
2. edit sample
3.
> Feature 2.0.0 sample

- python/fate/arch/dataframe/ops/_replace.py
> dataframe: fix replace op type judgement logic

- python/fate/ml/feature_binning/hetero_feature_binning.py
Fixes  ISSUE #4660
Changes:
1.
2.
3.
> raise error when host use woe transform(#4660)

- python/fate/components/components/data_split.py
- python/fate/ml/model_selection/data_split.py
Fixes  ISSUE #4779
Changes:
1.
2.
3.
> edit data split(#4779)

- examples/pipeline/test_data_split_stratified.py
- python/fate/ml/model_selection/data_split.py
Fixes  ISSUE #4779
Changes:
1.
2.
3.
> fix data split stratified(#4779)

- python/fate/components/components/hetero_feature_binning.py
Fixes  ISSUE #4660
Changes:
1. 
2.
3.
> add param check for 'transform_method'(#4660)

- python/fate/components/core/component_desc/artifacts/_base_type.py
- python/fate/components/core/component_desc/artifacts/data/_dataframe.py
- python/fate/components/core/component_desc/artifacts/data/_directory.py
- python/fate/components/core/component_desc/artifacts/data/_table.py
- python/fate/components/core/component_desc/artifacts/metric/_json.py
- python/fate/components/core/component_desc/artifacts/model/_directory.py
- python/fate/components/core/component_desc/artifacts/model/_json.py
> add consumed field to artifact

- rust/fate_utils/crates/fate_utils/src/tensor/cb.rs
> improve sum

- python/fate/ml/preprocessing/union.py
Fixes  ISSUE #4668
Changes:
1.
2.
3.
> edit schema check(#4668)

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_indexer.py
> dataframe: fix loc

- python/fate/arch/dataframe/utils/_dataloader.py
- python/fate/ml/intersection/raw_intersection.py
> dataloader: ensure order

- python/fate/arch/dataframe/ops/_dimension_scaling.py
> dataframe: fix vstack column retrieval problem

- python/fate/arch/protocol/phe/paillier.py
- rust/fate_utils/crates/fate_utils/src/paillier/evaluator.rs
- rust/fate_utils/crates/fate_utils/src/paillier/paillier.rs
- rust/fate_utils/crates/fixedpoint/src/coder.rs
> dev 2.0.0 beta sage paillier

- python/fate/arch/dataframe/ops/_indexer.py
Changes:
1. fix loc unreplace sample_id
2. fix iloc block_id incorrent problem
> Feature 2.0.0 beta round3 dataframe update

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/_frame_reader.py
- python/fate/arch/dataframe/ops/_indexer.py
- python/fate/arch/dataframe/ops/_transformer.py
- python/fate/arch/protocol/psi/ecdh/_run.py
Changes:
1. dataframe: fix as_tensor, optimizer psi
> dataframe: fix as_tensor, optimizer psi

- python/fate/components/components/__init__.py
- python/fate/components/components/hetero_sbt.py
- python/fate/components/components/homo_nn.py
- python/fate/ml/ensemble/__init__.py
- python/fate/ml/ensemble/algo/secureboost/common/predict.py
- python/fate/ml/ensemble/algo/secureboost/hetero/_base.py
- python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
- python/fate/ml/ensemble/algo/secureboost/hetero/host.py
- python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
- python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_regression.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/subsample.py
- python/fate/ml/ensemble/utils/binning.py
- python/fate/ml/glm/hetero/coordinated_linr/host.py
- python/fate/ml/glm/hetero/coordinated_lr/guest.py
- python/fate/ml/glm/hetero/coordinated_lr/host.py
- python/fate/test/test_histogram.py
Add hetero-sbt contents:
1. Ml algo
2. Histogram support
3. Component
4. Test scripts
> Add Hetero Secureboost:

- python/fate/arch/protocol/psi/ecdh/_run.py
Changes:
1. psi: speed up by changing flatmap to mapPartitions
> psi: speed up

- python/fate/components/components/hetero_sbt.py
- python/fate/components/components/homo_lr.py
- python/fate/ml/glm/homo/lr/client.py
1. fix homo-lr bug
2. add hetero-sbt predict
> Dev 2.0.0 bug fix round 3

- python/fate/arch/dataframe/ops/_indexer.py
Changes:
1. dataframe: fix loc_with_sample_id_replacement, which dst row are unsort
> dataframe: fix loc_with_sample_id_replacement

- python/fate/components/components/hetero_sbt.py
- python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
- python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_multi.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/loss.py
- python/fate/ml/evaluation/classification.py
1. predict format json error
2. error indent code
> Fix bug in hetero-sbt:

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/ops/_apply_row.py
- python/fate/arch/dataframe/ops/_dimension_scaling.py
- python/fate/arch/dataframe/ops/_encoder.py
- python/fate/arch/dataframe/ops/_field_extract.py
- python/fate/arch/dataframe/ops/_indexer.py
- python/fate/arch/protocol/psi/ecdh/_run.py
> dataframe: op optimize

- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/tensor/phe/_keypair.py
- python/fate/arch/tensor/phe/_tensor.py
> dev 2.0.0 beta improve iupdate

- python/fate/arch/histogram/histogram.py
> fix serde bugs

- python/fate/arch/dataframe/ops/_set_item.py
> dataframe: fix set_item

- rust/fate_utils/crates/fate_utils/src/paillier/paillier.rs
> fix packer/unpacker

- python/fate/arch/histogram/histogram.py
> add some api for tests

- examples/benchmark_performance/coordinated_lr/test_lr_sid.py
- examples/benchmark_quality/linr/fate-linr.py
- examples/benchmark_quality/lr/pipeline-lr-binary.py
- examples/benchmark_quality/lr/pipeline-lr-multi.py
- examples/pipeline/coordinated_linr/test_linr.py
- examples/pipeline/coordinated_linr/test_linr_multi_host.py
- examples/pipeline/coordinated_linr/test_linr_warm_start.py
- examples/pipeline/coordinated_lr/test_lr.py
- examples/pipeline/coordinated_lr/test_lr_multi_class.py
- examples/pipeline/coordinated_lr/test_lr_multi_host.py
- examples/pipeline/coordinated_lr/test_lr_validate.py
- examples/pipeline/coordinated_lr/test_lr_warm_start.py
- examples/pipeline/feature_scale/test_scale_w_lr.py
- examples/pipeline/multi_model/test_multi.py
- examples/pipeline/multi_model/test_multi_w_predict.py
- python/fate/ml/utils/predict_tools.py
Fixes  ISSUE #4659
Changes:
1. edit predict utils
2. edit lr & linr examples
3.
> predict utils rename label name in predict result dataframe(#4659)

- python/fate/arch/histogram/histogram.py
- add union for ShuffledHistogram
> dev 2.0.0 beta add histogram test api

- python/fate/arch/histogram/histogram.py
> enhance unpack

- python/fate/ml/utils/predict_tools.py
> predict tools add check for null label name

- python/fate/arch/context/_cipher.py
- python/fate/arch/histogram/histogram.py
- python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
> Dev 2.0.0 gh

- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
> secureboost: remove duplicate operations

- rust/fate_utils/crates/fate_utils/src/paillier/paillier.rs
- rust/fate_utils/crates/fixedpoint_paillier/src/lib.rs
> fix packer/unpacker error

- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
> secureboost: optimize dataframe op call

- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/ops/_indexer.py
- python/fate/arch/dataframe/utils/_dataloader.py
- python/fate/arch/dataframe/utils/_sample.py
> dataframe: fix dataloader loc, vstack cat of pd.Index

- doc/tutorial/pipeline_tutorial_hetero.ipynb
Fixes  ISSUE #
Changes:
1.
2.
3.
> edit configuration in pipeline tutorial

- python/fate/arch/histogram/histogram.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
Changes:
1. secureboost: optimize update_sample_pos process
2. histogram: expand partitions for balance
> Feature 2.0.0 beta dataframe refact

- python/fate/arch/dataframe/ops/_dimension_scaling.py
- python/fate/arch/dataframe/ops/_indexer.py
> dataframe: fix bug of loc datamanager inplace

- python/fate/arch/dataframe/ops/_set_item.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
> optimizer secureboost

- python/fate/arch/tensor/_custom_ops.py
- python/fate/arch/tensor/distributed/_ops_others.py
- python/fate/arch/tensor/distributed/_tensor.py
> add encode_as_int_f

- java/osx/RELEASE.md
> change doc

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_apply_row.py
- python/fate/arch/dataframe/ops/_set_item.py
- python/fate/ml/ensemble/algo/secureboost/common/predict.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
> optimizer secureboost predicting,and  apply_row api in dataframe

- python/fate/arch/dataframe/_dataframe.py
> dataframe: support histogram stat without passing node positions

- python/fate/arch/dataframe/_dataframe.py
- python/fate/components/components/coordinated_linr.py
- python/fate/components/components/coordinated_lr.py
- python/fate/components/core/params/__init__.py
- python/fate/components/core/params/_he_param.py
- python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
- python/fate/ml/glm/hetero/coordinated_linr/guest.py
- python/fate/ml/glm/hetero/coordinated_linr/host.py
- python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
- python/fate/ml/glm/hetero/coordinated_lr/guest.py
- python/fate/ml/glm/hetero/coordinated_lr/host.py
Fixes  ISSUE #4659
Changes:
1. add HEParam for specifying he kind and key length
2.
3.
> coordinated lr & linr use he param for he kind and key length (#4659)

- python/fate/arch/histogram/_histogram_distributed.py
- python/fate/arch/histogram/_histogram_splits.py
- python/fate/arch/histogram/values/_values.py
- python/fate/arch/protocol/phe/paillier.py
> add subkey for histogram

- python/fate/arch/histogram/_histogram_local.py
- python/fate/arch/histogram/values/_values.py
- add subkey for histogram
- add to_dict method to Histogram
> dev 2.0.0 beta histogram subkey

- python/fate/arch/tensor/distributed/_op_matmul.py
> type promote only when both tensor are torch.Tensor

- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/ops/_encoder.py
- python/fate/arch/dataframe/utils/_sample.py
- python/fate/ml/model_selection/data_split.py
> fix convert block warning

- python/fate/arch/dataframe/ops/_dimension_scaling.py
> dataframe: fix row indexing by label/weight

- python/fate/arch/histogram/values/_cipher.py
- python/fate/arch/histogram/values/_values.py
- python/fate/components/components/hetero_feature_binning.py
- python/fate/ml/feature_binning/hetero_feature_binning.py
Fixes  ISSUE #4660
Changes:
1. [use new distributed histogram api in hetero feature binning
2.
3.
> Feature 2.0.0 beta fate test

- python/fate/arch/context/_cipher.py
- python/fate/arch/histogram/_histogram_distributed.py
- python/fate/arch/histogram/_histogram_local.py
- python/fate/arch/histogram/_histogram_splits.py
- python/fate/arch/histogram/indexer/_indexer.py
- python/fate/arch/histogram/values/_cipher.py
- python/fate/arch/histogram/values/_plain.py
- python/fate/arch/histogram/values/_value.py
- python/fate/arch/histogram/values/_values.py
- python/fate/arch/protocol/phe/mock.py
- python/fate/arch/protocol/phe/paillier.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/test/test_decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
- rust/fate_utils/crates/fate_utils/src/paillier/paillier.rs
- rust/fate_utils/crates/fixedpoint_paillier/src/lib.rs
- remove old codes
- Update hist-sub
- fix histogram
- fix histogram
- fix histogram sub
- fix histogram values when coder not provided
> dev 2.0.0 hist sub

- python/fate/arch/dataframe/manager/schema_manager.py
> dataframe: support rename same column

- python/fate/arch/context/_cipher.py
- python/fate/components/components/coordinated_linr.py
- python/fate/components/components/coordinated_lr.py
- python/fate/components/components/hetero_feature_binning.py
- python/fate/ml/feature_binning/hetero_feature_binning.py
- python/fate/ml/glm/hetero/coordinated_linr/arbiter.py
- python/fate/ml/glm/hetero/coordinated_lr/arbiter.py
> improve cipher setup

- python/fate/arch/context/_federation.py
> fix party name

- python/requirements-fate.txt
> update requirements of fate

- python/fate/arch/dataframe/_frame_reader.py
- python/fate/arch/dataframe/io/_json_serialization.py
- python/fate/arch/dataframe/manager/data_manager.py
- python/fate/arch/dataframe/manager/schema_manager.py
- python/fate/arch/dataframe/manager/utils/_anonymous_generator.py
- python/fate/components/components/dataframe_transformer.py
> dataframe: adjust for anonymous sitename

- python/fate/components/core/params/_filter_param.py
- python/fate/ml/feature_selection/hetero_feature_selection.py
Fixes  ISSUE #4661
Changes:
1. update description file
2. fix percentile filter selection 
3.
> fix percentile filter selection(#4661)

- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/ops/_apply_row.py
> dataframe: fix apply_row type judging

- python/fate/arch/dataframe/manager/block_manager.py
> dataframe: fix column indexing order problem

- examples/pipeline/data_split/test_data_split_stratified.py
> edit pipeline examples

- examples/pipeline/data_split/test_data_split_stratified.py
> edit pipeline example

- python/fate/arch/context/_cipher.py
- python/fate/ml/ensemble/algo/secureboost/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/guest.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
> disable custom seed in sbt

- python/fate/components/components/nn/torch/__init__.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
- python/fate/ml/nn/trainer/trainer_base.py
> Add copyright

- python/fate/arch/histogram/values/_cipher.py
- python/fate/arch/histogram/values/_values.py
- python/fate/arch/protocol/phe/mock.py
- python/fate/arch/protocol/phe/ou.py
- python/fate/arch/protocol/phe/paillier.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
- python/fate/ml/feature_binning/hetero_feature_binning.py
> add dtype to cipher value in histogram and fix ou coder for uint

- examples/benchmark_quality/hetero_sbt/hetero_sbt_benchmark.yaml
- examples/benchmark_quality/hetero_sbt/xgb.py
- examples/benchmark_quality/hetero_sbt/xgb_student_config.yaml
- examples/benchmark_quality/homo_nn/fed_nn_student_config.yaml
- examples/benchmark_quality/homo_nn/fed_nn_vehicle_config.yaml
- examples/benchmark_quality/homo_nn/homo_nn_benchmark.yaml
- examples/benchmark_quality/homo_nn/local_nn_binary.py
- examples/benchmark_quality/homo_nn/local_nn_multi.py
- examples/benchmark_quality/homo_nn/local_nn_regression.py
- examples/benchmark_quality/homo_nn/local_nn_student_config.yaml
- examples/benchmark_quality/homo_nn/local_nn_vehicle_config.yaml
- examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
- examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
- examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
> Dev 2.0.0 benchmark verify

- examples/benchmark_quality/lr/vehicle_config.yaml
- python/requirements-fate.txt
- python/setup.py
specify sklearn version in requirements
Changes:
1.
2.
3.
> add random state to lr bq example

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/manager/block_manager.py
- python/fate/arch/dataframe/manager/data_manager.py
Changes:
1. support dtypes in dataframe
> dataframe: add dtypes

- python/fate/arch/histogram/values/_cipher.py
- python/fate/arch/histogram/values/_encoded.py
- python/fate/arch/histogram/values/_plain.py
- python/fate/arch/histogram/values/_values.py
- python/fate/arch/protocol/phe/mock.py
> add dtype to cipher value in histogram

- python/fate/arch/histogram/values/_encoded.py
- python/fate/ml/feature_binning/hetero_feature_binning.py
Fixes  ISSUE #4660
Changes:
1.
2.
3.
> fix binning when he kind is mock(#4660)

- python/fate/arch/dataframe/ops/_encoder.py
> dataframe: fix bucketize when boudaries are all integers

- python/fate/arch/histogram/values/_cipher.py
> fix zeros bug

- python/fate/ml/ensemble/learner/decision_tree/tree_core/hist.py
> secureboost: hist fix, use dtypes from gh frame

- python/fate/ml/ensemble/algo/secureboost/test/test_hetero_sbt_binary.py
- python/fate/ml/ensemble/learner/decision_tree/hetero/host.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/decision_tree.py
- python/fate/ml/ensemble/learner/decision_tree/tree_core/splitter.py
> remove logs

- doc/2.0/quick_start.md
> udpate quick start doc for component using

- python/fate/arch/computing/spark/_csession.py
> Feature 2.0.0 beta doc

- RELEASE.md
> update release of 2.0.0-beta

- python/requirements-fate.txt
> update torch to cpu for manually deploy

- python/fate/components/core/params/_filter_param.py
Signed-off-by: yoldanwu131@gmail.com
Fixes  ISSUE #4661
Changes:
1.
2.
3.
> fix statistic filter param(#4661)

- examples/benchmark_performance/hetero_secureboost/default_credit_config.yaml
- examples/benchmark_performance/hetero_secureboost/hetero_secureboost_performance.yaml
- examples/benchmark_performance/hetero_secureboost/test_sbt.py
> add benchmark performance of hetero-sbt & fix import

- RELEASE.md
> update release note

- deploy/standalone-deploy/README.zh.md
> doc: update zh doc of standalone-deploy

- deploy/standalone-deploy/README.zh.md
> fix standalone deploy zh doc

- .gitmodules
Changes:
1. update submodule of fate_flow/fate_client/eggroll
2. add new submodule: fate_test
> Feature 2.0.0 beta update submodule

- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- doc/2.0/quick_start.md
> Feature 2.0.0 quick guide update

- python/fate/arch/federation/osx/_federation.py
- python/fate/arch/federation/pulsar/_federation.py
> optim bug for osx and pulsar maxsize

- python/fate/arch/dataframe/_dataframe.py
- python/fate/arch/dataframe/ops/_sort.py
Changes:
1. dataframe: add nlargest interface
> dataframe: add nlargest interface

- python/fate/arch/dataframe/ops/_sort.py
> dataframe: fix nlargest

- python/fate/arch/dataframe/ops/_sort.py
> dataframe: fix nlargest return size

- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/cross_entropy.py
- python/federatedml/ensemble/basic_algorithms/decision_tree/tree_core/loss/test/cross_entropy_test.py
> recover xentropy computation, align to lgb

- python/fate_arch/common/encrypt_utils.py
Signed-off-by: gxx777 xiangxinguo@mail.ustc.edu.cn
Fixes  ISSUE #5234 
Changes:
1. update RSA padding from PKCS1v1.5 to OAEP
Test:
I have run `test_encrypt_decrypt` function  to validate the effectiveness of encryption and decryption.
> Update RSA OAEP Padding 

- examples/pipeline/homo_nn/pipeline_homo_nn_train_binary.py
- python/federatedml/nn/homo/_init.py
- python/federatedml/nn/homo/client.py
> Fix predict

- python/fate/arch/dataframe/ops/_apply_row.py
- python/fate/arch/dataframe/ops/_dimension_scaling.py
> dataframe: fix vstack when data types or columns order change

- examples/pipeline/feature_correlation/feature_correlation_testsuite.yaml
- examples/pipeline/feature_correlation/test_feature_correlation.py
- python/fate/arch/utils/trace.py
- python/fate/components/components/__init__.py
- python/fate/components/components/feature_correlation.py
- python/fate/ml/statistics/__init__.py
- python/fate/ml/statistics/pearson_correlation.py
Fixes  ISSUE #5228
Changes:
1. add feature correlation component
2.
3.
> add feature correlation(#5228)

- python/federatedml/feature/imputer.py
- python/federatedml/statistic/statics.py
> select random mode when counts equal

- python/federatedml/statistic/statics.py
> add warning if some columns missing mode

- python/fate/ml/feature_selection/hetero_feature_selection.py
> edit metrics

- python/federatedml/optim/gradient/hetero_poisson_gradient_and_loss.py
Fixes  ISSUE #5281
Changes:
1. edit poisson comments about loss computation
2.
3.
> edit poisson comments

- examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
- examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
- examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
- examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_cv.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
- examples/pipeline/homo_lr/test_homo_lr_binary.py
- examples/pipeline/homo_nn/test_nn_binary.py
- examples/pipeline/homo_nn/test_nn_multi.py
- examples/pipeline/homo_nn/test_nn_regression.py
> Dev 2.0.0 rc testsuite fix

- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
- python/fate/components/components/hetero_secureboost.py
> fix sbt bug

- examples/pipeline/hetero_nn/test_nn_binary.py
- examples/pipeline/hetero_nn/test_nn_binary_with_fedpass.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
- python/fate/components/components/hetero_nn.py
- python/fate/components/components/nn/component_utils.py
- python/fate/components/components/nn/runner/hetero_default_runner.py
- python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
- python/fate/ml/glm/homo/lr/client.py
- python/fate/ml/glm/homo/lr/server.py
- python/fate/ml/nn/model_zoo/agg_layer/fedpass/_passport_block.py
> Fix bugs of hetero-nn

- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
> Fix example

- python/fate/arch/computing/eggroll/_csession.py
- python/fate/components/core/_load_computing.py
- python/fate/components/core/spec/computing.py
> add host and port params to eggroll

- python/fate/components/core/component_desc/artifacts/data/_unresolved.py
- python/fate/components/core/spec/component.py
> fix component of reader

- examples/benchmark_quality/linr/fate-sshe-linr.py
- examples/benchmark_quality/lr/breast_config.yaml
- examples/benchmark_quality/lr/default_credit_config.yaml
- examples/benchmark_quality/lr/epsilon_5k_sshe_config.yaml
- examples/benchmark_quality/lr/give_credit_config.yaml
- examples/benchmark_quality/lr/lr_benchmark.yaml
- examples/benchmark_quality/lr/pipeline-sshe-lr-binary.py
- examples/benchmark_quality/lr/pipeline-sshe-lr-multi.py
- examples/benchmark_quality/lr/vehicle_config.yaml
- examples/pipeline/sshe_linr/test_linr_cv.py
- examples/pipeline/sshe_linr/test_linr_warm_start.py
- examples/pipeline/sshe_lr/test_lr.py
- examples/pipeline/sshe_lr/test_lr_multi_class.py
- examples/pipeline/sshe_lr/test_lr_predict_w_torch.py
- examples/pipeline/sshe_lr/test_lr_validate.py
- examples/pipeline/sshe_lr/test_lr_warm_start.py
- python/fate/components/components/sshe_linr.py
- python/fate/components/components/sshe_lr.py
- python/fate/components/components/union.py
- python/fate/components/core/spec/artifact.py
- python/fate/ml/glm/hetero/sshe/sshe_linr.py
- python/fate/ml/glm/hetero/sshe/sshe_lr.py
Fixes  ISSUE #5227 #4668
Changes:
1. edit Union
2. edit SSHE LR & LinR
3. edit examples
> Feature 2.0.0 rc sshe glm

- examples/benchmark_quality/linr/hetero_linr_benchmark.yaml
- examples/benchmark_quality/linr/linr_config.yaml
- examples/pipeline/sshe_linr/sshe_linr_testsuite.yaml
- examples/pipeline/sshe_linr/test_linr_validate.py
Fixes  ISSUE #5227
Changes:
1.
2.
3.
> edit examples(#5227)

- configs/default.yaml
- python/fate/arch/context/_cipher.py
- python/fate/arch/protocol/mpc/__init__.py
- python/fate/arch/protocol/mpc/nn/sshe/linr_layer.py
- python/fate/arch/protocol/mpc/nn/sshe/lr_layer.py
- python/fate/arch/protocol/mpc/nn/sshe/nn_layer.py
- python/fate/arch/protocol/mpc/primitives/arithmetic.py
- python/fate/arch/protocol/mpc/primitives/beaver.py
- python/fate/arch/protocol/phe/ou.py
- python/fate/arch/protocol/phe/paillier.py
- python/fate/arch/protocol/psi/_psi_run.py
- python/fate/test/test_ou.py
- python/fate/test/test_paillier.py
> add default config for protocols

- examples/benchmark_performance/coordinated_lr/config.yaml
- examples/benchmark_performance/coordinated_lr/test_lr.py
- examples/benchmark_performance/sshe_lr/breast_config.yaml
- examples/benchmark_performance/sshe_lr/config.yaml
- examples/benchmark_performance/sshe_lr/sshe_lr_performance.yaml
- examples/benchmark_performance/sshe_lr/test_lr.py
- examples/benchmark_quality/linr/fate-linr.py
- examples/benchmark_quality/linr/fate-sshe-linr.py
- examples/benchmark_quality/lr/epsilon_5k_sshe_config.yaml
- examples/benchmark_quality/lr/pipeline-lr-binary.py
- examples/benchmark_quality/lr/pipeline-lr-multi.py
- examples/benchmark_quality/lr/pipeline-sshe-lr-binary.py
- examples/benchmark_quality/lr/pipeline-sshe-lr-multi.py
- examples/pipeline/coordinated_lr/test_lr_multi_class.py
- python/fate/ml/glm/hetero/sshe/sshe_lr.py
edit examples
Fixes  ISSUE #5227
Changes:
1. edit SSHE LR
2. add examples 
3.
> edit sshe lr(#5227)

- python/fate/ml/glm/hetero/sshe/sshe_linr.py
- python/fate/ml/glm/hetero/sshe/sshe_lr.py
> SSHE LR & LinR record train data header

- python/fate/arch/computing/api/_table.py
- python/fate/arch/context/_federation.py
- python/fate/arch/federation/__init__.py
- python/fate/arch/federation/api/__init__.py
- python/fate/arch/federation/api/_federation.py
- python/fate/arch/federation/api/_table_meta.py
- python/fate/arch/federation/backends/eggroll/_federation.py
- python/fate/arch/federation/backends/osx/_federation.py
- python/fate/arch/federation/backends/pulsar/_federation.py
- python/fate/arch/federation/backends/rabbitmq/_federation.py
- python/fate/arch/federation/backends/standalone/_federation.py
- python/fate/arch/federation/message_queue/__init__.py
- python/fate/arch/federation/message_queue/_federation.py
- python/fate/arch/launchers/multiprocess_launcher.py
- python/fate/arch/trace/_trace.py
- python/requirements-eggroll.txt
- python/requirements-fate.txt
- python/setup.py
> remove type requirements for queue mode and double pickle issue

- python/fate/ml/glm/hetero/sshe/sshe_linr.py
- python/fate/ml/glm/hetero/sshe/sshe_lr.py
> edit logging

- python/fate/arch/federation/backends/osx/_federation.py
- python/fate/arch/federation/backends/osx/_mq_channel.py
- python/fate/arch/federation/backends/rabbitmq/_federation.py
- python/fate/arch/federation/message_queue/_federation.py
> Remove redundant code for osx

- python/fate/arch/protocol/mpc/nn/sshe/nn_layer.py
> add dst param to get

- python/fate/components/components/nn/runner/homo_default_runner.py
- python/fate/ml/aggregator/__init__.py
- python/fate/ml/aggregator/aggregator_wrapper.py
- python/fate/ml/nn/homo/fedavg.py
- python/fate/ml/nn/trainer/trainer_base.py
> homo_nn: deepspeed support

- python/fate/arch/federation/api/_serdes.py
> fix whitelist

- configs/default.yaml
- python/fate/arch/config/_config.py
- python/fate/components/entrypoint/cli/component/execute_cli.py
> add components blacklist

- python/fate/arch/federation/api/_serdes.py
- python/requirements-fate.txt
- python/setup.py
- use safetensor to serialize/deserialize torch tensor
- add dependency
> feature 2.0.0 rc safetensor

- examples/config.yaml
- python/fate/ml/aggregator/aggregator_wrapper.py
- python/fate/ml/nn/trainer/trainer_base.py
Changes:
1. fix homo nn running on cpu device
> Feature 2.0.0 rc ds new

- python/fate/arch/federation/api/_serdes.py
> improve custom serdes

- python/requirements-fate.txt
- python/setup.py
- custom numpy serdes
- fix requirements-fate.txt
> bugfix 2.0.0 rc requirements

- python/fate/arch/computing/backends/spark/_table.py
> bugfix 2.0.0 rc spark

- python/fate/ml/glm/hetero/sshe/sshe_linr.py
- python/fate/ml/glm/hetero/sshe/sshe_lr.py
> fix sshe loss

- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_warm_start.py
- python/fate/ml/ensemble/algo/secureboost/hetero/_base.py
- python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
Fix hetero-secureboost warm-start bug
> Signed-off-by: weijingchen <talkingwallace@sohu.com>

- python/fate/ml/ensemble/algo/secureboost/hetero/guest.py
> Dev 2.0.0 rc final round fix

- python/fate/arch/computing/backends/spark/_table.py
- python/fate/components/components/toy_example.py
> fix bugs when the other side is different engine

- python/fate/components/components/evaluation.py
> Signed-off-by: weijingchen <talkingwallace@sohu.com> Remove logs

- python/requirements-fate.txt
Changes:
1. update requirement versions of transformers and accelerate
> reqs: update version of transformers and accelerate

- python/fate/arch/computing/__init__.py
- python/fate/arch/computing/_builder.py
- python/fate/arch/context/__init__.py
- python/fate/arch/context/_context_helper.py
- python/fate/arch/federation/__init__.py
- chore: remove unused code
- fix: fix enum issue
- feat: add context create helper for ml use
> feature 2.0.0 rc add context create helper

- java/osx/RELEASE.md
> add release note

- RELEASE.md
Signed-off-by: zhihuiwan 15779896112@163.com
Changes:
update fate flow release
> update fate flow release

- RELEASE.md
> edit release note

- python/fate/arch/context/_parties.py
> chore: fix profile

- python/fate/components/core/component_desc/artifacts/metric/_json.py
- chore: fix profile
- chore: remote data in log since it may be large
> bugfix 2.0.0 rc fix profile

- .github/workflows/build_fate.yaml
- .github/workflows/build_fate_utils.yml
- .gitignore
- Makefile
- chore: add some gitignore
- chore: fix makefile
- chore: fix fate build action
- chore: fix fate utils build action
> chore 2.0.0 rc gitignore

- examples/pipeline/psi/psi_testsuite.yaml
- examples/pipeline/psi/test_psi.py
- examples/pipeline/psi/test_psi_multi_host.py
Signed-off-by:  mgqa34 mgq3374541@!63.com
> example: update psi pipeline example

- python/fate/components/core/component_desc/artifacts/data/_dataframe.py
> chore: remove metadata in dataframe write since it may be large

- python/setup.py
> chore: loose some package version in setup

- deploy/cluster-deploy/allinone/fate-allinone_deployment_guide.zh.md
Signed-off-by: robbie228 <v_lmli@webank.com>
Changes:
1. update fate-allinone-deploy doc
2.
3.
> update fate-allinone-deploy doc：source

- bin/service.sh
> add fate service.sh

- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
> update doc of standalone deploy

- doc/2.0/fate/components/evaluation.md
> Dev 2.0.0 evaluation doc

- doc/2.0/fate/ml/hetero_nn_tutorial.md
- examples/launchers/fedpass_nn_launcher.py
- examples/launchers/secureboost_launcher.py
- examples/launchers/sshe_nn_launcher.py
Changes:
1. fix nn tutorial bugs
2. add launcher examples
3.
> fix nn tutorial bugs & add launcher examples

- RELEASE.md
- doc/2.0/fate/performance.md
> edit doc: update performance data of hetero_nn

- examples/pipeline/homo_nn/homo_nn_testsuite.yaml
> fix homo-nn doc Signed-off-by: weijingchen <talkingwallace@sohu.com>

- python/fate/arch/computing/backends/spark/_table.py
> Spark fix 2.1 dy

- python/fate/arch/config/default.yaml
- python/fate/arch/federation/backends/osx/_mq_channel.py
> add osx timeout config

- python/fate/arch/computing/backends/standalone/_standalone.py
- Update fate-exchange_deployment_guide.zh.md
- fix: parallel computing blocks by lmdb write in shuffle without reduce
> bugfix 2.1.0 standalone shuffle write

- python/fate/arch/dataframe/ops/_dimension_scaling.py
Changes:
1. fix order when running on spark
> Feature 2.0.0 fix dataframe join order

- .readthedocs.yml
Changes:
1. add build.os to readthedocs bulding
> add build os to readthedocs

- python/fate/arch/federation/api/_serdes.py
- fix: fix serde when size greater than 4GB
> bugfix 2.1.0 increase byte size limit

- examples/pipeline/coordinated_linr/test_linr.py
- examples/pipeline/coordinated_linr/test_linr_multi_host.py
- examples/pipeline/coordinated_linr/test_linr_warm_start.py
- examples/pipeline/coordinated_lr/test_lr.py
- examples/pipeline/coordinated_lr/test_lr_multi_class.py
- examples/pipeline/coordinated_lr/test_lr_multi_host.py
- examples/pipeline/coordinated_lr/test_lr_predict_w_torch.py
- examples/pipeline/coordinated_lr/test_lr_validate.py
- examples/pipeline/coordinated_lr/test_lr_warm_start.py
- examples/pipeline/feature_scale/test_scale_w_lr.py
- examples/pipeline/hetero_nn/test_nn_binary_fedpass.py
- examples/pipeline/hetero_nn/test_nn_binary_sshe.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_binary_warm_start.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_multi.py
- examples/pipeline/hetero_secureboost/test_hetero_sbt_regression.py
- examples/pipeline/homo_lr/test_homo_lr_binary.py
- examples/pipeline/homo_lr/test_homo_lr_multi_ovr.py
- examples/pipeline/homo_nn/test_nn_binary.py
- examples/pipeline/homo_nn/test_nn_multi.py
- examples/pipeline/homo_nn/test_nn_regression.py
- examples/pipeline/sshe_linr/test_linr.py
- examples/pipeline/sshe_linr/test_linr_validate.py
- examples/pipeline/sshe_linr/test_linr_warm_start.py
- examples/pipeline/sshe_lr/test_lr.py
- examples/pipeline/sshe_lr/test_lr_multi_class.py
- examples/pipeline/sshe_lr/test_lr_predict_w_torch.py
- examples/pipeline/sshe_lr/test_lr_validate.py
- examples/pipeline/sshe_lr/test_lr_warm_start.py
- python/fate/components/components/evaluation.py
> Update evaluation input

- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- doc/2.0/fate/quick_start.md
- python/fate/_info.py
> update version of fate from 2.0.0 to 2.1.0

- python/fate/components/components/nn/runner/hetero_default_runner.py
> Fix hetero-nn param Signed-off-by: weijingchen <talkingwallace@sohu.com>

- RELEASE.md
- doc/2.0/fate/dag.md
- doc/2.0/fate/dag.zh.md
- examples/benchmark_performance/coordinated_lr/test_lr.py
- examples/benchmark_performance/hetero_secureboost/breast_config.yaml
- examples/benchmark_performance/hetero_secureboost/default_credit_config.yaml
- examples/benchmark_performance/hetero_secureboost/test_sbt.py
- examples/benchmark_performance/psi/breast_config.yaml
- examples/benchmark_performance/psi/psi_performance.yaml
- examples/benchmark_performance/psi/test_psi.py
- examples/benchmark_performance/sshe_lr/test_lr.py
Changes:
1. update fate-2.0's dag description
> Feature 2.1.0 update dag doc

- doc/2.0/fate/quick_start.md
- doc/README.md
- doc/tutorial/pipeline_tutorial_hetero.ipynb
> update readme of doc

- examples/benchmark_quality/hetero_nn/hetero_nn.py
- examples/benchmark_quality/hetero_secureboost/pipeline_hetero_sbt.py
- examples/benchmark_quality/homo_nn/homo_nn_benchmark.yaml
- examples/benchmark_quality/homo_nn/pipeline_nn_binary.py
- examples/benchmark_quality/homo_nn/pipeline_nn_multi.py
- examples/benchmark_quality/homo_nn/pipeline_nn_regression.py
- examples/benchmark_quality/linr/fate-linr.py
- examples/benchmark_quality/linr/fate-sshe-linr.py
- examples/benchmark_quality/lr/pipeline-lr-binary.py
- examples/benchmark_quality/lr/pipeline-lr-multi.py
- examples/benchmark_quality/lr/pipeline-sshe-lr-binary.py
- examples/benchmark_quality/lr/pipeline-sshe-lr-multi.py
> update bq Signed-off-by: weijingchen <talkingwallace@sohu.com>

- examples/benchmark_quality/linr/linr_sklearn_config.yaml
- examples/benchmark_quality/lr/breast_lr_sklearn_config.yaml
- examples/benchmark_quality/lr/default_credit_lr_sklearn_config.yaml
- examples/benchmark_quality/lr/epsilon_5k_lr_sklearn_config.yaml
- examples/benchmark_quality/lr/give_credit_lr_sklearn_config.yaml
- examples/benchmark_quality/lr/sklearn-lr-binary.py
- examples/benchmark_quality/lr/sklearn-lr-multi.py
- examples/benchmark_quality/lr/vehicle_lr_sklearn_config.yaml
> benchmark config adopt newer param format for sklearn

- .gitmodules
Signed-off-by: mgqa34 mgq3374541
Changes:
1. update submodules
> update submodules of fate-v2.1.0

- python/fate/ml/preprocessing/feature_scale.py
Signed-off-by: Zhang Hui <zhang_hui0019@163.com>
> fix bugs: min-max scale公式错误修改

- python/fate/ml/aggregator/base.py
> aggregator: support bfloat16 dtype agg

- doc/2.0/fate/quick_start.md
> update quick start

- README.md
- doc/2.0/fate/homo_quick_start.md
- doc/README.md
add doc guide
Changes:
1.  document update
2.
3.
> add homo quick start

- RELEASE.md
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- doc/2.0/fate/dag.md
- doc/2.0/fate/dag.zh.md
> update version of fate to 2.1.1

- doc/2.0/fate/components/hetero_nn.md
> Fix hetero-nn doc

- python/fate/_info.py
> update gitmodules of fate-v2.1.1

- .gitmodules
> update gitmodule file

- .github/workflows/close_inactive_issues.yml
Signed-off-by: sagewe <sagewe@fastmail.com>
> chore: add github action to close state issue

- RELEASE.md
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- doc/2.0/fate/dag.md
- doc/2.0/fate/dag.zh.md
- doc/2.0/fate/homo_quick_start.md
- doc/2.0/fate/quick_start.md
- python/fate/_info.py
> update version of fate

- python/requirements-fate.txt
- python/setup.py
> upgrade pandas's version

- python/requirements-fate.txt
> relax numpy verrsion

- bin/install_os_dependencies.sh
Signed-off-by: robbie228 526714167@qq.com
Changes:
1. update centos mirror in install_os_dependencies.sh
> update centos mirror in install_os_dependencies.sh

- .gitmodules
- deploy/standalone-deploy/README.md
- deploy/standalone-deploy/README.zh.md
- doc/tutorial/README.md
> update guide: modify python3.8 to python3.10

- doc/2.0/fate/components/feature_binning.md
- doc/2.0/fate/components/feature_selection.md
- doc/2.0/fate/model_building_quick_start.md
- doc/2.0/fate/psi_quick_start.md
- doc/README.md
- examples/pipeline/hetero_feature_binning/test_feature_binning_asymmetric.py
- examples/pipeline/hetero_feature_selection/test_feature_selection_binning.py
- examples/pipeline/hetero_feature_selection/test_feature_selection_binning_lr.py
- examples/pipeline/hetero_feature_selection/test_feature_selection_multi_host.py
- examples/pipeline/hetero_feature_selection/test_feature_selection_multi_model.py
Changes:
1. update doc: add new tutorials 
2. update examples 
3.
> Patch doc update

- .github/workflows/codeql-analysis.yml
- .gitmodules
Signed-off-by:mgqa34 mgq3374541@163.com
Changes:
1. update eggroll submodule to v3.2.0
2. fix codeql-analysis
> update  submodule and fix codeqa
